--[[
	Language Localization: deDE
	Translated by: Chiaki EU-Frostwolf <chiakiaccess@hotmail.com>
]]

WIM.AddLocale("deDE", {
    ["WIM (WoW Instant Messenger)"] = true,
    ["_Description"] = "WIM ist ein AddOn, welches einem das vertraute Gefühl über ein Chatsystem zu kommunizieren zurückbringt. In diesem Fenster kannst du WIM individualisieren, um es deinen Bedürfnissen anzupassen.",

    ["_DemoText"] = "Dies ist ein Demonstrationsfenster und ist nicht voll funktionsfähig. Platziere dieses Fenster an die Stelle, an der du alle anderen Fenster erzeugen möchtest. Sobald du fertig bist kannst du das Fenster schließen, um die Einstellungen zu speichern.",

    ["_DateFormat"] = "%d/%m/%Y",

    ["Yes"] = "Ja",
    ["No"] = "Nein",
    ["None"] = "Kein(e)",
    ["Cancel"] = "Abbrechen",
    ["Unknown"] = "Unbekannt",
    ["Click to update..."] = "Klicke um ein Update zu starten...",
    ["Usage"] = "Gebrauch",

    ["state_resting"] = "Ruhend",
    ["state_combat"] = "Kampf",
    ["state_pvp"] = "PVP",
    ["state_arena"] = "Arena",
    ["state_party"] = "Gruppeninstanz",
    ["state_raid"] = "Schlachtzuginstanz",
    ["state_other"] = "Normal (Sonstiges)",

    ["Options"] = "Einstellungen",

    ["Up"] = "Oben",
    ["Down"] = "Unten",
    ["Left"] = "Links",
    ["Right"] = "Rechts",
    ["Ignore"] = "Ignorieren",
    ["Block"] = "Blockieren",
    ["Enable WIM"] = "WIM aktivieren",

    ["Enable"] = "Aktivieren",
    ["Disable"] = "Deaktivieren",
    ["Enable window fading effects."] = "Fenster-Verblassungseffekte aktivieren.",

    ["General"] = "Allgemein",
    ["History"] = "Verlauf",
    ["Filters"] = "Filter",

    ["Include sent messages in /REPLY."] = "Gesendete Nachrichten in /REPLY einschließen.",

    ["Sort tabs by:"] = "Sortiere Tabs:",
    ["Window Created"] = "Fenster erstellt",
    ["Last Activity"] = "Letzte Aktivität",
    ["Alphabetical"] = "Alphabetisch",

    -- Class Names --
    ["Druid"] = LOCALIZED_CLASS_NAMES_MALE.DRUID,
    ["Hunter"] = LOCALIZED_CLASS_NAMES_MALE.HUNTER,
    ["Mage"] = LOCALIZED_CLASS_NAMES_MALE.MAGE,
    ["Paladin"] = LOCALIZED_CLASS_NAMES_MALE.PALADIN,
    ["Priest"] = LOCALIZED_CLASS_NAMES_MALE.PRIEST,
    ["Rogue"] = LOCALIZED_CLASS_NAMES_MALE.ROGUE,
    ["Shaman"] = LOCALIZED_CLASS_NAMES_MALE.SHAMAN,
    ["Warlock"] = LOCALIZED_CLASS_NAMES_MALE.WARLOCK,
    ["Warrior"] = LOCALIZED_CLASS_NAMES_MALE.WARRIOR,
    ["Death Knight"] = LOCALIZED_CLASS_NAMES_MALE.DEATHKNIGHT,
    ["Monk"] = LOCALIZED_CLASS_NAMES_MALE.MONK,
    ["Demon Hunter"] = LOCALIZED_CLASS_NAMES_MALE.DEMONHUNTER,
	["Evoker"] = LOCALIZED_CLASS_NAMES_MALE.EVOKER,

    -- Female Class Names --
    ["DruidF"] = LOCALIZED_CLASS_NAMES_FEMALE.DRUID,
    ["HunterF"] = LOCALIZED_CLASS_NAMES_FEMALE.HUNTER,
    ["MageF"] = LOCALIZED_CLASS_NAMES_FEMALE.MAGE,
    ["PaladinF"] = LOCALIZED_CLASS_NAMES_FEMALE.PALADIN,
    ["PriestF"] = LOCALIZED_CLASS_NAMES_FEMALE.PRIEST,
    ["RogueF"] = LOCALIZED_CLASS_NAMES_FEMALE.ROGUE,
    ["ShamanF"] = LOCALIZED_CLASS_NAMES_FEMALE.SHAMAN,
    ["WarlockF"] = LOCALIZED_CLASS_NAMES_FEMALE.WARLOCK,
    ["WarriorF"] = LOCALIZED_CLASS_NAMES_FEMALE.WARRIOR,
    ["Death KnightF"] = LOCALIZED_CLASS_NAMES_FEMALE.DEATHKNIGHT,
    ["MonkF"] = LOCALIZED_CLASS_NAMES_FEMALE.MONK,
    ["Demon HunterF"] = LOCALIZED_CLASS_NAMES_FEMALE.DEMONHUNTER,
	["EvokerF"] = LOCALIZED_CLASS_NAMES_FEMALE.EVOKER,

    ["Game Master"] = "Spielmeister",

    -- WIM.lua --
    ["Toggle WIM 'On' and 'Off'."] = "Schalte WIM 'Ein' oder 'Aus'.",
    ["Toggle Debugging Mode 'On' and 'Off'."] = "Schalte Debugging Modus 'Ein' oder 'Aus'",

    -- Filters.lua --
    ["Whispers Sent by Addons"] = "Flüsternachrichten gesendet durch AddOns",
    ["WhisperSelect Part 1"] = "FlüsterAuswahl Teil 1",
    ["Example Spam Blocker"] = "Beispiel Spamblocker",
    ["WhisperSelect Part 2"] = "FlüsterAuswahl Teil 2",
    ["Filter Name"] = "Filtername",
    ["Filter By"] = "Filtern nach",
    ["Pattern"] = "Muster",
    ["User Type"] = "Spielertyp",
    ["Level"] = "Level",
    ["Friends"] = "Freunde",
    ["Guild Members"] = "Gildenmitglieder",
    ["Party Members"] = "Gruppenmitglieder",
    ["Raid Members"] = "Schlachtzugsmitglieder",
    ["Cross-Realm"] = "Realm-Übergreifend",
    ["Everyone"] = "Alle",
    ["User must be at least level:"] = "Spieler muss mindestens diesen Level haben:",
    ["Apply to messages received."] = "Für eingehende Nachrichten übernehmen.",
    ["Apply to messages sent."] = "Für ausgehende Nachrichten übernehmen.",
    ["Apply to:"] = "Anwenden auf:",
    ["All Classes"] = "Alle Klassen",
    ["Action to Perform:"] = "Durchzuführende Aktion:",
    ["Allow"] = "Erlauben",
    ["Ignore"] = "Ignorieren",
    ["Blocked"] = "Blockieren",
    ["Save"] = "Speichern",
    ["Cancel"] = "Abbrechen",
    ["Edit Filter"] = "Filter bearbeiten",
    ["Add Filter"] = "Filter hinzufügen",

    -- History.lua --
    ["WIM History Button"] = "WIM Verlaufsbutton",
    ["Click to view message history."] = "Klicken um den Nachrichtenverlauf anzuzeigen.",
    ["WIM pruned %d |4message:messages; from your history."] = "WIM hat %d |4message:messages; von deinem Nachrichtenverlauf gelöscht.",
    ["History Viewer"] = "Verlaufsanzeige",
    ["Filters"] = "Filter",
    ["Are you sure you want to delete all history saved for %s on %s?"] = "Bist du sicher, dass du sämtliche Nachrichtenverläufe gespeichert für %s auf %s löschen möchtest?",
    ["Search resulted in %d |4message:messages;."] = "Ergebnis der Suche resultiert in %d |4message:messages;.",
    ["No results found!"] = "Keine Ergebnisse gefunden!",
    ["Search"] = "Suche",
    ["Show All"] = "Alle anzeigen",
    ["Loading History"] = "Verlauf wird geladen",
    ["Chat View"] = "Chatansicht",
    ["Text View"] = "Textansicht",
    ["BBCode"] = "BBCode",
    ["WIM History Viewer can be accessed any time by typing:"] = "WIM Verlaufsanzeige kann jederzeit aufgerufen werden durch drücken von:",
    ["WIM History Viewer"] = "WIM Verlaufsanzeige",
    ["Display history viewer."] = "Verlaufsanzeige anzeigen",

    -- ldb.lua --
    ["No New Messages"] = "Keine neuen Nachrichten",

    -- Menu.lua --
    ["Whispers"] = "Flüsternachrichten",
    ["Chat"] = true,

    -- Negotiate.lua --
    ["WIM Update Available!"] = "WIM Update verfügbar!",

    -- ShortcutBar.lua --
    ["Player Location"] = "Spieler Standort",
    ["Unknown"] = "Unbekannt",
    ["Click to update..."] = "Klicke um ein Update zu starten...",
    ["Invite to Party"] = "In die Gruppe einladen",
    ["Invite to Guild"] = "In die Gilde einladen",
    ["Add Friend"] = "Freund hinzufügen",
    ["Ignore Player"] = "Spieler ignorieren",
    ["Are you sure you want to\nignore %s?"] = "Bist du sicher, dass du \n %s ignorieren willst?",
	["Copy Name"] = "Namen kopieren",
	["Profile Links"] = "Profil-Links",
	["Location"] = "Standort",
	["Game"] = "Spiel",
	["Realm"] = "Realm",
	["Character"] = "Charakter",
	["Right-Click for profile links..."] = "Rechtsklick für Profil-Links...",

    -- Tutorials.lua --
    ["View Updates"] = "Updates ansehen",

    -- WhisperEngine.lua --
    ["Whisper Received!"] = "Flüsternachricht erhalten!",
    ["Recently Sent Messages"] = "Zuletzt gesendete Nachrichten",
    ["Users in %s"] = "Benutzer in %s",

    -- Clear.lua --
    ["You are about to clear all of WIM's history!"] = "Du bist dabei den gesamten WIM Nachrichtenverlauf zu löschen!",
    ["This action will reload your user interface."] = "Dieser Vorgang wird dein Interface neu laden.",
    ["Do you want to continue?"] = "Willst du fortfahren?",
    ["You are about to restore WIM's filters to it's default settings!"] = "Du bist dabei die WIM Filtereinstellungen auf die Standardeinstellungen zurückzusetzen!",
    ["Usage"] = "Gebrauch",
    ["Clear various WIM data."] = "Lösche diverse WIM Daten.",

    -- SlashHandler.lua --
    ["WIM Slash Commands"] = "WIM Slash-Befehle",
    ["Hide or show {all, whisper, chat} windows."] = "Alle, Flüster- oder Chat-Fenster ein-/ausblenden.",
    ["To see a list of available WIM slash commands type:"] = "Um eine Liste von verfügbaren WIM-Befehlen zu erhalten gebe ein:",
    ["Display available slash commands."] = "Zeige verfügbare Slash-Befehle an.",
    ["Reload User Interface."] = "Lade Spieler-Interface neu.",

    -- TabHandler.lua --
    ["Manipulating Tabs"] = "Manipulation von Tabs",

    -- WindowHandler.lua --
    ["Window Resized!"] = "Fenstergröße angepasst!",
    ["Creating Tab Groups"] = "Erstellung von Tab-Gruppen",
    ["You can group two or many windows together by <Shift-Clicking> a window and dragging it on top of another."] = "Du kannst zwei oder mehrere Fenster zusammengruppieren indem du ein Fenster <Shift-Klickst> und es auf ein anderes ziehst.",
    ["Resizing Windows"] = "Größenanpassung von Fenstern",
    ["You can resize a window by holding <Shift> and dragging the bottom right corner of the window."] = "Du kannst die Größe eines Fensters anpassen, indem du <Shift> gedrückt hältst und die obere rechte Ecke des Fensters ziehst.",
    ["Demo Window"] = "Demonstrationsfenster",
    ["<Shift-Click> to close window."] = "<Shift-Klick> zum Schließen des Fensters.",
    ["Message Window Hidden"] = "Nachrichtenfenster versteckt",
    ["Default"] = "Standard",
    ["%s is Away From Keyboard: %s"] = "%s ist AFK (Away From Keyboard/Abwesend): %s",
    ["%s does not wish to be disturbed: %s"] = "%s möchte nicht gestört werden: %s",
    ["Right-Mouse Click!"] = "Rechtsklick!",
    ["There might be useful tools hidden under the message box. Right-Click to see them!"] = "Unter dem Nachrichtenfeld könnten nützliche Werkzeuge verborgen sein. Rechtsklick zum Anzeigen!",

    -- Options.lua --
    ["Display WIM's options."] = "WIM Optionen anzeigen.",
    ["Resetting WIM will clear all of your settings!"] = "Das Zurücksetzen von WIM wird sämtliche deiner Einstellungen löschen!",
    ["A reset will reload your user interface."] = "Ein Zurücksetzen wird deine Benutzeroberfläche neu laden.",
    ["Reset all options to default."] = "Alle Einstellungen zurücksetzen.",

    -- CoreOptions --
    ["Created By:"] = "Kreiert von:",
    ["Special Thanks:"] = "Besonderer Dank:",
    ["Welcome!"] = "Willkommen!",
    ["Enable WIM"] = "WIM aktivieren",
    ["Display Minimap Icon"] = "Minimap-Symbol anzeigen",
    ["<Right-Click> to show unread messages."] = "<Rechts-Klick> um ungelesene Nachrichten anzuzeigen.",
	["Display Addon Compartment Icon"] = "Icon des Addon-Fachs anzeigen",
    ["Display Tutorials"] = "Tutorials anzeigen",
    ["Reset Tutorials"] = "Tutorials zurücksetzen",
    ["Credits"] = "Danksagungen",
    ["This is a long message which contains both emoticons and urls 8). WIM's home is www.WIMAddon.com."] = "Dies ist eine lange Nachricht, die sowohl Emoticons/Smileys, als auch Internetadressen enthält 8). WIMs Homepage ist www.WIMAddon.com.",
    ["Message Formatting"] = "Nachrichtenformatierung",
    ["Manipulate how WIM displays messages."] = "Stelle ein, wie WIM Nachrichten darstellen soll.",
    ["Preview"] = "Vorschau",
    ["Display Time Stamps"] = "Zeitstempel anzeigen",
    ["Display Emoticons"] = "Emoticons/Smileys anzeigen",
    ["Display URLs as Links"] = "Internetadressen als Links anzeigen",
    ["Indent long messages."] = "Lange Nachrichten einrücken.",
    ["Window Behavior"] = "Fensterverhalten",
    ["Bracket names."] = "Namen einklammern.",
    ["You can control how windows behave while you are in different situations."] = "Du kannst das Verhalten von Fenstern in verschiedenen Situationen einstellen.",
    ["Intercept Slash Commands"] = "Slash-Befehle abfangen",
	["Obey autofocus rules when opening frames via the menu. (autofocus if unchecked)"] = "Respektiere beim Öffnen via des Menüs die autofocus-Einstellung.",
    ["Use the same rules for all states."] = "Dieselben Regeln für alle Situationen anwenden.",
    ["Behaviors for state:"] = "Verhalten für Situation:",
    ["Pop-Up window when message is sent."] = "Fenster als Pop-Up sobald Nachricht versendet wurde.",
    ["Pop-Up window when message is received."] = "Fenster als Pop-Up sobald Nachricht erhalten wurde.",
    ["Auto focus a window when it is shown."] = "Automatischer Textcursor-Fokus wenn sich ein Fenster öffnet.",
    ["Keep focus on window after sending a message."] = "Textcursor-Fokus nach der Nachrichtenversendung beibehalten.",
    ["Suppress messages from the default chat frame."] = "Nachrichten vom Standard-Chatfenster unterdrücken.",
    ["Window Settings"] = "Fenstereinstellungen",
    ["Some settings may be limited by certain skins."] = "Manche Einstellungen können auf bestimmte Skins begrenzt sein.",
    ["Default Width"] = "Standardbreite",
    ["Default Height"] = "Standardhöhe",
    ["Window Scale"] = "Fensterskalierung",
    ["Window Alpha"] = "Fenstertransparenz",
    ["Set Window Spawn Location"] = "Stelle Erzeugungspunkt für Fenster ein",
    ["Up"] = "Oben",
    ["Down"] = "Unten",
    ["Left"] = "Links",
    ["Right"] = "Rechts",
    ["Cascade overlapping windows."] = "Überlappende Fenster hintereinanderschalten.",
    ["Ignore arrow keys in message box."] = "Pfeiltasten im Nachrichtenfenster ignorieren.",
    ["Allow <ESC> to hide windows."] = "<ESC> zum verstecken von Fenstern erlauben.",
    ["Display Settings"] = "Anzeige-Einstellungen",
    ["Configure general window display settings."] = "Allgemeine Einstellungen zur Fensteranzeige konfigurieren.",
    ["Window Skin:"] = "Fenster-Skin:",
    ["Version"] = true,
    ["Color: System Messages"] = "Farbe: Systemnachrichten",
    ["Color: Error Messages"] = "Farbe: Fehlernachrichten",
    ["Color: URL - Web Addresses"] = "Farbe: Internetadressen",
    ["Color: History Messages Sent"] = "Farbe: Versendete Nachrichten im Nachrichtenverlauf",
    ["Color: History Messages Received"] = "Farbe: Empfangene Nachrichten im Nachrichtenverlauf",
    ["Use colors suggested by skin."] = "Verwende für den Skin empfohlene Farben.",
    ["Enable window fading effects."] = "Fenster-Verblassungseffekte aktivieren.",
    ["Enable window animation effects."] = "Fenster-Animationseffekte aktivieren.",
    ["Display item links when hovering over them."] = "Itemlinks bei Mouseover anzeigen.",
    ["Fonts"] = "Schriftarten",
    ["Configure the fonts used in WIM's message windows."] = "Schriftarten in den WIM Nachrichtenfenstern konfigurieren.",
    ["Font Outline"] = "Schriftart-Außenlinie",
    ["Thin"] = "Dünn",
    ["Thick"] = "Dick",
    ["Use font suggested by skin."] = "Verwende für den Skin empfohlene Schriftart.",
    ["Chat Font Size"] = "Chat Schriftgröße",
    ["Configure general display settings when dealing with whispers."] = "Konfiguriere allgemeine Darstellungsoptionen bei Flüsternachrichten.",
    ["Color: Messages Sent"] = "Farbe: Gesendete Nachrichten",
    ["Color: Messages Received"] = "Farbe: Empfangene Nachrichten",
    ["Use colors suggested by skin."] = "Verwende für den Skin empfohlene Farben.",
    ["Display user class icons and details."] = "Zeige Spieler Klassensymbole und Details an.",
    ["Requires who lookups."] = "Benötigt /wer Abfragen.",
    ["Display Shortcut Bar"] = "Zeige Funktionsleiste (rechts) an.",
    ["Allow"] = "Erlauben",
    ["Ignore"] = "Ignorieren",
    ["Block"] = "Blockieren",
    ["Filtering"] = "Filterung",
    ["Filtering allows you to control which messages are handled as well as how they are handled by WIM."] = "Filtern erlaubt dir die Kontrolle darüber zu haben welche Nachrichten wie von WIM gehandhabt werden.",
    ["Enable Filtering"] = "Filterung aktivieren.",
    ["Protected"] = "Gesichert",
    ["Action:"] = "Aktion:",
    ["Occurrences:"] = "Vorfälle:",
    ["Delete Filter"] = "Filter löschen",
    ["History"] = "Nachrichtenverlauf",
    ["WIM can store conversations to be viewed at a later time."] = "WIM kann Konversationen speichern, um sie zu einem späteren Zeitpunkt wieder anzuzeigen.",
    ["Enable History"] = "Nachrichtenverlauf aktivieren.",
    ["Messages"] = "Nachrichten",
    ["Preview history inside message windows."] = "Vorschau des Nachrichtenverlaufs innerhalb \n der Nachrichtenfenster anzeigen.",
    ["Record Friends"] = "Freunde aufzeichnen",
    ["Record Guild"] = "Gildenmitglieder aufzeichnen",
    ["Record Everyone"] = "Alle aufzeichen",
    ["Record Chat"] = "Chat aufzeichnen",
    ["Maintenance"] = "Wartung",
    ["Allowing your history logs to grow too large will affect the game's performance, therefore it is reccomended that you use the following options."] = "Wenn du deinen Nachrichtenverläufen ermöglichst \n zu lang/groß zu werden, könnte dies die Performance des Spiels beeinträchtigen, deswegen ist es empfehlenswert, dass du folgende Einstellungen nutzt.",
    ["Save a maximum number of messages per person."] = "Speichere eine Maximalzahl an Nachrichten pro Spieler.",
    ["%d |4Week:Weeks;"] = "%d |4Woche:Wochen;",
    ["Automatically delete old messages."] = "Automatisch alte Nachrichten löschen.",
    ["WIM-2-WIM is a feature which allows users with WIM to interact in ways that normal whispering can not."] = "WIM-2-WIM ist eine Funktion, die WIM erlaubt mit Spielern, die ebenfalls WIM nutzen, auf bestimmte Arten zu interagieren, die über normales Flüstern nicht möglich sind.",
    ["Enable WIM-2-WIM"] = "WIM-2-WIM aktivieren",
    ["Privacy"] = "Privatsphäre",
    ["Restrict the data that is shared."] = "Austauschbare Daten eingrenzen.",
    ["Allow others to see me typing."] = "Erlaube Anderen zu sehen, wann ich tippe.",
    ["Allow others to see my location."] = "Erlaube Anderen meinen Standort zu sehen.",
    ["Main"] = "Haupteinstellungen",
    ["General"] = "Allgemein",
    ["User Level"] = "Spielerlevel",
    ["Windows will also be hidden when frames such as the world map are shown."] = "Fenster werden ebenfalls versteckt, sobald andere Fenster, wie etwa die Weltkarte, angezeigt werden.",
    ["Sounds"] = "Sounds",
    ["Configure various sound events and how they are triggered."] = "Verschiedene Sound-Ereignisse und deren Auslösung konfigurieren.",
    ["Play sound when a whisper is received."] = "Sound abspielen, wenn ein Flüstern empfangen wird.",
    ["Play special sound for friends."] = "Speziellen Sound für Freunde abspielen.",
    ["Play special sound for battle.net friends."] = "Speziellen Sound für Battle.net-Freunde abspielen.",
    ["Play special sound for guild members."] = "Speziellen Sound für Gildenmitglieder abspielen.",
    ["Play sound when a whisper is sent."] = "Sound abspielen, wenn ein Flüstern gesendet wird.",
    ["Allow others to see my talent spec."] = "Erlaube Anderen, meine Talentspezialisierung zu sehen.",
    ["Window Strata:"] = "Fensterebene:",
	["Background"] = BACKGROUND,
	["Low"] = LOW,
	["Medium"] = "Mittel",
	["High"] = "Hoch",
	["Dialog"] = ENABLE_DIALOG,
	["Tooltip"] = true,
    ["Unlock from Minimap"] = "Von der Minikarte lösen",
    ["Press <Tab> to advance to next tell target."] = "<Tab> drücken, um zum nächsten Whisper-Ziel zu wechseln.",
    ["Force sounds when game sound is disabled."] = "Sound erzwingen, auch wenn der Spielsound deaktiviert ist.",
    ["Colorize names."] = "Namen einfärben.",
    ["Clamp window to screen."] = "Fenster am Bildschirmrand begrenzen.",
    ["Group with whisper windows."] = "Mit Whisper-Fenstern gruppieren.",
    ["Color: BNet Messages Sent"] = "Farbe: Gesendete BNet-Nachrichten",
    ["Color: BNet Messages Received"] = "Farbe: Empfangene BNet-Nachrichten",

    -- TabManagement.lua --
    ["Tab Management"] = true,
    ["Automatically manage your open windows and place them into appropriate tab groups."] = "Manage automatisch deine offenen Fenster und platziere sie in angemessene Tabgruppen.",
    ["Automatically group whispers."] = "Automatische Gruppen-Flüsternachrichten.",
    ["Place friends in their own group."] = "Platziere Freunde in ihre eigene Gruppe.",
    ["Place guild members in their own group."] = "Platziere Gildenmitglieder in ihre eigene Gruppe.",
    ["Automatically group chat windows."] = "Chat-Fenster automatisch gruppieren.",
    ["Does not apply to windows already opened."] = "Wird nicht für Fenster übernommen, die bereits geöffnet sind.",

    -- Talent Specs --
    ["Hybrid"] = "Hybride",

    -- Filters.lua --
    ["Show Alert"] = "Warnung anzeigen",
    ["WIM has blocked a message from %s."] = "WIM hat eine Nachricht von %s blockiert.",
    ["View Blocked Message"] = "Blockierte Nachricht anzeigen",
    ["Blocked Message"] = "Blockierte Nachricht",

    -- MinimapIcon.lua
    ["Show Unread Messages"] = "Zeige ungelesene Nachrichten",
    ["Show All Windows"] = "Zeige alle Fenster",
    ["Hide All Windows"] = "Verberge alle Fenster",

    -- Emoticons.lua --
    ["Also"] = "Auch",
    ["More"] = "Mehr",
    ["Emoticons"] = "Emoticons",

    -- Expose.lua --
    ["Your conversations have been hidden in order to clear your screen while in combat. To disable this feature type"] = "Deine Gespräche wurden ausgeblendet, um den Bildschirm im Kampf zu bereinigen. Zum Deaktivieren gib ein:",
    ["Expose"] = "Expose",
    ["Expose is a Mac OS X inspired feature which enables you to quickly clear your screen of windows and then restore them back to their original position."] = "Expose ist eine von macOS inspirierte Funktion, mit der du schnell alle Fenster vom Bildschirm entfernen und anschließend wieder in ihre ursprüngliche Position zurückbringen kannst.",
    ["Auto hide/restore windows during combat."] = "Fenster im Kampf automatisch aus-/einblenden.",
    ["Delay if I am typing a message."] = "Verzögern, wenn ich gerade eine Nachricht tippe.",
    ["Border Size"] = "Rahmengröße",
    ["Only while in an instance."] = "Nur in Instanzen.",
    ["Show Border"] = "Rahmen anzeigen",
    ["Animation Direction:"] = "Animationsrichtung:",

    -- ChatEngine.lua --
    ["WIM will manage this chat type within its own message windows."] = "WIM verwaltet diesen Chattyp in eigenen Nachrichtenfenstern.",
    ["Show Minimap Alerts"] = "Minikartenwarnungen anzeigen",
    ["Never pop-up on my screen."] = "Nie als Popup auf meinem Bildschirm anzeigen.",
    ["Never suppress messages."] = "Keine Nachrichtenunterdrückung.",
    ["Include emotes."] = "Emotes einschließen.",
    ["Have WIM monitor this channel."] = "WIM soll diesen Kanal überwachen.",
    ["Never Pop"] = "Nie Popup",
    ["Never have this window pop-up on my screen."] = "Dieses Fenster niemals als Popup anzeigen.",
    ["Never Suppress"] = "Nie unterdrücken",
    ["Never suppress messages from the default chat frame."] = "Keine Nachrichten im Standard-Chatfenster unterdrücken.",
    ["Show unread message alert on minimap."] = "Warnung für ungelesene Nachrichten auf der Minikarte anzeigen.",
    ["No History"] = "Kein Verlauf",
    ["Do not record history for this channel."] = "Keinen Verlauf für diesen Kanal speichern.",
    ["World Chat"] = "Weltchat",
    ["Custom Chat"] = "Benutzerdefinierter Chat",
    ["Community Chat"] = "Community-Chat",
    ["Community Chats"] = "Community-Chats",
    ["Chat"] = "Chat",
    ["Play special sound for %s."] = "Speziellen Sound für %s abspielen.",
    ["Play sound when a message is received."] = "Sound bei eingehender Nachricht abspielen.",
    ["Play sound when a message is sent."] = "Sound bei gesendeter Nachricht abspielen.",
    ["Do not play sounds for this channel."] = "Keine Sounds für diesen Kanal abspielen.",
    ["No Sound"] = "Kein Sound",
    ["Sensitivity"] = "Empfindlichkeit",
    ["Enable WorldFrame Click Detection."] = "WorldFrame-Klickerkennung aktivieren.",

    -- OffScreenTracker.lua --
    ["WIM Window Off Screen"] = "WIM-Fenster außerhalb des Bildschirms",
    ["Click to reposition."] = "Klicken zum Neupositionieren.",

    -- Whisper Mode Warnings --
    ["Whisper Mode: In-line"] = "Flüstermodus: Inline",
    ["Set whispers to In-line"] = "Flüstern auf Inline setzen",
    ["Message suppression requires whispers to be set to 'In-line'."] = "Nachrichtenunterdrückung erfordert, dass Flüstern auf 'Inline' gesetzt ist.",
    ["It is recommended for whispers to be set to in-line in order to handle their behavior properly."] = "Es wird empfohlen, Flüstern auf Inline zu setzen, um das Verhalten korrekt zu verarbeiten.",

    -- Skins --
    ["Blue"] = "Blau",
    ["Green"] = "Grün",
    ["Red"] = "Rot",
    ["Yellow"] = "Gelb",

    -- Battle.net friend consolidation (History Viewer)
    ["Battle.net Friends"] = "Battle.net-Freunde",
    ["Are you sure you want to delete ALL history saved with %s, across every realm and every character on this account?"] = "Bist du sicher, dass du ALLE mit %s gespeicherten Nachrichtenverläufe über alle Realms und Charaktere dieses Accounts löschen möchtest?",

    -- Per-date deletion from the History Viewer filter list
    ["Are you sure you want to delete the %s history with %s across every realm and character on this account?"] = "Bist du sicher, dass du die Nachrichtenverläufe vom %s mit %s über alle Realms und Charaktere dieses Accounts löschen möchtest?",
    ["Are you sure you want to delete the %s history for %s across every character on %s?"] = "Bist du sicher, dass du die Nachrichtenverläufe vom %s für %s über alle Charaktere auf %s löschen möchtest?",
    ["Are you sure you want to delete the %s history for %s on %s?"] = "Bist du sicher, dass du die Nachrichtenverläufe vom %s für %s auf %s löschen möchtest?",


    -- Modern options panel --
    ["Use modern options UI"] = "Moderne Einstellungen-Oberfläche verwenden",
    ["Classic Options"] = "Klassische Einstellungen",
    ["Open"] = "Öffnen",
    ["Open the classic WIM options window."] = "Klassisches WIM-Einstellungsfenster öffnen.",
    ["Choose the options style: /wim style [classic|modern]."] = "Wähle den Stil der Einstellungen: /wim style [classic|modern].",
    ["When enabled, WIM's Options entry points (minimap menu, key binding, /wim) open this panel instead of the classic WIM options window."] = "Wenn aktiviert, öffnen WIMs Einstiegspunkte zu den Optionen (Minimap-Menü, Tastenbelegung, /wim) dieses Panel statt des klassischen WIM-Einstellungsfensters.",
    ["While a modern-only skin (such as WIM Modern) is selected, this option is enforced: those skins are configured through this panel only."] = "Solange ein rein moderner Skin (wie WIM Modern) ausgewählt ist, ist diese Option erzwungen: Diese Skins werden ausschließlich über dieses Panel konfiguriert.",

    -- Modern skin styling --
    ["Modern Skin"] = "Moderner Skin",
    ["These settings style WIM's modern-only skins (such as WIM Modern), which are built from the game's own interface art. They shape the History Viewer and the chat windows, and are available only while a modern-only skin is selected under General > Display Settings; with a classic skin active they are greyed out."] = "Diese Einstellungen gestalten WIMs rein moderne Skins (wie WIM Modern), die aus der Oberflächengrafik des Spiels aufgebaut sind. Sie formen die Verlaufsanzeige und die Chatfenster und sind nur verfügbar, solange unter Allgemein > Anzeige-Einstellungen ein rein moderner Skin ausgewählt ist; bei aktivem klassischem Skin sind sie ausgegraut.",
    ["Disabled while a modern-only skin (such as WIM Modern) is selected: those skins carry settings the classic window has no controls for."] = "Deaktiviert, solange ein rein moderner Skin (wie WIM Modern) ausgewählt ist: Diese Skins enthalten Einstellungen, für die das klassische Fenster keine Steuerelemente hat.",
    ["Frame background"] = "Rahmenhintergrund",
    ["Message area background"] = "Hintergrund des Nachrichtenbereichs",
    ["Chat history background"] = "Chatverlauf-Hintergrund",
    ["Selection panels background"] = "Hintergrund der Auswahlpanels",
    ["Window frame background"] = "Fensterrahmen-Hintergrund",
    ["None (game default)"] = "Keiner (Spielstandard)",
    ["Panels see through to the game world"] = "Panels blicken auf die Spielwelt durch",
    ["Window sees through to the game world"] = "Fenster blickt auf die Spielwelt durch",
    ["Draws the frame background only around the panels, so a clear panel background (None or Transparent) shows the game world behind the viewer instead of the frame fill."] = "Zeichnet den Rahmenhintergrund nur um die Panels, sodass ein transparenter Panel-Hintergrund (Keiner oder Transparent) die Spielwelt hinter der Verlaufsanzeige statt der Rahmenfüllung zeigt.",
    ["Draws the window frame background only around the message area, so a clear message area background (None or Transparent) shows the game world behind the window."] = "Zeichnet den Fensterrahmen-Hintergrund nur um den Nachrichtenbereich, sodass ein transparenter Hintergrund des Nachrichtenbereichs (Keiner oder Transparent) die Spielwelt hinter dem Fenster zeigt.",

    -- Roleplay profiles (Total RP 3 / Mary Sue Protocol) --
    ["Roleplay Profiles"] = "Rollenspiel-Profile",
    ["Enable roleplay profile integration"] = "Integration von Rollenspiel-Profilen aktivieren",
    ["Whisper windows show roleplay profile fields from Total RP 3 or any Mary Sue Protocol addon, and gain an Open RP Profile button on their shortcut bar that opens the partner's profile in the installed viewer."] = "Flüsterfenster zeigen Rollenspiel-Profilfelder von Total RP 3 oder einem beliebigen Mary-Sue-Protocol-AddOn und erhalten in ihrer Funktionsleiste eine Schaltfläche 'RP-Profil öffnen', die das Profil des Gegenübers im installierten Betrachter öffnet.",
    ["Open RP Profile"] = "RP-Profil öffnen",
    ["Displayed profile fields"] = "Angezeigte Profilfelder",
    ["Whisper windows show the selected fields from the partner's Total RP 3 or Mary Sue Protocol profile. Fields left unselected -- or without profile data -- keep the standard display."] = "Flüsterfenster zeigen die ausgewählten Felder aus dem Total-RP-3- oder Mary-Sue-Protocol-Profil des Gegenübers. Nicht ausgewählte Felder – oder Felder ohne Profildaten – behalten die Standarddarstellung.",
    ["First Name"] = "Vorname",
    ["Last Name"] = "Nachname",
    ["Title"] = "Titel",
    ["Full Title"] = "Voller Titel",
    ["Race"] = "Volk",
    ["Class"] = "Klasse",
    ["Portrait"] = "Porträt",
    ["Name & Class Color"] = "Farbe von Name & Klasse",
    ["The profile's first name, shown as the window's name text."] = "Der Vorname des Profils, als Namenstext des Fensters angezeigt.",
    ["The profile's last name, shown as the window's name text."] = "Der Nachname des Profils, als Namenstext des Fensters angezeigt.",
    ["The short title, shown on the window's details line."] = "Der kurze Titel, in der Detailzeile des Fensters angezeigt.",
    ["The long title, shown on the window's details line and portrait tooltip."] = "Der lange Titel, in der Detailzeile des Fensters und im Porträt-Tooltip angezeigt.",
    ["The custom race, replacing the character's race on the details line."] = "Das eigene Volk, das das Volk des Charakters in der Detailzeile ersetzt.",
    ["The custom class, replacing the character's class on the details line."] = "Die eigene Klasse, die die Klasse des Charakters in der Detailzeile ersetzt.",
    ["The profile's icon, replacing the class icon."] = "Das Symbol des Profils, das das Klassensymbol ersetzt.",
    ["The profile's custom color, applied to the window's name text and to the class on the details line."] = "Die eigene Farbe des Profils, angewandt auf den Namenstext des Fensters und die Klasse in der Detailzeile.",
    ["Apply filter to character menus"] = "Filter auf Charaktermenüs anwenden",

    -- History Viewer filters --
    ["No Filter"] = "Kein Filter",
    ["Relative Dates"] = "Relative Daten",
    ["%d or more"] = "%d oder mehr",
    ["Fewer than %d"] = "Weniger als %d",
    ["Results Filtered"] = "Ergebnisse gefiltert",
    ["-- Results Filtered --"] = "-- Ergebnisse gefiltert --",
    ["Results are hidden by the active filter. Click to open the Filters menu."] = "Ergebnisse werden durch den aktiven Filter ausgeblendet. Klicke, um das Filtermenü zu öffnen.",
    ["Click to change how history is filtered."] = "Klicke, um die Verlaufsfilterung zu ändern.",
    ["Click to open the Filters menu."] = "Klicke, um das Filtermenü zu öffnen.",
    ["Clicking the %s button on the message window will show that user's history in WIM's History Viewer."] = "Ein Klick auf die Schaltfläche %s im Nachrichtenfenster zeigt den Verlauf dieses Spielers in WIMs Verlaufsanzeige.",

    -- Message input & formatting --
    ["Wrap the message being typed"] = "Nachricht beim Tippen umbrechen",
    ["Limit wrapped lines"] = "Umbrochene Zeilen begrenzen",
    ["Visible input lines"] = "Sichtbare Eingabezeilen",
    ["Caps how far the input field grows; past the limit the message scrolls inside it."] = "Begrenzt, wie weit das Eingabefeld wächst; über der Grenze scrollt die Nachricht darin.",
    ["The most lines the input field grows to before the message scrolls inside it."] = "Die maximale Anzahl an Zeilen, auf die das Eingabefeld wächst, bevor die Nachricht darin scrollt.",
    ["The input field wraps long messages onto multiple lines, growing downward with the message instead of scrolling it on one line."] = "Das Eingabefeld bricht lange Nachrichten auf mehrere Zeilen um und wächst mit der Nachricht nach unten, statt sie in einer Zeile zu scrollen.",
    ["Timestamp Format"] = "Zeitstempel-Format",
    ["Bracket Style"] = "Klammerstil",
    ["Colors"] = "Farben",
    ["Sound"] = "Sound",

    -- Chat type options --
    ["Chat Windows"] = "Chatfenster",
    ["Monitor"] = "Überwachen",
    ["Record"] = "Aufzeichnen",
    ["Minimap Alerts"] = "Minikarten-Warnungen",

    -- Help, bug reports & links --
    ["Found a bug?"] = "Fehler gefunden?",
    ["Report a Bug"] = "Fehler melden",
    ["Reports are welcome! Click below and follow the instructions in the bug report template."] = "Meldungen sind willkommen! Klicke unten und folge den Anweisungen in der Vorlage für Fehlerberichte.",
    ["Visit us on GitHub"] = "Besucht uns auf GitHub",
    ["Click to copy the link."] = "Klicke, um den Link zu kopieren.",
    ["Press Ctrl+C to copy the link, then open it in your browser."] = "Drücke Strg+C, um den Link zu kopieren, und öffne ihn in deinem Browser.",

    -- Debugging & development slash commands --
    ["Clear the captured debug log."] = "Gespeichertes Debug-Protokoll löschen.",
    ["Set debugging level: /wim debug [0|1|2]. 2 adds verbose chat event tracing."] = "Debugging-Stufe festlegen: /wim debug [0|1|2]. 2 fügt ausführliche Chat-Ereignisverfolgung hinzu.",
    ["Snapshot the next modern context menu while it is open."] = "Momentaufnahme des nächsten modernen Kontextmenüs erstellen, während es geöffnet ist.",
    ["Snapshot UI widget state for skin development: /wim snap all | <Frame.Dot.Path> (bare /wim snap lists the arguments)."] = "Zustand der UI-Widgets für die Skin-Entwicklung festhalten: /wim snap all | <Frame.Dot.Path> (/wim snap ohne Argument listet die Möglichkeiten auf).",

    -- Tutorials & notices --
    ["WIM is currently running. To access WIM's wide array of options type:"] = "WIM läuft derzeit. Um Zugang zu WIMs umfangreichen Optionen zu erhalten, tippe:",
    ["WIM's message window has been hidden to WIM's Minimap Icon. If you want to end a conversation, you may do so by <Shift-Clicking> the close button."] = "Das Nachrichtenfenster wurde auf WIMs Minimap-Symbol versteckt. Wenn du ein Gespräch beenden möchtest, kannst du dies per <Shift-Klick> auf die Schließen-Schaltfläche tun.",
    ["If you want all windows to be this size, you can set the default window size within WIM's options."] = "Wenn alle Fenster diese Größe haben sollen, kannst du die Standardfenstergröße in WIMs Einstellungen festlegen.",
    ["You can <Shift-Click> a tab and drag it out into it's own window."] = "Du kannst einen Tab per <Shift-Klick> greifen und in ein eigenes Fenster herausziehen.",
    ["You received a whisper which was hidden due to your current activity. You can change how whispers behave in WIM's options by typing"] = "Du hast eine Flüsternachricht erhalten, die aufgrund deiner aktuellen Aktivität ausgeblendet wurde. Wie sich Flüstern verhält, kannst du in WIMs Einstellungen ändern, indem du tippst",
    ["Sets the game's Social > Whisper Mode setting to In-line. Without it, suppressed whispers would vanish into a popout chat tab."] = "Setzt die Spieleinstellung 'Soziales > Flüstermodus' auf 'Inline'. Andernfalls würden unterdrückte Flüstern in einem Popup-Chat-Tab verschwinden.",

    -- Community channel maintenance --
    ["Toggle the experimental community channel re-add repair (mutates chat window channels)."] = "Aktiviert die experimentelle Reparatur zum erneuten Beitreten von Community-Kanälen (verändert die Kanäle der Chatfenster).",
    ["Toggle whether WIM focuses community streams at login."] = "Legt fest, ob WIM beim Login Community-Streams fokussiert.",

    -- Misc --
    ["Age"] = "Alter",

    -- History Viewer filter modes --
    ["Sent by Me"] = "Von mir gesendet",
    ["Sent by Them"] = "Von anderen gesendet",
    ["Active Days"] = "Aktive Tage",
    ["Last 1 Day"] = "Letzter Tag",
    ["Last 7 Days"] = "Letzte 7 Tage",
    ["Last 30 Days"] = "Letzte 30 Tage",
    ["Last 90 Days"] = "Letzte 90 Tage",


    -- Chrome background names --
    ["None (fully clear)"] = "Keine (vollständig transparent)",
    ["Transparent"] = "Transparent",
    ["Rock"] = "Fels",
    ["Marble"] = "Marmor",
    ["Dark Marble"] = "Dunkler Marmor",
    ["Bank"] = "Bank",
    ["Guild Vault"] = "Gildenbank",
    ["Dark Sandstone"] = "Dunkler Sandstein",
    ["Parchment (Tileable)"] = "Pergament (kachelbar)",
    ["Quest Parchment"] = "Questpergament",
    ["Raid Frame"] = "Schlachtzugsfenster",
    ["Destiny"] = "Schicksal",
    ["Stationery (Auction)"] = "Briefpapier (Auktion)",
    ["Stationery (Illustrated)"] = "Briefpapier (illustriert)",
    ["Stationery (Orgrimmar)"] = "Briefpapier (Orgrimmar)",
    ["Stationery (Thunder Bluff)"] = "Briefpapier (Donnerfels)",
    ["Stationery (Undercity)"] = "Briefpapier (Unterstadt)",
    ["Stationery (Plain)"] = "Briefpapier (einfach)",
    ["World Map 1"] = "Weltkarte 1",
    ["World Map 2"] = "Weltkarte 2",
    ["Achievement Stats"] = "Erfolgsstatistiken",
    ["Adventure Map Parchment"] = "Abenteuerkarten-Pergament",
    ["Collections"] = "Sammlungen",
    ["Frame: Alliance"] = "Rahmen: Allianz",
    ["Frame: Horde"] = "Rahmen: Horde",
    ["Frame: Neutral"] = "Rahmen: Neutral",
    ["Frame: Marine"] = "Rahmen: Marine",
    ["Frame: Mechagon"] = "Rahmen: Mechagon",
    ["Frame: Kyrian"] = "Rahmen: Kyrianer",
    ["Frame: Necrolord"] = "Rahmen: Nekrolords",
    ["Frame: Night Fae"] = "Rahmen: Nachtfey",
    ["Frame: Venthyr"] = "Rahmen: Venthyr",
    ["Frame: Oribos"] = "Rahmen: Oribos",
    ["Frame: Dragonflight"] = "Rahmen: Dragonflight",
    ["Frame: The War Within"] = "Rahmen: The War Within",
    ["Class Hall"] = "Klassenhalle",
    ["Class Hall (Internal)"] = "Klassenhalle (intern)",
    ["Garrison Landing Page"] = "Garnisonslandeplatz",
    ["Garrison Mission"] = "Garnisonsmission",
    ["Ship Mission Parchment"] = "Schiffsmissions-Pergament",
    ["Garrison UI"] = "Garnison-UI",
    ["Garrison UI 2"] = "Garnison-UI 2",
    ["Credits: Classic"] = "Abspann: Classic",
    ["Credits: Burning Crusade"] = "Abspann: Burning Crusade",
    ["Credits: Wrath"] = "Abspann: Wrath",
    ["Credits: Cataclysm"] = "Abspann: Cataclysm",
    ["Credits: Mists of Pandaria"] = "Abspann: Mists of Pandaria",
    ["Credits: Warlords"] = "Abspann: Warlords",
    ["Credits: Legion"] = "Abspann: Legion",
    ["Credits: Battle for Azeroth"] = "Abspann: Battle for Azeroth",


    -- Skin & options style notices --
    ["WIM: the selected skin (%s) is configured through the modern options UI; the classic window is unavailable while it is active."] = "WIM: Der ausgewählte Skin (%s) wird über die moderne Einstellungen-Oberfläche konfiguriert; das klassische Fenster ist während seiner Aktivierung nicht verfügbar.",
    ["WIM: the selected skin (%s) requires the modern options UI; switch to another skin first."] = "WIM: Der ausgewählte Skin (%s) benötigt die moderne Einstellungen-Oberfläche; wechsle zuerst zu einem anderen Skin.",
    ["WIM options style: Modern (native Options > AddOns)."] = "WIM-Einstellungsstil: Modern (im Spiel unter Optionen > AddOns).",
    ["WIM options style: Classic (WIM window)."] = "WIM-Einstellungsstil: Klassisch (WIM-Fenster).",


    -- Slash command feedback --
    ["WIM: community chat settings unavailable."] = "WIM: Community-Chat-Einstellungen nicht verfügbar.",
    ["WIM community stream auto-focus ON. Takes effect at next login."] = "WIM-Community-Stream-Autofokus AN. Wird beim nächsten Login wirksam.",
    ["WIM community stream auto-focus OFF - the client may refuse sends to community channels. Takes effect at next login."] = "WIM-Community-Stream-Autofokus AUS - der Client kann Nachrichten an Community-Kanäle ablehnen. Wird beim nächsten Login wirksam.",
    ["WIM channel re-add repair ON (experimental). On logins where the community stream is focused late, WIM removes and re-adds community channels to ChatFrame1 about 8s after login. If a re-add fails the channel must be restored from the chat settings UI."] = "WIM-Kanal-Reparatur AN (experimentell). Bei Logins, in denen der Community-Stream spät fokussiert wird, entfernt WIM Community-Kanäle etwa 8 Sekunden nach dem Login aus ChatFrame1 und fügt sie neu hinzu. Schlägt das Neuhinzufügen fehl, muss der Kanal über die Chat-Einstellungen wiederhergestellt werden.",
    ["WIM: attempting a repair now (see /wim debug output)."] = "WIM: Reparatur wird jetzt versucht (siehe Ausgabe von /wim debug).",
    ["WIM channel re-add repair OFF. No further attempts this session."] = "WIM-Kanal-Reparatur AUS. Keine weiteren Versuche in dieser Sitzung.",
    ["Usage: /wim style [classic|modern]"] = "Verwendung: /wim style [classic|modern]",
    ["WIM: the modern options UI is not available on this client."] = "WIM: Die moderne Optionsoberfläche ist auf diesem Client nicht verfügbar.",
    ["WIM: queued options open canceled."] = "WIM: Geplantes Öffnen der Optionen abgebrochen.",

    -- Placeholder: Translated with Google Translate, pending a natural language speaker to verify the translation.
    ["Click to switch between Say, Yell, and Emote."] = "Klicken, um zwischen Sagen, Schreien und Emote zu wechseln.",
    ["Say, Yell, or Emote"] = "Sagen, Schreien oder Emote",
    ["Chat Colors"] = "Chatfarben",
    ["Match the game's chat colors."] = "Die Chatfarben des Spiels übernehmen.",
    ["The message being typed takes the color of the chat type it will send as, like the game's own chat box."] = "Die eingegebene Nachricht erhält die Farbe des Chat-Typs, in dem sie gesendet wird, wie im Chatfenster des Spiels.",
    ["Battle.net Whispers"] = "Battle.net-Flüstern",
    ["Filter Editor"] = "Filter-Editor",
    ["Filter area background"] = "Hintergrund des Filterbereichs",
    ["Filter area sees through to the game world"] = "Filterbereich gibt den Blick auf die Spielwelt frei",
    ["Draws the frame background only around the filter area, so a clear filter area background (None or Transparent) shows the game world behind the editor."] = "Zeichnet den Fensterhintergrund nur um den Filterbereich, sodass ein durchsichtiger Filterbereich (Kein oder Transparent) die Spielwelt hinter dem Editor zeigt.",
});
