--[[
    Language Localization: enUS
    Translated by: name <email address>
]]

WIM.AddLocale("enUS", {
    ["WIM (WoW Instant Messenger)"] = true,
    ["_Description"] = "WIM is an addon that brings a familiar feel to communicating through chat in The World of Warcraft. On this screen you will be able to customize WIM to tailor it to your needs.",

    ["_DemoText"] = "This is a demonstration window and is not fully functional. Place this window in the location where you want all other windows to spawn. When finished, you may close this window and your settings will be saved.",

    ["_DateFormat"] = "%m/%d/%Y",

    ["Yes"] = true,
    ["No"] = true,
    ["None"] = true,
    ["Cancel"] = true,
    ["Unknown"] = true,
    ["Click to update..."] = true,
    ["Usage"] = true,

    ["state_resting"] = "Resting",
    ["state_combat"] = "Combat",
    ["state_pvp"] = "PVP",
    ["state_arena"] = "Arena",
    ["state_party"] = "Party Instance",
    ["state_raid"] = "Raid Instance",
    ["state_other"] = "Normal (Other)",

    ["Options"] = true,

    ["Up"] = true,
    ["Down"] = true,
    ["Left"] = true,
    ["Right"] = true,
    ["Ignore"] = true,
    ["Block"] = true,
    ["Enable WIM"] = true,

    ["Enable"] = true,
    ["Disable"] = true,
    ["Enable window fading effects."] = true,

    ["General"] = true,
    ["History"] = true,
    ["Filters"] = true,

	["Include sent messages in /REPLY."] = true,

    ["Sort tabs by:"] = true,
	["Window Created"] = true,
	["Last Activity"] = true,
    ["Alphabetical"] = true,

    -- Class Names --
    ["Druid"] = LOCALIZED_CLASS_NAMES_MALE.DRUID,
    ["Hunter"] = LOCALIZED_CLASS_NAMES_MALE.HUNTER,
    ["Mage"] = LOCALIZED_CLASS_NAMES_MALE.MAGE,
    ["Paladin"] = LOCALIZED_CLASS_NAMES_MALE.PALADIN,
    ["Priest"] = LOCALIZED_CLASS_NAMES_MALE.PRIEST,
    ["Rogue"] = LOCALIZED_CLASS_NAMES_MALE.ROGUE,
    ["Shaman"] = LOCALIZED_CLASS_NAMES_MALE.SHAMAN,
    ["Warlock"] = LOCALIZED_CLASS_NAMES_MALE.WARLOCK,
    ["Warrior"] = LOCALIZED_CLASS_NAMES_MALE.WARRIOR,
    ["Death Knight"] = LOCALIZED_CLASS_NAMES_MALE.DEATHKNIGHT,
    ["Monk"] = LOCALIZED_CLASS_NAMES_MALE.MONK,
    ["Demon Hunter"] = LOCALIZED_CLASS_NAMES_MALE.DEMONHUNTER,
	["Evoker"] = LOCALIZED_CLASS_NAMES_MALE.EVOKER,

    -- Female Class Names --
    ["DruidF"] = LOCALIZED_CLASS_NAMES_FEMALE.DRUID,
    ["HunterF"] = LOCALIZED_CLASS_NAMES_FEMALE.HUNTER,
    ["MageF"] = LOCALIZED_CLASS_NAMES_FEMALE.MAGE,
    ["PaladinF"] = LOCALIZED_CLASS_NAMES_FEMALE.PALADIN,
    ["PriestF"] = LOCALIZED_CLASS_NAMES_FEMALE.PRIEST,
    ["RogueF"] = LOCALIZED_CLASS_NAMES_FEMALE.ROGUE,
    ["ShamanF"] = LOCALIZED_CLASS_NAMES_FEMALE.SHAMAN,
    ["WarlockF"] = LOCALIZED_CLASS_NAMES_FEMALE.WARLOCK,
    ["WarriorF"] = LOCALIZED_CLASS_NAMES_FEMALE.WARRIOR,
    ["Death KnightF"] = LOCALIZED_CLASS_NAMES_FEMALE.DEATHKNIGHT,
    ["MonkF"] = LOCALIZED_CLASS_NAMES_FEMALE.MONK,
    ["Demon HunterF"] = LOCALIZED_CLASS_NAMES_FEMALE.DEMONHUNTER,
	["EvokerF"] = LOCALIZED_CLASS_NAMES_FEMALE.EVOKER,

    ["Game Master"] = true,

    -- WIM.lua --
    ["Toggle WIM 'On' and 'Off'."] = true,
    ["Toggle Debugging Mode 'On' and 'Off'."] = true,

    -- Filters.lua --
    ["Whispers Sent by Addons"] = true,
    ["WhisperSelect Part 1"] = true,
    ["Example Spam Blocker"] = true,
    ["WhisperSelect Part 2"] = true,
    ["Filter Name"] = true,
    ["Filter By"] = true,
    ["Pattern"] = true,
    ["User Type"] = true,
    ["Level"] = true,
    ["Friends"] = true,
    ["Guild Members"] = true,
    ["Party Members"] = true,
    ["Raid Members"] = true,
    ["Cross-Realm"] = true,
    ["Everyone"] = true,
    ["User must be at least level:"] = true,
    ["Apply to messages received."] = true,
    ["Apply to messages sent."] = true,
    ["Apply to:"] = true,
    ["All Classes"] = true,
    ["Action to Perform:"] = true,
    ["Allow"] = true,
    ["Ignore"] = true,
    ["Blocked"] = true,
    ["Save"] = true,
    ["Cancel"] = true,
    ["Edit Filter"] = true,
    ["Add Filter"] = true,

    -- History.lua --
    ["WIM History Button"] = true,
    ["Click to view message history."] = true,
    ["WIM pruned %d |4message:messages; from your history."] = true,
    ["History Viewer"] = true,
    ["Filters"] = true,
    ["Are you sure you want to delete all history saved for %s on %s?"] = true,
    ["Search resulted in %d |4message:messages;."] = true,
    ["No results found!"] = true,
    ["Search"] = true,
    ["Show All"] = true,
    ["Loading History"] = true,
    ["Chat View"] = true,
    ["Text View"] = true,
    ["BBCode"] = true,
    ["WIM History Viewer can be accessed any time by typing:"] = true,
    ["WIM History Viewer"] = true,
    ["Display history viewer."] = true,

    -- ldb.lua --
    ["No New Messages"] = true,

    -- Menu.lua --
    ["Whispers"] = true,
    ["Chat"] = true,

    -- Negotiate.lua --
    ["WIM Update Available!"] = true,

    -- ShortcutBar.lua --
    ["Player Location"] = true,
    ["Unknown"] = true,
    ["Click to update..."] = true,
    ["Invite to Party"] = true,
    ["Invite to Guild"] = true,
    ["Add Friend"] = true,
    ["Ignore Player"] = true,
    ["Are you sure you want to\nignore %s?"] = true,
    ["Right-Click for profile links..."] = true,
	["Profile Links"] = true,
	["Location"] = true,
	["Game"] = true,
	["Realm"] = true,
	["Character"] = true,
	["Copy Name"] = true,

    -- Tutorials.lua --
    ["View Updates"] = true,

    -- WhisperEngine.lua --
    ["Whisper Received!"] = true,
    ["Recently Sent Messages"] = true,

    -- Clear.lua --
    ["You are about to clear all of WIM's history!"] = true,
    ["This action will reload your user interface."] = true,
    ["Do you want to continue?"] = true,
    ["You are about to restore WIM's filters to it's default settings!"] = true,
    ["Usage"] = true,
    ["Clear various WIM data."] = true,

    -- SlashHandler.lua --
    ["WIM Slash Commands"] = true,
    ["Hide or show {all, whisper, chat} windows."] = true,
    ["To see a list of available WIM slash commands type:"] = true,
    ["Display available slash commands."] = true,
    ["Reload User Interface."] = true,

    -- TabHandler.lua --
    ["Manipulating Tabs"] = true,

    -- WindowHandler.lua --
    ["Window Resized!"] = true,
    ["Creating Tab Groups"] = true,
    ["You can group two or many windows together by <Shift-Clicking> a window and dragging it on top of another."] = true,
    ["Resizing Windows"] = true,
    ["You can resize a window by holding <Shift> and dragging the bottom right corner of the window."] = true,
    ["Demo Window"] = true,
    ["<Shift-Click> to close window."] = true,
    ["Message Window Hidden"] = true,
    ["Default"] = true,
    ["%s is Away From Keyboard: %s"] = true,
    ["%s does not wish to be disturbed: %s"] = true,
    ["Right-Mouse Click!"] = true,
    ["There might be useful tools hidden under the message box. Right-Click to see them!"] = true,


    -- Options.lua --
    ["Display WIM's options."] = true,
    ["Resetting WIM will clear all of your settings!"] = true,
    ["A reset will reload your user interface."] = true,
    ["Reset all options to default."] = true,

    -- CoreOptions --
    ["Created By:"] = true,
    ["Special Thanks:"] = true,
    ["Welcome!"] = true,
    ["Enable WIM"] = true,
    ["Display Minimap Icon"] = true,
    ["<Right-Click> to show unread messages."] = true,
	["Display Addon Compartment Icon"] = true,
    ["Display Tutorials"] = true,
    ["Reset Tutorials"] = true,
    ["Credits"] = true,
    ["This is a long message which contains both emoticons and urls 8). WIM's home is www.WIMAddon.com."] = true,
    ["Message Formatting"] = true,
    ["Manipulate how WIM displays messages."] = true,
    ["Preview"] = true,
    ["Display Time Stamps"] = true,
    ["Display Emoticons"] = true,
    ["Display URLs as Links"] = true,
	["Indent long messages."] = true,
	["Bracket names."] = true,
    ["Window Behavior"] = true,
    ["You can control how windows behave while you are in different situations."] = true,
    ["Intercept Slash Commands"] = true,
	-- Shorter display text than the key: the full key overflowed the options
	-- panel's right edge (Window Behavior). The key stays untouched so every
	-- other locale keeps its translation.
	["Obey autofocus rules when opening frames via the menu. (autofocus if unchecked)"] = "Obey autofocus rules when opening via the menu (else autofocus).",
    ["Use the same rules for all states."] = true,
    ["Behaviors for state:"] = true,
    ["Pop-Up window when message is sent."] = true,
    ["Pop-Up window when message is received."] = true,
    ["Auto focus a window when it is shown."] = true,
    ["Keep focus on window after sending a message."] = true,
    ["Suppress messages from the default chat frame."] = true,
    ["Window Settings"] = true,
    ["Some settings may be limited by certain skins."] = true,
    ["Default Width"] = true,
    ["Default Height"] = true,
    ["Window Scale"] = true,
    ["Window Alpha"] = true,
    ["Set Window Spawn Location"] = true,
    ["Up"] = true,
    ["Down"] = true,
    ["Left"] = true,
    ["Right"] = true,
    ["Cascade overlapping windows."] = true,
    ["Ignore arrow keys in message box."] = true,
    ["Allow <ESC> to hide windows."] = true,
    ["Display Settings"] = true,
    ["Configure general window display settings."] = true,
    ["Window Skin:"] = true,
    ["Version"] = true,
    ["Color: System Messages"] = true,
    ["Color: Error Messages"] = true,
    ["Color: URL - Web Addresses"] = true,
    ["Color: History Messages Sent"] = true,
    ["Color: History Messages Received"] = true,
    ["Use colors suggested by skin."] = true,
    ["Enable window fading effects."] = true,
    ["Enable window animation effects."] = true,
    ["Display item links when hovering over them."] = true,
    ["Fonts"] = true,
    ["Configure the fonts used in WIM's message windows."] = true,
    ["Font Outline"] = true,
    ["Thin"] = true,
    ["Thick"] = true,
    ["Use font suggested by skin."] = true,
    ["Chat Font Size"] = true,
    ["Configure general display settings when dealing with whispers."] = true,
    ["Color: Messages Sent"] = true,
    ["Color: Messages Received"] = true,
    ["Use colors suggested by skin."] = true,
    ["Display user class icons and details."] = true,
    ["Requires who lookups."] = true,
    ["Display Shortcut Bar"] = true,
    ["Allow"] = true,
    ["Ignore"] = true,
    ["Block"] = true,
    ["Filtering"] = true,
    ["Filtering allows you to control which messages are handled as well as how they are handled by WIM."] = true,
    ["Enable Filtering"] = true,
    ["Protected"] = true,
    ["Action:"] = true,
    ["Occurrences:"] = true,
    ["Delete Filter"] = true,
    ["History"] = true,
    ["WIM can store conversations to be viewed at a later time."] = true,
    ["Enable History"] = true,
    ["Messages"] = true,
    ["Preview history inside message windows."] = true,
    ["Record Friends"] = true,
    ["Record Guild"] = true,
    ["Record Everyone"] = true,
    ["Record Chat"] = true,
    ["Maintenance"] = true,
    ["Allowing your history logs to grow too large will affect the game's performance, therefore it is reccomended that you use the following options."] = true,
    ["Save a maximum number of messages per person."] = true,
    ["%d |4Week:Weeks;"] = true,
    ["Automatically delete old messages."] = true,
    ["WIM-2-WIM is a feature which allows users with WIM to interact in ways that normal whispering can not."] = true,
    ["Enable WIM-2-WIM"] = true,
    ["Privacy"] = true,
    ["Restrict the data that is shared."] = true,
    ["Allow others to see me typing."] = true,
    ["Allow others to see my location."] = true,
    ["Main"] = true,
    ["General"] = true,
    ["User Level"] = true,
    ["Windows will also be hidden when frames such as the world map are shown."] = true,
    ["Sounds"] = true,
    ["Configure various sound events and how they are triggered."] = true,
    ["Play sound when a whisper is received."] = true,
	["Play special sound for friends."] = true,
	["Play special sound for battle.net friends."] = true,
    ["Play special sound for guild members."] = true,
    ["Play sound when a whisper is sent."] = true,
    ["Allow others to see my talent spec."] = true,
    ["Window Strata:"] = true,
	["Background"] = BACKGROUND,
	["Low"] = LOW,
	["Medium"] = true,
	["High"] = true,
	["Dialog"] = ENABLE_DIALOG,
	["Tooltip"] = true,
    ["Unlock from Minimap"] = true,
	["Press <Tab> to advance to next tell target."] = true,
	["Force sounds when game sound is disabled."] = true,
    ["Colorize names."] = true,
    ["Clamp window to screen."] = true,
	["Group with whisper windows."] = true,
	["Color: BNet Messages Sent"] = true,
	["Color: BNet Messages Received"] = true,

	-- TabManagement.lua --
    ["Tab Management"] = true,
    ["Automatically manage your open windows and place them into appropriate tab groups."] = true,
    ["Automatically group whispers."] = true,
    ["Place friends in their own group."] = true,
	["Place guild members in their own group."] = true,
	["Automatically group chat windows."] = true,
	["Does not apply to windows already opened."] = true,

	-- Talent Specs --
    ["Hybrid"] = true,

    -- Filters.lua --
    ["Show Alert"] = true,
    ["WIM has blocked a message from %s."] = true,
    ["View Blocked Message"] = true,
    ["Blocked Message"] = true,

    -- MinimapIcon.lua
    ["Show Unread Messages"] = true,
    ["Show All Windows"] = true,
    ["Hide All Windows"] = true,

    --Emoticons.lua
    ["Also"] = true,
    ["More"] = true,
    ["Emoticons"] = true,

    --Expose.lua
    ["Your conversations have been hidden in order to clear your screen while in combat. To disable this feature type"] = true,
    ["Expose"] = true,
    ["Expose is a Mac OS X inspired feature which enables you to quickly clear your screen of windows and then restore them back to their original position."] = true,
	["Auto hide/restore windows during combat."] = true,
	["Delay if I am typing a message."] = true,
    ["Border Size"] = true,
    ["Only while in an instance."] = true,
    ["Show Border"] = true,
    ["Animation Direction:"] = true,

    --ChatEngine.lua
    ["WIM will manage this chat type within its own message windows."] = true,
    ["Show Minimap Alerts"] = true,
    ["Never pop-up on my screen."] = true,
	["Never suppress messages."] = true,
	["Include emotes."] = true,
    ["Have WIM monitor this channel."] = true,
    ["Never Pop"] = true,
    ["Never have this window pop-up on my screen."] = true,
    ["Never Suppress"] = true,
    ["Never suppress messages from the default chat frame."] = true,
    ["Show unread message alert on minimap."] = true,
    ["No History"] = true,
    ["Do not record history for this channel."] = true,
    ["World Chat"] = true,
    ["Custom Chat"] = true,
	["Community Chat"] = true,
	["Community Chats"] = true,
    ["Chat"] = true,
    ["Play special sound for %s."] = true,
    ["Play sound when a message is received."] = true,
    ["Play sound when a message is sent."] = true,
    ["Do not play sounds for this channel."] = true,
    ["No Sound"] = true,
    ["Sensitivity"] = true,
    ["Enable WorldFrame Click Detection."] = true,

    --OffScreenTracker.lua
    ["WIM Window Off Screen"] = true,
    ["Click to reposition."] = true,

	-- Whisper Mode Warnings
	["Whisper Mode: In-line"] = true,
	["Set whispers to In-line"] = true,
	["Message suppression requires whispers to be set to 'In-line'."] = true,
	["It is recommended for whispers to be set to in-line in order to handle their behavior properly."] = true,

	-- Skins --
	["Blue"] = true,
	["Green"] = true,
	["Red"] = true,
	["Yellow"] = true,

	-- Battle.net friend consolidation (History Viewer)
	["Battle.net Friends"] = true,
	["Are you sure you want to delete ALL history saved with %s, across every realm and every character on this account?"] = true,

	-- Per-date deletion from the History Viewer filter list
	["Are you sure you want to delete the %s history with %s across every realm and character on this account?"] = true,
	["Are you sure you want to delete the %s history for %s across every character on %s?"] = true,
	["Are you sure you want to delete the %s history for %s on %s?"] = true,

    -- Modern options panel --
    ["Use modern options UI"] = true,
    ["Classic Options"] = true,
    ["Open"] = true,
    ["Open the classic WIM options window."] = true,
    ["Choose the options style: /wim style [classic|modern]."] = true,
    ["When enabled, WIM's Options entry points (minimap menu, key binding, /wim) open this panel instead of the classic WIM options window."] = true,
    ["While a modern-only skin (such as WIM Modern) is selected, this option is enforced: those skins are configured through this panel only."] = true,

    -- Modern skin styling --
    ["Modern Skin"] = true,
    ["These settings style WIM's modern-only skins (such as WIM Modern), which are built from the game's own interface art. They shape the History Viewer and the chat windows, and are available only while a modern-only skin is selected under General > Display Settings; with a classic skin active they are greyed out."] = true,
    ["Disabled while a modern-only skin (such as WIM Modern) is selected: those skins carry settings the classic window has no controls for."] = true,
    ["Frame background"] = true,
    ["Message area background"] = true,
    ["Chat history background"] = true,
    ["Selection panels background"] = true,
    ["Window frame background"] = true,
    ["None (game default)"] = true,
    ["Panels see through to the game world"] = true,
    ["Window sees through to the game world"] = true,
    ["Draws the frame background only around the panels, so a clear panel background (None or Transparent) shows the game world behind the viewer instead of the frame fill."] = true,
    ["Draws the window frame background only around the message area, so a clear message area background (None or Transparent) shows the game world behind the window."] = true,

    -- Roleplay profiles (Total RP 3 / Mary Sue Protocol) --
    ["Roleplay Profiles"] = true,
    ["Enable roleplay profile integration"] = true,
    ["Whisper windows show roleplay profile fields from Total RP 3 or any Mary Sue Protocol addon, and gain an Open RP Profile button on their shortcut bar that opens the partner's profile in the installed viewer."] = true,
    ["Open RP Profile"] = true,
    ["Displayed profile fields"] = true,
    ["Whisper windows show the selected fields from the partner's Total RP 3 or Mary Sue Protocol profile. Fields left unselected -- or without profile data -- keep the standard display."] = true,
    ["First Name"] = true,
    ["Last Name"] = true,
    ["Title"] = true,
    ["Full Title"] = true,
    ["Race"] = true,
    ["Class"] = true,
    ["Portrait"] = true,
    ["Name & Class Color"] = true,
    ["The profile's first name, shown as the window's name text."] = true,
    ["The profile's last name, shown as the window's name text."] = true,
    ["The short title, shown on the window's details line."] = true,
    ["The long title, shown on the window's details line and portrait tooltip."] = true,
    ["The custom race, replacing the character's race on the details line."] = true,
    ["The custom class, replacing the character's class on the details line."] = true,
    ["The profile's icon, replacing the class icon."] = true,
    ["The profile's custom color, applied to the window's name text and to the class on the details line."] = true,
    ["Apply filter to character menus"] = true,

    -- History Viewer filters --
    ["No Filter"] = true,
    ["Relative Dates"] = true,
    ["%d or more"] = true,
    ["Fewer than %d"] = true,
    ["Results Filtered"] = true,
    ["-- Results Filtered --"] = true,
    ["Results are hidden by the active filter. Click to open the Filters menu."] = true,
    ["Click to change how history is filtered."] = true,
    ["Click to open the Filters menu."] = true,
    ["Clicking the %s button on the message window will show that user's history in WIM's History Viewer."] = true,

    -- Message input & formatting --
    ["Wrap the message being typed"] = true,
    ["Limit wrapped lines"] = true,
    ["Visible input lines"] = true,
    ["Caps how far the input field grows; past the limit the message scrolls inside it."] = true,
    ["The most lines the input field grows to before the message scrolls inside it."] = true,
    ["The input field wraps long messages onto multiple lines, growing downward with the message instead of scrolling it on one line."] = true,
    ["Timestamp Format"] = true,
    ["Bracket Style"] = true,
    ["Colors"] = true,
    ["Sound"] = true,
    ["AaBbYyZz 123"] = true,

    -- Chat type options --
    ["Chat Windows"] = true,
    ["Monitor"] = true,
    ["Record"] = true,
    ["Minimap Alerts"] = true,

    -- Help, bug reports & links --
    ["Found a bug?"] = true,
    ["Report a Bug"] = true,
    ["Reports are welcome! Click below and follow the instructions in the bug report template."] = true,
    ["Visit us on GitHub"] = true,
    ["Click to copy the link."] = true,
    ["Press Ctrl+C to copy the link, then open it in your browser."] = true,

    -- Debugging & development slash commands --
    ["Clear the captured debug log."] = true,
    ["Set debugging level: /wim debug [0|1|2]. 2 adds verbose chat event tracing."] = true,
    ["Snapshot the next modern context menu while it is open."] = true,
    ["Snapshot UI widget state for skin development: /wim snap all | <Frame.Dot.Path> (bare /wim snap lists the arguments)."] = true,

    -- Tutorials & notices --
    ["WIM is currently running. To access WIM's wide array of options type:"] = true,
    ["WIM's message window has been hidden to WIM's Minimap Icon. If you want to end a conversation, you may do so by <Shift-Clicking> the close button."] = true,
    ["If you want all windows to be this size, you can set the default window size within WIM's options."] = true,
    ["You can <Shift-Click> a tab and drag it out into it's own window."] = true,
    ["You received a whisper which was hidden due to your current activity. You can change how whispers behave in WIM's options by typing"] = true,
    ["Sets the game's Social > Whisper Mode setting to In-line. Without it, suppressed whispers would vanish into a popout chat tab."] = true,

    -- Community channel maintenance --
    ["Toggle the experimental community channel re-add repair (mutates chat window channels)."] = true,
    ["Toggle whether WIM focuses community streams at login."] = true,

    -- Misc --
    ["Age"] = true,
    ["Users in %s"] = true,

    -- History Viewer filter modes --
    ["Sent by Me"] = true,
    ["Sent by Them"] = true,
    ["Active Days"] = true,
    ["Last 1 Day"] = true,
    ["Last 7 Days"] = true,
    ["Last 30 Days"] = true,
    ["Last 90 Days"] = true,


    -- Chrome background names --
    ["None (fully clear)"] = true,
    ["Transparent"] = true,
    ["Rock"] = true,
    ["Marble"] = true,
    ["Dark Marble"] = true,
    ["Bank"] = true,
    ["Guild Vault"] = true,
    ["Dark Sandstone"] = true,
    ["Parchment (Tileable)"] = true,
    ["Quest Parchment"] = true,
    ["Raid Frame"] = true,
    ["Destiny"] = true,
    ["Stationery (Auction)"] = true,
    ["Stationery (Illustrated)"] = true,
    ["Stationery (Orgrimmar)"] = true,
    ["Stationery (Thunder Bluff)"] = true,
    ["Stationery (Undercity)"] = true,
    ["Stationery (Plain)"] = true,
    ["World Map 1"] = true,
    ["World Map 2"] = true,
    ["Achievement Stats"] = true,
    ["Adventure Map Parchment"] = true,
    ["Collections"] = true,
    ["Frame: Alliance"] = true,
    ["Frame: Horde"] = true,
    ["Frame: Neutral"] = true,
    ["Frame: Marine"] = true,
    ["Frame: Mechagon"] = true,
    ["Frame: Kyrian"] = true,
    ["Frame: Necrolord"] = true,
    ["Frame: Night Fae"] = true,
    ["Frame: Venthyr"] = true,
    ["Frame: Oribos"] = true,
    ["Frame: Dragonflight"] = true,
    ["Frame: The War Within"] = true,
    ["Class Hall"] = true,
    ["Class Hall (Internal)"] = true,
    ["Garrison Landing Page"] = true,
    ["Garrison Mission"] = true,
    ["Ship Mission Parchment"] = true,
    ["Garrison UI"] = true,
    ["Garrison UI 2"] = true,
    ["Credits: Classic"] = true,
    ["Credits: Burning Crusade"] = true,
    ["Credits: Wrath"] = true,
    ["Credits: Cataclysm"] = true,
    ["Credits: Mists of Pandaria"] = true,
    ["Credits: Warlords"] = true,
    ["Credits: Legion"] = true,
    ["Credits: Battle for Azeroth"] = true,


    -- Skin & options style notices --
    ["WIM: the selected skin (%s) is configured through the modern options UI; the classic window is unavailable while it is active."] = true,
    ["WIM: the selected skin (%s) requires the modern options UI; switch to another skin first."] = true,
    ["WIM options style: Modern (native Options > AddOns)."] = true,
    ["WIM options style: Classic (WIM window)."] = true,


    -- Slash command feedback --
    ["WIM: community chat settings unavailable."] = true,
    ["WIM community stream auto-focus ON. Takes effect at next login."] = true,
    ["WIM community stream auto-focus OFF - the client may refuse sends to community channels. Takes effect at next login."] = true,
    ["WIM channel re-add repair ON (experimental). On logins where the community stream is focused late, WIM removes and re-adds community channels to ChatFrame1 about 8s after login. If a re-add fails the channel must be restored from the chat settings UI."] = true,
    ["WIM: attempting a repair now (see /wim debug output)."] = true,
    ["WIM channel re-add repair OFF. No further attempts this session."] = true,
    ["Usage: /wim style [classic|modern]"] = true,
    ["WIM: the modern options UI is not available on this client."] = true,
    ["WIM: queued options open canceled."] = true,
});
