--[[
    Language Localization: esES & esMX
    Translated by: Woopy#1685 (NA)
]]

local translations = {
    ["WIM (WoW Instant Messenger)"] = "WIM (WoW Instant Messenger)",
    ["_Description"] = "WIM es un addon que aporta una sensación familiar a la comunicación a través del chat en World of Warcraft. En esta pantalla podrá personalizar WIM para adaptarlo a tus necesidades.",

    ["_DemoText"] = "Esta es una ventana de demostración y no es completamente funcional. Coloca esta ventana en el lugar donde deseas que aparezcan todas las demás ventanas. Cuando termines, puedes cerrar esta ventana y su configuración se guardará.",

    ["_DateFormat"] = "%d/%m/%Y",

    ["Yes"] = "Sí",
    ["No"] = "No",
    ["None"] = "Ninguno",
    ["Cancel"] = "Cancelar",
    ["Unknown"] = "Desconocido",
    ["Click to update..."] = "Haz clic para actualizar...",
    ["Usage"] = "Uso",

    ["state_resting"] = "Ausente",
    ["state_combat"] = "Combate",
    ["state_pvp"] = "JcJ",
    ["state_arena"] = "Arena",
    ["state_party"] = "Grupo de mazmorra",
    ["state_raid"] = "Grupo de banda",
    ["state_other"] = "Normal (otro)",

    ["Options"] = "Opciones",

    ["Up"] = "Arriba",
    ["Down"] = "Abajo",
    ["Left"] = "Izquierda",
    ["Right"] = "Derecha",
    ["Ignore"] = "Ignorar",
    ["Block"] = "Bloquear",
    ["Enable WIM"] = "Activar WIM",

    ["Enable"] = "Activar",
    ["Disable"] = "Desactivar",
    ["Enable window fading effects."] = "Activar efectos de desvanecimiento de ventana",

    ["General"] = "General",
    ["History"] = "Historial",
    ["Filters"] = "Filtros",

    ["Include sent messages in /REPLY."] = "Incluir mensajes enviados en /r",

    ["Sort tabs by:"] = "Ordenar pestañas por:",
	["Window Created"] = "Ventana creada",
	["Last Activity"] = "Última actividad",
    ["Alphabetical"] = "Alfabético",

    -- Class Names --
    ["Druid"] = LOCALIZED_CLASS_NAMES_MALE.DRUID,
    ["Hunter"] = LOCALIZED_CLASS_NAMES_MALE.HUNTER,
    ["Mage"] = LOCALIZED_CLASS_NAMES_MALE.MAGE,
    ["Paladin"] = LOCALIZED_CLASS_NAMES_MALE.PALADIN,
    ["Priest"] = LOCALIZED_CLASS_NAMES_MALE.PRIEST,
    ["Rogue"] = LOCALIZED_CLASS_NAMES_MALE.ROGUE,
    ["Shaman"] = LOCALIZED_CLASS_NAMES_MALE.SHAMAN,
    ["Warlock"] = LOCALIZED_CLASS_NAMES_MALE.WARLOCK,
    ["Warrior"] = LOCALIZED_CLASS_NAMES_MALE.WARRIOR,
    ["Death Knight"] = LOCALIZED_CLASS_NAMES_MALE.DEATHKNIGHT,
    ["Monk"] = LOCALIZED_CLASS_NAMES_MALE.MONK,
    ["Demon Hunter"] = LOCALIZED_CLASS_NAMES_MALE.DEMONHUNTER,
	["Evoker"] = LOCALIZED_CLASS_NAMES_MALE.EVOKER,

    -- Female Class Names --
    ["DruidF"] = LOCALIZED_CLASS_NAMES_FEMALE.DRUID,
    ["HunterF"] = LOCALIZED_CLASS_NAMES_FEMALE.HUNTER,
    ["MageF"] = LOCALIZED_CLASS_NAMES_FEMALE.MAGE,
    ["PaladinF"] = LOCALIZED_CLASS_NAMES_FEMALE.PALADIN,
    ["PriestF"] = LOCALIZED_CLASS_NAMES_FEMALE.PRIEST,
    ["RogueF"] = LOCALIZED_CLASS_NAMES_FEMALE.ROGUE,
    ["ShamanF"] = LOCALIZED_CLASS_NAMES_FEMALE.SHAMAN,
    ["WarlockF"] = LOCALIZED_CLASS_NAMES_FEMALE.WARLOCK,
    ["WarriorF"] = LOCALIZED_CLASS_NAMES_FEMALE.WARRIOR,
    ["Death KnightF"] = LOCALIZED_CLASS_NAMES_FEMALE.DEATHKNIGHT,
    ["MonkF"] = LOCALIZED_CLASS_NAMES_FEMALE.MONK,
    ["Demon HunterF"] = LOCALIZED_CLASS_NAMES_FEMALE.DEMONHUNTER,
	["EvokerF"] = LOCALIZED_CLASS_NAMES_FEMALE.EVOKER,

    ["Game Master"] = "Maestro de juego",

    -- WIM.lua --
    ["Toggle WIM 'On' and 'Off'."] = "Alternar WIM 'Activado' y 'Desactivado'.",
    ["Toggle Debugging Mode 'On' and 'Off'."] = "Activar y desactivar el modo de depuración.",

    -- Filters.lua --
    ["Whispers Sent by Addons"] = "Susurros enviados por addons",
    ["WhisperSelect Part 1"] = "Selección de susurros parte 1",
    ["Example Spam Blocker"] = "Ejemplo del bloqueador de spam",
    ["WhisperSelect Part 2"] = "Selección de susurros parte 2",
    ["Filter Name"] = "Nombre de filtro",
    ["Filter By"] = "Filtrar por",
    ["Pattern"] = "Patrón",
    ["User Type"] = "Tipo de jugador",
    ["Level"] = "Nivel",
    ["Friends"] = "Amigos",
    ["Guild Members"] = "Miembros de hermandad",
    ["Party Members"] = "Miembros de grupo",
    ["Raid Members"] = "Miembros de banda",
    ["Cross-Realm"] = "Interreinos",
    ["Everyone"] = "Todos",
    ["User must be at least level:"] = "El jugador debe tener al menos un nivel:",
    ["Apply to messages received."] = "Aplicar a los mensajes recibidos.",
    ["Apply to messages sent."] = "Aplicar a los mensajes enviados.",
    ["Apply to:"] = "Aplicar a:",
    ["All Classes"] = "Todas las clases",
    ["Action to Perform:"] = "Acción a realizar:",
    ["Allow"] = "Permitir",
    ["Ignore"] = "Ignorar",
    ["Blocked"] = "Bloqueado",
    ["Save"] = "Guardar",
    ["Cancel"] = "Cancelar",
    ["Edit Filter"] = "Editar filtro",
    ["Add Filter"] = "Añadir filtro",

    -- History.lua --
    ["WIM History Button"] = "Botón de historial de WIM",
    ["Click to view message history."] = "Haz clic para ver el historial de mensajes.",
    ["WIM pruned %d |4message:messages; from your history."] = "WIM eliminó %d |4mensaje:mensajes; de tu historial.",
    ["History Viewer"] = "Visor de historial",
    ["Filters"] = "Filtros",
    ["Are you sure you want to delete all history saved for %s on %s?"] = "¿Estás seguro de que quieres eliminar todo el historial guardado para %s en %s?",
    ["Search resulted in %d |4message:messages;."] = "La búsqueda resultó en %d |4mensaje:mensajes;.",
    ["No results found!"] = "¡No se han encontrado resultados!",
    ["Search"] = "Buscar",
    ["Show All"] = "Mostrar todos",
    ["Loading History"] = "Cargando historial",
    ["Chat View"] = "Vista de chat",
    ["Text View"] = "Vista de texto",
    ["BBCode"] = "BBCode",
    ["WIM History Viewer can be accessed any time by typing:"] = "Se puede acceder al visor de historial de WIM en cualquier momento escribiendo:",
    ["WIM History Viewer"] = "Visor de historial de WIM",
    ["Display history viewer."] = "Mostrar visor de historial",

    -- ldb.lua --
    ["No New Messages"] = "No hay mensajes nuevos",

    -- Menu.lua --
    ["Whispers"] = "Susurros",
    ["Chat"] = "Chat",

    -- Negotiate.lua --
    ["WIM Update Available!"] = "¡Actualización WIM disponible!",

    -- ShortcutBar.lua --
    ["Player Location"] = "Zona del jugador",
    ["Unknown"] = "Desconocido",
    ["Click to update..."] = "Haz clic para actualizar...",
    ["Invite to Party"] = "Invitar al grupo",
    ["Invite to Guild"] = "Invitar a la hermandad",
    ["Add Friend"] = "Añadir amigo",
    ["Ignore Player"] = "Ignorar jugador",
    ["Are you sure you want to\nignore %s?"] = "¿Estás seguro de que quieres\nignorar a %s?",
    ["Right-Click for profile links..."] = "Haz clic derecho para enlaces de perfil...",
    ["Profile Links"] = "Enlaces de perfil",
    ["Location"] = "Zona",
    ["Game"] = "Juego",
    ["Realm"] = "Reino",
    ["Character"] = "Personaje",
	["Copy Name"] = "Copiar nombre",

    -- Tutorials.lua --
    ["View Updates"] = "Ver actualizaciones",

    -- WhisperEngine.lua --
    ["Whisper Received!"] = "¡Susurro recibido!",
    ["Recently Sent Messages"] = "Mensajes enviados recientemente",
    ["Users in %s"] = "Usuarios en %s",

    -- Clear.lua --
    ["You are about to clear all of WIM's history!"] = "¡Estás a punto de borrar toda la historia de WIM!",
    ["This action will reload your user interface."] = "Esta acción volverá a cargar tu interfaz de usuario.",
    ["Do you want to continue?"] = "¿Quieres continuar?",
    ["You are about to restore WIM's filters to it's default settings!"] = "¡Estás a punto de restaurar los filtros de WIM a su configuración predeterminada!",
    ["Usage"] = "Uso",
    ["Clear various WIM data."] = "Borrar varios datos WIM.",

    -- SlashHandler.lua --
    ["WIM Slash Commands"] = "Comandos de barra diagonal WIM",
    ["Hide or show {all, whisper, chat} windows."] = "Ocultar o mostrar ventanas {todas, de susurro, de chat}.",
    ["To see a list of available WIM slash commands type:"] = "Para ver una lista de comandos de barra diagonal WIM, escribe:",
    ["Display available slash commands."] = "Mostrar los comandos de barra diagonal disponibles.",
    ["Reload User Interface."] = "Recargar la interfaz del usuario",

    -- TabHandler.lua --
    ["Manipulating Tabs"] = "Manipular pestañas",

    -- WindowHandler.lua --
    ["Window Resized!"] = "¡Ventana redimensionada!",
    ["Creating Tab Groups"] = "Crear grupos de pestañas",
    ["You can group two or many windows together by <Shift-Clicking> a window and dragging it on top of another."] = "Puedes agrupar dos o muchas ventanas juntas por <Mayús-clic> en una ventana y arrastrándola encima de otra.",
    ["Resizing Windows"] = "Redimensionar Ventanas",
    ["You can resize a window by holding <Shift> and dragging the bottom right corner of the window."] = "Puedes redimensionar una ventana manteniendo presionado <Mayús> y arrastrando la esquina inferior derecha de la ventana.",
    ["Demo Window"] = "Ventana de demonstración",
    ["<Shift-Click> to close window."] = "<Mayús-clic> para cerrar la ventana.",
    ["Message Window Hidden"] = "Ventana de mensaje oculta",
    ["Default"] = "Predeterminado",
    ["%s is Away From Keyboard: %s"] = "%s está ausente: %s",
    ["%s does not wish to be disturbed: %s"] = "%s no desea ser molestrado: %s",
    ["Right-Mouse Click!"] = "¡Haz clic derecho!",
    ["There might be useful tools hidden under the message box. Right-Click to see them!"] = "Se puede haber herramientas útiles ocultas debajo del cuadro de mensaje. ¡Haz clic derecho para verlas!",

    -- Options.lua --
    ["Display WIM's options."] = "Mostrar opciones de WIM",
    ["Resetting WIM will clear all of your settings!"] = "¡Al restablecer WIM se borrarán todas las configuraciones!",
    ["A reset will reload your user interface."] = "Un restablecimiento recargará tu interfaz de usuario.",
    ["Reset all options to default."] = "Restablecer todas las opciones a las predeterminadas.",

    -- CoreOptions --
    ["Created By:"] = "Creado por:",
    ["Special Thanks:"] = "Agradecimiento especial:",
    ["Welcome!"] = "¡Bienvenido!",
    ["Enable WIM"] = "Activar WIM",
    ["Display Minimap Icon"] = "Mostrar icono del minimapa",
    ["<Right-Click> to show unread messages."] = "<Haz clic derecho> para mostrar mensajes no leídos",
	["Display Addon Compartment Icon"] = "Mostrar icono del compartimento de addons",
    ["Display Tutorials"] = "Mostrar tutoriales",
    ["Reset Tutorials"] = "Restablecer tutoriales",
    ["Credits"] = "Créditos",
    ["This is a long message which contains both emoticons and urls 8). WIM's home is www.WIMAddon.com."] = "Este es un mensaje largo que contiene emoticonos y urls 8). La página de WIM es www.WIMAddon.com.",
    ["Message Formatting"] = "Formato de mensaje",
    ["Manipulate how WIM displays messages."] = "Manipula cómo WIM muestra los mensajes.",
    ["Preview"] = "Vista previa",
    ["Display Time Stamps"] = "Mostrar marca de tiempo",
    ["Display Emoticons"] = "Mostrar emoticonos",
    ["Display URLs as Links"] = "Mostrar URLs como enlaces",
    ["Indent long messages."] = "Sangrar mensajes largos",
    ["Bracket names."] = "Nombres en paréntesis",
    ["Window Behavior"] = "Comportamiento",
    ["You can control how windows behave while you are in different situations."] = "Puedes controlar cómo se comportan las ventanas mientras estás en diferentes situaciones.",
    ["Intercept Slash Commands"] = "Interceptar comandos de barra diagonal",
    ["Obey autofocus rules when opening frames via the menu. (autofocus if unchecked)"] = "Obedecer las reglas de enfoque automático al abrir marcos",
    ["Use the same rules for all states."] = "Usar las mismas reglas para todos los estados",
    ["Behaviors for state:"] = "Comportamientos de estado:",
    ["Pop-Up window when message is sent."] = "Ventana emergente cuando se envía un mensaje",
    ["Pop-Up window when message is received."] = "Ventana emergente cuando se recibe el mensaje",
    ["Auto focus a window when it is shown."] = "Autoenfocar una ventana cuando se muestra",
    ["Keep focus on window after sending a message."] = "Mantener el foco en la ventana después de enviar un mensaje",
    ["Suppress messages from the default chat frame."] = "Suprimir los mensajes del marco de chat predeterminado",
    ["Window Settings"] = "Ventana",
    ["Some settings may be limited by certain skins."] = "Algunas configuraciones pueden estar limitadas por ciertos estilos.",
    ["Default Width"] = "Anchura predeterminada",
    ["Default Height"] = "Altura predeterminada",
    ["Window Scale"] = "Escala de la ventana",
    ["Window Alpha"] = "Transparencia de la ventana",
    ["Set Window Spawn Location"] = "Establecer ubicación de generación de ventana",
    ["Up"] = "Arriba",
    ["Down"] = "Abajo",
    ["Left"] = "Izquierdo",
    ["Right"] = "Derecho",
    ["Cascade overlapping windows."] = "Ventanas superpuestas en cascada",
    ["Ignore arrow keys in message box."] = "Ignorar las teclas de flecha en el cuadro de mensaje",
    ["Allow <ESC> to hide windows."] = "Permitir que <ESC> oculte ventanas",
    ["Display Settings"] = "Visualización",
    ["Configure general window display settings."] = "Configura ajustes generales de visualización de ventana.",
    ["Window Skin:"] = "Estilo de ventana:",
    ["Version"] = "Versión",
    ["Color: System Messages"] = "Color: Mensajes de sistema",
    ["Color: Error Messages"] = "Color: Mensajes de error",
    ["Color: URL - Web Addresses"] = "Color: URL - Dirección de web",
    ["Color: History Messages Sent"] = "Color: Mensajes de historial enviados",
    ["Color: History Messages Received"] = "Color: Mensajes de historial recibidos",
    ["Enable window fading effects."] = "Activar efectos de desvanecimiento de ventana",
    ["Enable window animation effects."] = "Activar efectos de animación de ventana",
    ["Display item links when hovering over them."] = "Mostrar enlaces de objetos al pasar el cursor sobre ellos",
    ["Fonts"] = "Fuentes",
    ["Configure the fonts used in WIM's message windows."] = "Configura las fuentes utilizadas en las ventanas de mensajes de WIM.",
    ["Font Outline"] = "Contorno de fuente",
    ["Thin"] = "Delgado",
    ["Thick"] = "Grueso",
    ["Use font suggested by skin."] = "Usar fuente sugerida por el estilo",
    ["Chat Font Size"] = "Tamaño de fuente del chat",
    ["Configure general display settings when dealing with whispers."] = "Configura ajustes generales de pantalla cuando se trata de susurros.",
    ["Color: Messages Sent"] = "Color: Mensajes enviados",
    ["Color: Messages Received"] = "Color: Mensajes recibidos",
    ["Color: BNet Messages Sent"] = "Color: Mensajes de BNet enviados",
    ["Color: BNet Messages Received"] = "Color: Mensajes de BNet recibidos",
    ["Use colors suggested by skin."] = "Usar colores sugeridos por el estilo",
    ["Display user class icons and details."] = "Mostrar iconos de clase de usuario y detalles",
    ["Requires who lookups."] = "Requiere búsqueda de quién",
    ["Display Shortcut Bar"] = "Mostrar barra de acceso directo",
    ["Allow"] = "Permitir",
    ["Ignore"] = "Ignorar",
    ["Block"] = "Bloquear",
    ["Filtering"] = "Filtro",
    ["Filtering allows you to control which messages are handled as well as how they are handled by WIM."] = "El filtro te permite controlar qué mensajes se manejan y cómo WIM los maneja.",
    ["Enable Filtering"] = "Activar filtro",
    ["Protected"] = "Protegido",
    ["Action:"] = "Acción:",
    ["Occurrences:"] = "Ocurrencias:",
    ["Delete Filter"] = "Eliminar filtro",
    ["History"] = "Historial",
    ["WIM can store conversations to be viewed at a later time."] = "WIM puede archivar conversaciones para verlas más adelante.",
    ["Enable History"] = "Activar historial",
    ["Messages"] = "Mensajes",
    ["Preview history inside message windows."] = "Previsualización del historial",
    ["Record Friends"] = "Registrar amigos",
    ["Record Guild"] = "Registrar hermandad",
    ["Record Everyone"] = "Registrar todos",
    ["Record Chat"] = "Registrar chat",
    ["Maintenance"] = "Mantenimiento",
    ["Allowing your history logs to grow too large will affect the game's performance, therefore it is reccomended that you use the following options."] = "Permite que tus registros de historial crezcan demasiado afectará el rendimiento del juego, por lo tanto, se recomienda que uses las siguientes opciones.",
    ["Save a maximum number of messages per person."] = "Guardar un número máximo de mensajes por persona",
    ["%d |4Week:Weeks;"] = "%d |4Semana:Semanas;",
    ["Automatically delete old messages."] = "Eliminar automáticamente los mensajes antiguos",
    ["WIM-2-WIM is a feature which allows users with WIM to interact in ways that normal whispering can not."] = "WIM-2-WIM es una característica que permite a los usuarios con WIM interactuar de formas que los susurros normales no pueden.",
    ["Enable WIM-2-WIM"] = "Activar WIM-2-WIM",
    ["Privacy"] = "Privacidad",
    ["Restrict the data that is shared."] = "Restringir los datos que se comparten.",
    ["Allow others to see me typing."] = "Permitir que otros me vean escribiendo.",
    ["Allow others to see my location."] = "Permitir a otros ver mi ubicación.",
    ["Main"] = "Principal",
    ["General"] = "General",
    ["User Level"] = "Nivel del jugador",
    ["Windows will also be hidden when frames such as the world map are shown."] = "Ventanas también estará oculto cuando se muestren marcos como el mapa del mundo.",
    ["Sounds"] = "Sonidos",
    ["Configure various sound events and how they are triggered."] = "Configura varios eventos de sonido y cómo se activan.",
    ["Play sound when a whisper is received."] = "Reproducir sonido cuando se recibe un susurro",
    ["Play special sound for friends."] = "Reproducir un sonido especial para amigos",
    ["Play special sound for battle.net friends."] = "Reproducir un sonido especial para amigos de battle.net",
    ["Play special sound for guild members."] = "Reproducir un sonido especial para miembros de la hermandad",
    ["Play sound when a whisper is sent."] = "Reproducir sonido cuando se envía un susurro",
    ["Allow others to see my talent spec."] = "Permitir que otros vean mi especialización de talento",
    ["Window Strata:"] = "Estratos de ventana:",
	["Background"] = BACKGROUND,
	["Low"] = LOW,
	["Medium"] = "Medio",
	["High"] = "Alto",
	["Dialog"] = ENABLE_DIALOG,
	["Tooltip"] = true,
    ["Unlock from Minimap"] = "Desbloquear del minimapa",
    ["Press <Tab> to advance to next tell target."] = "Presionar <Tab> para avanzar al siguiente objetivo",
    ["Force sounds when game sound is disabled."] = "Forzar sonidos cuando el sonido del juego está desactivado",
    ["Colorize names."] = "Colorear nombres",
    ["Clamp window to screen."] = "Anclar la ventana a la pantalla",
    ["Group with whisper windows."] = "Agrupar con ventanas de susurros",

    -- TabManagement.lua --
    ["Tab Management"] = "Gestión de pestañas",
    ["Automatically manage your open windows and place them into appropriate tab groups."] = "Gestiona automáticamente tus ventanas abiertas y colóquelas en grupos de pestañas apropiados.",
    ["Automatically group whispers."] = "Agrupar automáticamente los susurros",
    ["Automatically group chat windows."] = "Agrupar automáticamente las ventanas de chat",
    ["Place friends in their own group."] = "Colocar amigos en su propio grupo",
    ["Place guild members in their own group."] = "Colocar a los miembros de la hermandad en su propio grupo",
    ["Does not apply to windows already opened."] = "No se aplica a las ventanas ya abiertas.",

    -- Talent Specs --
    ["Hybrid"] = "Híbrido",

    -- Filters.lua --
    ["Show Alert"] = "Mostrar alerta",
    ["WIM has blocked a message from %s."] = "WIM ha bloqueado un mensaje de %s.",
    ["View Blocked Message"] = "Ver mensaje bloqueado",
    ["Blocked Message"] = "Mensaje bloqueado",

    -- MinimapIcon.lua
    ["Show Unread Messages"] = "Mostrar mensajes no leídos",
    ["Show All Windows"] = "Mostrar todas las ventanas",
    ["Hide All Windows"] = "Ocultar todas las ventanas",

    --Emoticons.lua
    ["Also"] = "También",
    ["More"] = "Más",
    ["Emoticons"] = "Emoticones",

    --Expose.lua
    ["Your conversations have been hidden in order to clear your screen while in combat. To disable this feature type"] = "Tus conversaciones se han ocultado para limpiar tu pantalla mientras estás en combate. Para desactivar esto escribe",
    ["Expose"] = "Expose",
    ["Expose is a Mac OS X inspired feature which enables you to quickly clear your screen of windows and then restore them back to their original position."] = "Expose es una característica inspirada en Mac OS X que te permite borrar rápidamente la pantalla de ventanas y luego restaurarlas a su posición original.",
    ["Auto hide/restore windows during combat."] = "Ocultar/restaurar ventanas automáticamente durante el combate",
    ["Delay if I am typing a message."] = "Retrasar si estoy escribiendo un mensaje",
    ["Border Size"] = "Tamaño del borde",
    ["Only while in an instance."] = "Solo en una estancia",
    ["Show Border"] = "Mostrar borde",
    ["Animation Direction:"] = "Dirección de animación:",

    --ChatEngine.lua
    ["WIM will manage this chat type within its own message windows."] = "WIM gestionará este tipo de chat dentro de sus propias ventanas de mensajes.",
    ["Show Minimap Alerts"] = "Mostrar alertas de minimapa",
    ["Never pop-up on my screen."] = "Nunca aparecer en mi pantalla",
    ["Never suppress messages."] = "Nunca suprimir mensajes",
    ["Include emotes."] = "Incluir emociones",
    ["Have WIM monitor this channel."] = "Haz que WIM supervise este canal.",
    ["Never Pop"] = "Nunca aparecer",
    ["Never have this window pop-up on my screen."] = "Nunca mostrar esta ventana emergente en mi pantalla.",
    ["Never Suppress"] = "Nunca suprimir",
    ["Never suppress messages from the default chat frame."] = "Nunca suprimir mensajes del marco de chat predeterminado.",
    ["Show unread message alert on minimap."] = "Mostrar alerta de mensaje no leído en el minimapa.",
    ["No History"] = "Sin historial",
    ["Do not record history for this channel."] = "No grabar el historial de este canal.",
    ["World Chat"] = "Chat del mundo",
    ["Custom Chat"] = "Chat personalizado",
    ["Community Chat"] = "Chat de comunidad",
    ["Community Chats"] = "Chats de comunidad",
    ["Chat"] = "Chat",
    ["Play special sound for %s."] = "Reproducir sonido especial para %s",
    ["Play sound when a message is received."] = "Reproducir sonido cuando se recibe un mensaje",
    ["Play sound when a message is sent."] = "Reproducir sonido cuando se envía un mensaje",
    ["Do not play sounds for this channel."] = "No reproducir sonidos para este canal.",
    ["No Sound"] = "Sin sonido",
    ["Sensitivity"] = "Sensibilidad",
    ["Enable WorldFrame Click Detection."] = "Activar detección de clic WorldFrame",

    --OffScreenTracker.lua
    ["WIM Window Off Screen"] = "Ventana WIM fuera de pantalla",
    ["Click to reposition."] = "Haz clic para reposicionar.",

	-- Whisper Mode Warnings
    ["Whisper Mode: In-line"] = "Modo de susurro: en línea",
	["Set whispers to In-line"] = "Establecer susurros en línea",
	["Message suppression requires whispers to be set to 'In-line'."] = "La supresión de mensajes requiere que los susurros estén configurados en 'en línea'.",
	["It is recommended for whispers to be set to in-line in order to handle their behavior properly."] = "Se recomienda configurar los susurros en línea para manejar su comportamiento correctamente.",

	-- Skins --
	["Blue"] = "Azul",
	["Green"] = "Verde",
	["Red"] = "Rojo",
	["Yellow"] = "Amarillo",

	-- Battle.net friend consolidation (History Viewer)
	["Battle.net Friends"] = "Amigos de Battle.net",
	["Are you sure you want to delete ALL history saved with %s, across every realm and every character on this account?"] = "¿Estás seguro de que quieres eliminar TODO el historial guardado con %s, en todos los reinos y todos los personajes de esta cuenta?",

	-- Per-date deletion from the History Viewer filter list
	["Are you sure you want to delete the %s history with %s across every realm and character on this account?"] = "¿Estás seguro de que quieres eliminar el historial del %s con %s en todos los reinos y personajes de esta cuenta?",
	["Are you sure you want to delete the %s history for %s across every character on %s?"] = "¿Estás seguro de que quieres eliminar el historial del %s de %s en todos los personajes de %s?",
	["Are you sure you want to delete the %s history for %s on %s?"] = "¿Estás seguro de que quieres eliminar el historial del %s de %s en %s?",


	-- Modern options panel --
	["Use modern options UI"] = "Usar la interfaz de opciones moderna",
	["Classic Options"] = "Opciones clásicas",
	["Open"] = "Abrir",
	["Open the classic WIM options window."] = "Abre la ventana de opciones clásica de WIM.",
	["Choose the options style: /wim style [classic|modern]."] = "Elige el estilo de opciones: /wim style [classic|modern].",
	["When enabled, WIM's Options entry points (minimap menu, key binding, /wim) open this panel instead of the classic WIM options window."] = "Cuando está activada, los puntos de acceso a las opciones de WIM (menú del minimapa, tecla asignada, /wim) abren este panel en lugar de la ventana de opciones clásica de WIM.",
	["While a modern-only skin (such as WIM Modern) is selected, this option is enforced: those skins are configured through this panel only."] = "Con un estilo exclusivamente moderno seleccionado (como WIM Modern), esta opción se aplica obligatoriamente: esos estilos se configuran solo desde este panel.",

	-- Modern skin styling --
	["Modern Skin"] = "Estilo moderno",
	["These settings style WIM's modern-only skins (such as WIM Modern), which are built from the game's own interface art. They shape the History Viewer and the chat windows, and are available only while a modern-only skin is selected under General > Display Settings; with a classic skin active they are greyed out."] = "Estos ajustes dan estilo a los estilos exclusivamente modernos de WIM (como WIM Modern), creados con el arte de interfaz del propio juego. Dan forma al visor de historial y a las ventanas de chat, y solo están disponibles mientras haya un estilo exclusivamente moderno seleccionado en General > Configuración de pantalla; con un estilo clásico activo aparecen en gris.",
	["Disabled while a modern-only skin (such as WIM Modern) is selected: those skins carry settings the classic window has no controls for."] = "Desactivado mientras haya un estilo exclusivamente moderno (como WIM Modern) seleccionado: esos estilos incluyen ajustes para los que la ventana clásica no tiene controles.",
	["Frame background"] = "Fondo del marco",
	["Message area background"] = "Fondo del área de mensajes",
	["Chat history background"] = "Fondo del historial de chat",
	["Selection panels background"] = "Fondo de los paneles de selección",
	["Window frame background"] = "Fondo del marco de la ventana",
	["None (game default)"] = "Ninguno (predeterminado del juego)",
	["Panels see through to the game world"] = "Los paneles dejan ver el mundo del juego",
	["Window sees through to the game world"] = "La ventana deja ver el mundo del juego",
	["Draws the frame background only around the panels, so a clear panel background (None or Transparent) shows the game world behind the viewer instead of the frame fill."] = "Dibuja el fondo del marco solo alrededor de los paneles, de modo que un fondo de panel limpio (Ninguno o Transparente) deja ver el mundo del juego detrás del visor en lugar del relleno del marco.",
	["Draws the window frame background only around the message area, so a clear message area background (None or Transparent) shows the game world behind the window."] = "Dibuja el fondo del marco de la ventana solo alrededor del área de mensajes, de modo que un fondo de área de mensajes limpio (Ninguno o Transparente) deja ver el mundo del juego detrás de la ventana.",

	-- Roleplay profiles (Total RP 3 / Mary Sue Protocol) --
	["Roleplay Profiles"] = "Perfiles de rol",
	["Enable roleplay profile integration"] = "Activar la integración de perfiles de rol",
	["Whisper windows show roleplay profile fields from Total RP 3 or any Mary Sue Protocol addon, and gain an Open RP Profile button on their shortcut bar that opens the partner's profile in the installed viewer."] = "Las ventanas de susurro muestran los campos de perfil de rol de Total RP 3 o cualquier addon de Mary Sue Protocol, y añaden un botón 'Abrir perfil de rol' en su barra de accesos directos que abre el perfil del otro jugador en el visor instalado.",
	["Open RP Profile"] = "Abrir perfil de rol",
	["Displayed profile fields"] = "Campos de perfil mostrados",
	["Whisper windows show the selected fields from the partner's Total RP 3 or Mary Sue Protocol profile. Fields left unselected -- or without profile data -- keep the standard display."] = "Las ventanas de susurro muestran los campos seleccionados del perfil de Total RP 3 o Mary Sue Protocol del otro jugador. Los campos no seleccionados -- o sin datos de perfil -- mantienen la visualización estándar.",
	["First Name"] = "Nombre",
	["Last Name"] = "Apellido",
	["Title"] = "Título",
	["Full Title"] = "Título completo",
	["Race"] = "Raza",
	["Class"] = "Clase",
	["Portrait"] = "Retrato",
	["Name & Class Color"] = "Color de nombre y clase",
	["The profile's first name, shown as the window's name text."] = "El nombre del perfil, mostrado como texto del nombre de la ventana.",
	["The profile's last name, shown as the window's name text."] = "El apellido del perfil, mostrado como texto del nombre de la ventana.",
	["The short title, shown on the window's details line."] = "El título corto, mostrado en la línea de detalles de la ventana.",
	["The long title, shown on the window's details line and portrait tooltip."] = "El título largo, mostrado en la línea de detalles de la ventana y en la información emergente del retrato.",
	["The custom race, replacing the character's race on the details line."] = "La raza personalizada, que sustituye a la raza del personaje en la línea de detalles.",
	["The custom class, replacing the character's class on the details line."] = "La clase personalizada, que sustituye a la clase del personaje en la línea de detalles.",
	["The profile's icon, replacing the class icon."] = "El icono del perfil, que sustituye al icono de clase.",
	["The profile's custom color, applied to the window's name text and to the class on the details line."] = "El color personalizado del perfil, aplicado al texto del nombre de la ventana y a la clase en la línea de detalles.",
	["Apply filter to character menus"] = "Aplicar filtro a los menús de personaje",

	-- History Viewer filters --
	["No Filter"] = "Sin filtro",
	["Relative Dates"] = "Fechas relativas",
	["%d or more"] = "%d o más",
	["Fewer than %d"] = "Menos de %d",
	["Results Filtered"] = "Resultados filtrados",
	["-- Results Filtered --"] = "-- Resultados filtrados --",
	["Results are hidden by the active filter. Click to open the Filters menu."] = "Los resultados están ocultos por el filtro activo. Haz clic para abrir el menú de filtros.",
	["Click to change how history is filtered."] = "Haz clic para cambiar cómo se filtra el historial.",
	["Click to open the Filters menu."] = "Haz clic para abrir el menú de filtros.",
	["Clicking the %s button on the message window will show that user's history in WIM's History Viewer."] = "Al hacer clic en el botón %s de la ventana de mensajes se mostrará el historial de ese usuario en el visor de historial de WIM.",

	-- Message input & formatting --
	["Wrap the message being typed"] = "Ajustar el mensaje que se escribe",
	["Limit wrapped lines"] = "Limitar las líneas ajustadas",
	["Visible input lines"] = "Líneas de entrada visibles",
	["Caps how far the input field grows; past the limit the message scrolls inside it."] = "Limita cuánto crece el campo de entrada; pasado el límite, el mensaje se desplaza dentro de él.",
	["The most lines the input field grows to before the message scrolls inside it."] = "El número máximo de líneas que crece el campo de entrada antes de que el mensaje se desplace dentro de él.",
	["The input field wraps long messages onto multiple lines, growing downward with the message instead of scrolling it on one line."] = "El campo de entrada ajusta los mensajes largos en varias líneas, creciendo hacia abajo con el mensaje en lugar de desplazarlo en una sola línea.",
	["Timestamp Format"] = "Formato de marca de tiempo",
	["Bracket Style"] = "Estilo de corchetes",
	["Colors"] = "Colores",
	["Sound"] = "Sonido",

	-- Chat type options --
	["Chat Windows"] = "Ventanas de chat",
	["Monitor"] = "Vigilar",
	["Record"] = "Registrar",
	["Minimap Alerts"] = "Alertas de minimapa",

	-- Help, bug reports & links --
	["Found a bug?"] = "¿Encontraste un error?",
	["Report a Bug"] = "Informar de un error",
	["Reports are welcome! Click below and follow the instructions in the bug report template."] = "¡Los informes son bienvenidos! Haz clic abajo y sigue las instrucciones de la plantilla de informes de errores.",
	["Visit us on GitHub"] = "Visítanos en GitHub",
	["Click to copy the link."] = "Haz clic para copiar el enlace.",
	["Press Ctrl+C to copy the link, then open it in your browser."] = "Pulsa Ctrl+C para copiar el enlace y ábrelo en tu navegador.",

	-- Debugging & development slash commands --
	["Clear the captured debug log."] = "Borra el registro de depuración capturado.",
	["Set debugging level: /wim debug [0|1|2]. 2 adds verbose chat event tracing."] = "Establece el nivel de depuración: /wim debug [0|1|2]. 2 añade seguimiento detallado de eventos de chat.",
	["Snapshot the next modern context menu while it is open."] = "Toma una instantánea del siguiente menú contextual moderno mientras esté abierto.",
	["Snapshot UI widget state for skin development: /wim snap all | <Frame.Dot.Path> (bare /wim snap lists the arguments)."] = "Guarda el estado de los widgets de la interfaz para el desarrollo de estilos: /wim snap all | <Frame.Dot.Path> (/wim snap sin argumentos lista las opciones).",

	-- Tutorials & notices --
	["WIM is currently running. To access WIM's wide array of options type:"] = "WIM se está ejecutando actualmente. Para acceder a la amplia gama de opciones de WIM escribe:",
	["WIM's message window has been hidden to WIM's Minimap Icon. If you want to end a conversation, you may do so by <Shift-Clicking> the close button."] = "La ventana de mensajes se ha ocultado en el icono del minimapa de WIM. Si quieres terminar una conversación, puedes hacerlo haciendo <Mayús-Clic> en el botón de cerrar.",
	["If you want all windows to be this size, you can set the default window size within WIM's options."] = "Si quieres que todas las ventanas tengan este tamaño, puedes establecer el tamaño predeterminado de ventana en las opciones de WIM.",
	["You can <Shift-Click> a tab and drag it out into it's own window."] = "Puedes hacer <Mayús-Clic> en una pestaña y arrastrarla fuera para convertirla en su propia ventana.",
	["You received a whisper which was hidden due to your current activity. You can change how whispers behave in WIM's options by typing"] = "Recibiste un susurro que se ocultó debido a tu actividad actual. Puedes cambiar cómo se comportan los susurros en las opciones de WIM escribiendo",
	["Sets the game's Social > Whisper Mode setting to In-line. Without it, suppressed whispers would vanish into a popout chat tab."] = "Establece la opción 'Social > Modo de susurro' del juego en 'En línea'. Sin ella, los susurros suprimidos desaparecerían en una pestaña emergente del chat.",

	-- Community channel maintenance --
	["Toggle the experimental community channel re-add repair (mutates chat window channels)."] = "Activa la reparación experimental de reincorporación de canales de comunidad (modifica los canales de las ventanas de chat).",
	["Toggle whether WIM focuses community streams at login."] = "Determina si WIM enfoca las transmisiones de comunidad al iniciar sesión.",

	-- Misc --
	["Age"] = "Edad",
	["Users in %s"] = "Usuarios en %s",

	-- History Viewer filter modes --
	["Sent by Me"] = "Enviado por mí",
	["Sent by Them"] = "Enviados por ellos",
	["Active Days"] = "Días activos",
	["Last 1 Day"] = "Último día",
	["Last 7 Days"] = "Últimos 7 días",
	["Last 30 Days"] = "Últimos 30 días",
	["Last 90 Days"] = "Últimos 90 días",


	-- Chrome background names --
	["None (fully clear)"] = "Ninguno (totalmente transparente)",
	["Transparent"] = "Transparente",
	["Rock"] = "Roca",
	["Marble"] = "Mármol",
	["Dark Marble"] = "Mármol oscuro",
	["Bank"] = "Banco",
	["Guild Vault"] = "Banco de hermandad",
	["Dark Sandstone"] = "Arenisca oscura",
	["Parchment (Tileable)"] = "Pergamino (repetible)",
	["Quest Parchment"] = "Pergamino de misión",
	["Raid Frame"] = "Marco de banda",
	["Destiny"] = "Destino",
	["Stationery (Auction)"] = "Papelería (subasta)",
	["Stationery (Illustrated)"] = "Papelería (ilustrada)",
	["Stationery (Orgrimmar)"] = "Papelería (Orgrimmar)",
	["Stationery (Thunder Bluff)"] = "Papelería (Cima del Trueno)",
	["Stationery (Undercity)"] = "Papelería (Entrañas)",
	["Stationery (Plain)"] = "Papelería (sencilla)",
	["World Map 1"] = "Mapa del mundo 1",
	["World Map 2"] = "Mapa del mundo 2",
	["Achievement Stats"] = "Estadísticas de logros",
	["Adventure Map Parchment"] = "Pergamino del mapa de aventuras",
	["Collections"] = "Colecciones",
	["Frame: Alliance"] = "Marco: Alianza",
	["Frame: Horde"] = "Marco: Horda",
	["Frame: Neutral"] = "Marco: Neutral",
	["Frame: Marine"] = "Marco: Marina",
	["Frame: Mechagon"] = "Marco: Mechagon",
	["Frame: Kyrian"] = "Marco: kyrianos",
	["Frame: Necrolord"] = "Marco: necroseñores",
	["Frame: Night Fae"] = "Marco: hadas nocturnas",
	["Frame: Venthyr"] = "Marco: venthyr",
	["Frame: Oribos"] = "Marco: Oribos",
	["Frame: Dragonflight"] = "Marco: Dragonflight",
	["Frame: The War Within"] = "Marco: The War Within",
	["Class Hall"] = "Sala de clase",
	["Class Hall (Internal)"] = "Sala de clase (interna)",
	["Garrison Landing Page"] = "Muelle de la ciudadela",
	["Garrison Mission"] = "Misión de ciudadela",
	["Ship Mission Parchment"] = "Pergamino de misión naval",
	["Garrison UI"] = "Interfaz de ciudadela",
	["Garrison UI 2"] = "Interfaz de ciudadela 2",
	["Credits: Classic"] = "Créditos: Classic",
	["Credits: Burning Crusade"] = "Créditos: Burning Crusade",
	["Credits: Wrath"] = "Créditos: Wrath",
	["Credits: Cataclysm"] = "Créditos: Cataclysm",
	["Credits: Mists of Pandaria"] = "Créditos: Mists of Pandaria",
	["Credits: Warlords"] = "Créditos: Warlords",
	["Credits: Legion"] = "Créditos: Legion",
	["Credits: Battle for Azeroth"] = "Créditos: Battle for Azeroth",


	-- Skin & options style notices --
	["WIM: the selected skin (%s) is configured through the modern options UI; the classic window is unavailable while it is active."] = "WIM: el estilo seleccionado (%s) se configura en la interfaz de opciones moderna; la ventana clásica no está disponible mientras esté activo.",
	["WIM: the selected skin (%s) requires the modern options UI; switch to another skin first."] = "WIM: el estilo seleccionado (%s) requiere la interfaz de opciones moderna; cambia primero a otro estilo.",
	["WIM options style: Modern (native Options > AddOns)."] = "Estilo de opciones de WIM: moderno (nativo, en Opciones > AddOns).",
	["WIM options style: Classic (WIM window)."] = "Estilo de opciones de WIM: clásico (ventana de WIM).",

};

if WIM.getLocale() == "esES" then
	WIM.AddLocale("esES", translations);
else
	WIM.AddLocale("esMX", translations);
end
