--[[
    Language Localization: ptBR
]]

WIM.AddLocale("ptBR", {
    ["WIM (WoW Instant Messenger)"] = "WIM (WoW Instant Messenger)",
    ["_Description"] = "WIM é um addon que traz um sensação familiar da comunicar através de bate-papo em World of Warcraft. Nesta tela, você será capaz de personalizar o WIM para adequá-lo as suas necessidades.",

    ["_DemoText"] = "Essa é uma demonstração da janela e não é totalmente funcional. Cloque esta janela no local onde você quer que todas as janelas surjam. Quando terminar, você pode fechar essa janela e suas preferências serão salvas.",

    ["_DateFormat"] = "%d/%m/%Y",

    ["Yes"] = "Sim",
    ["No"] = "Não",
    ["None"] = "Nenhum",
    ["Cancel"] = "Cancelar",
    ["Unknown"] = "Desconhecido",
    ["Click to update..."] = "Clique para atualizar...",
    ["Usage"] = "Uso",

    ["state_resting"] = "Descansando",
    ["state_combat"] = "Combate",
    ["state_pvp"] = "JxJ",
    ["state_arena"] = "Arena",
    ["state_party"] = "Grupo de masmorra",
    ["state_raid"] = "Grupo de raide",
    ["state_other"] = "Normal (outro)",

    ["Options"] = "Opções",

    ["Up"] = "Cima",
    ["Down"] = "Baixo",
    ["Left"] = "Esquerda",
    ["Right"] = "Direita",
    ["Ignore"] = "Ignorar",
    ["Block"] = "Bloquear",
    ["Enable WIM"] = "Ativar WIM",

    ["Enable"] = "Ativar",
    ["Disable"] = "Desativar",
    ["Enable window fading effects."] = "Ativar efeitos de desbotamento na janela",

    ["General"] = "Geral",
    ["History"] = "Histórico",
    ["Filters"] = "Filtros",

    ["Sort tabs by:"] = "Classificar guias por:",
	["Window Created"] = "Janela criada",
	["Last Activity"] = "Última atividade",
    ["Alphabetical"] = "Alfabético",

    -- Class Names --
    ["Druid"] = LOCALIZED_CLASS_NAMES_MALE.DRUID,
    ["Hunter"] = LOCALIZED_CLASS_NAMES_MALE.HUNTER,
    ["Mage"] = LOCALIZED_CLASS_NAMES_MALE.MAGE,
    ["Paladin"] = LOCALIZED_CLASS_NAMES_MALE.PALADIN,
    ["Priest"] = LOCALIZED_CLASS_NAMES_MALE.PRIEST,
    ["Rogue"] = LOCALIZED_CLASS_NAMES_MALE.ROGUE,
    ["Shaman"] = LOCALIZED_CLASS_NAMES_MALE.SHAMAN,
    ["Warlock"] = LOCALIZED_CLASS_NAMES_MALE.WARLOCK,
    ["Warrior"] = LOCALIZED_CLASS_NAMES_MALE.WARRIOR,
    ["Death Knight"] = LOCALIZED_CLASS_NAMES_MALE.DEATHKNIGHT,
    ["Monk"] = LOCALIZED_CLASS_NAMES_MALE.MONK,
    ["Demon Hunter"] = LOCALIZED_CLASS_NAMES_MALE.DEMONHUNTER,
	["Evoker"] = LOCALIZED_CLASS_NAMES_MALE.EVOKER,

    -- Female Class Names --
    ["DruidF"] = LOCALIZED_CLASS_NAMES_FEMALE.DRUID,
    ["HunterF"] = LOCALIZED_CLASS_NAMES_FEMALE.HUNTER,
    ["MageF"] = LOCALIZED_CLASS_NAMES_FEMALE.MAGE,
    ["PaladinF"] = LOCALIZED_CLASS_NAMES_FEMALE.PALADIN,
    ["PriestF"] = LOCALIZED_CLASS_NAMES_FEMALE.PRIEST,
    ["RogueF"] = LOCALIZED_CLASS_NAMES_FEMALE.ROGUE,
    ["ShamanF"] = LOCALIZED_CLASS_NAMES_FEMALE.SHAMAN,
    ["WarlockF"] = LOCALIZED_CLASS_NAMES_FEMALE.WARLOCK,
    ["WarriorF"] = LOCALIZED_CLASS_NAMES_FEMALE.WARRIOR,
    ["Death KnightF"] = LOCALIZED_CLASS_NAMES_FEMALE.DEATHKNIGHT,
    ["MonkF"] = LOCALIZED_CLASS_NAMES_FEMALE.MONK,
    ["Demon HunterF"] = LOCALIZED_CLASS_NAMES_FEMALE.DEMONHUNTER,
	["EvokerF"] = LOCALIZED_CLASS_NAMES_FEMALE.EVOKER,

    ["Game Master"] = "Mestre do jogo",

    -- WIM.lua --
    ["Toggle WIM 'On' and 'Off'."] = "Alternar WIM 'Ativado' e 'Desativado'",
    ["Toggle Debugging Mode 'On' and 'Off'."] = "Alternar modo de depuração 'Ativado' e 'Desativado'",

    -- Filters.lua --
    ["Whispers Sent by Addons"] = "Sussuros enviados pelos addons",
    ["WhisperSelect Part 1"] = "Sussurro selecionado parte 1",
    ["Example Spam Blocker"] = "Exemplo de bloqueador de spam",
    ["WhisperSelect Part 2"] = "Sussurro selecionado parte 2",
    ["Filter Name"] = "Filtrar nome",
    ["Filter By"] = "Filtro por",
    ["Pattern"] = "Molde",
    ["User Type"] = "Tipo de usuário",
    ["Level"] = "Nível do usuário",
    ["Friends"] = "Amigos",
    ["Guild Members"] = "Membros da guilda",
    ["Party Members"] = "Membros do grupo",
    ["Raid Members"] = "Membros da raide",
    ["Cross-Realm"] = "Através-Reino",
    ["Everyone"] = "Todos",
    ["User must be at least level:"] = "O usuário deve ter pelo menos no nível:",
    ["Apply to messages received."] = "Aplicar as mensagens recebidas.",
    ["Apply to messages sent."] = "Aplicar as mensagens enviadas",
    ["Apply to:"] = "Aplicar a:",
    ["All Classes"] = "Todas as classes",
    ["Action to Perform:"] = "Ação a ser executada:",
    ["Allow"] = "Permitir",
    ["Ignore"] = "Ignorar",
    ["Blocked"] = "Bloqueado",
    ["Save"] = "Salvo",
    ["Cancel"] = "Cancelar",
    ["Edit Filter"] = "Editar filtro",
    ["Add Filter"] = "Adicionar filtro",

    -- History.lua --
    ["WIM History Button"] = "Botão de histórico",
    ["Click to view message history."] = "Clique para visualizar o histórico de mensagem.",
    ["WIM pruned %d |4message:messages; from your history."] = "WIM suprimir %d |4mensagem:mensagens; de seu histórico.",
    ["History Viewer"] = "Visualizador do histórico",
    ["Filters"] = "Filtros",
    ["Are you sure you want to delete all history saved for %s on %s?"] = "Você tem certeza que você quer deletar todo o histórico salvadp dp %s no %s?",
    ["Search resulted in %d |4message:messages;."] = "Procura resultou em %d |4mensagem:mensagens;.",
    ["No results found!"] = "Não foram encontrados resultados!",
    ["Search"] = "Procurar",
    ["Show All"] = "Exibir tudo",
    ["Loading History"] = "Carregando histórico",
    ["Chat View"] = "Visualização de bate-papo",
    ["Text View"] = "Visualização de texto",
    ["BBCode"] = "BBCode",
    ["WIM History Viewer can be accessed any time by typing:"] = "O visualizador de histórico pode ser acessado todo o tempo escrevendo:",
    ["WIM History Viewer"] = "Visualizador de histórico",
    ["Display history viewer."] = "Exibir visualizador de histórico.",

    -- ldb.lua --
    ["No New Messages"] = "Não há novas mensagens",

    -- Menu.lua --
    ["Whispers"] = "Sussurros",
    ["Chat"] = "Bate-papo",

    -- Negotiate.lua --
    ["WIM Update Available!"] = "Atualização disponível!",

    -- ShortcutBar.lua --
    ["Player Location"] = "Zona do jogador",
    ["Unknown"] = "Desconhecido",
    ["Click to update..."] = "Clique para atualizar...",
    ["Invite to Party"] = "Convidar para o grupo",
    ["Invite to Guild"] = "Convidar para a guilda",
    ["Add Friend"] = "Adicionar amigo",
    ["Ignore Player"] = "Ignorar Jogador",
    ["Are you sure you want to\nignore %s?"] = "Você tem certeza que você quer\nignora %s?",
    ["Right-Click for profile links..."] = "Clique-Dereita nos links do perfil...",
    ["Profile Links"] = "Links de perfil",
	["Location"] = "Zona",
	["Game"] = "Jogo",
	["Realm"] = "Reino",
	["Character"] = "Personagem",
	["Copy Name"] = "Copiar nome",

    -- Tutorials.lua --
    ["View Updates"] = "Ver atualizações",

    -- WhisperEngine.lua --
    ["Whisper Received!"] = "Sussurro recebido!",
    ["Recently Sent Messages"] = "Mensagens enviadas recentemente",
    ["Users in %s"] = "Usuários em %s",

    -- Clear.lua --
    ["You are about to clear all of WIM's history!"] = "Você está prestes a limpar todo o histórico do WIM!",
    ["This action will reload your user interface."] = "Esta ação irá recarregar a interface do usuário.",
    ["Do you want to continue?"] = "Você quer continuar?",
    ["You are about to restore WIM's filters to it's default settings!"] = "Você está prestes a restaurar as configurações padrões do WIM!",
    ["Usage"] = "Uso",
    ["Clear various WIM data."] = "Limpar vários dados do WIM.",

    -- SlashHandler.lua --
    ["WIM Slash Commands"] = "Comandos de barra de WIM",
    ["Hide or show {all, whisper, chat} windows."] = "Ocultar ou exibir janelas {todas, de sussurro, de chat}.",
    ["To see a list of available WIM slash commands type:"] = "Para ver uma lista de comandos de barra do WIM disponível escreva:",
    ["Display available slash commands."] = "Exibir disponíveis comandos de barra.",
    ["Reload User Interface."] = "Recarregar interface do usuário.",

    -- TabHandler.lua --
    ["Manipulating Tabs"] = "Manipulando guias",

    -- WindowHandler.lua --
    ["Window Resized!"] = "Janela redimensionada!",
    ["Creating Tab Groups"] = "Criação de grupos de guia.",
    ["You can group two or many windows together by <Shift-Clicking> a window and dragging it on top of another."] = "Você pode agrupar duas ou mais janelas juntas por <Shift-Clicando> a janela e arrastando em cima da outra.",
    ["Resizing Windows"] = "Redimensionar as janelas",
    ["You can resize a window by holding <Shift> and dragging the bottom right corner of the window."] = "Você pode redimensionar uma janela segurando <Shift> e arrastando no canto direito embaixo na janela.",
    ["Demo Window"] = "Janela de demonstração",
    ["<Shift-Click> to close window."] = "<Shift-Clique> para fechar a janela.",
    ["Message Window Hidden"] = "Messagem da janela oculta",
    ["Default"] = "Padrão",
    ["%s is Away From Keyboard: %s"] = "%s está LDT: %s",
    ["%s does not wish to be disturbed: %s"] = "%s não deseja ser pertubado: %s",
    ["Right-Mouse Click!"] = "Clique-Direita!",
    ["There might be useful tools hidden under the message box. Right-Click to see them!"] = "Pode haver ferramentas úteis ocultas sob a caixa de mensagem. Clique-direito para vê-las!",

    -- Options.lua --
    ["Display WIM's options."] = "Exibir opções de WIM.",
    ["Resetting WIM will clear all of your settings!"] = "Resetando WIM irá limpar todas as suas configurações!",
    ["A reset will reload your user interface."] = "Um reset recarregará sua interface de usuário.",
    ["Reset all options to default."] = "Resetar todas as opções para padrão.",

    -- CoreOptions --
    ["Created By:"] = "Criado por:",
    ["Special Thanks:"] = "Agradecimentos especiais:",
    ["Welcome!"] = "Bem-Vindo!",
    ["Enable WIM"] = "Ativar WIM",
    ["Display Minimap Icon"] = "Exibir ícone no minimapa",
    ["<Right-Click> to show unread messages."] = "<Clique-Direita> para exibir mensagens não lidas",
	["Display Addon Compartment Icon"] = "Exibir ícone do compartimento de addons",
    ["Display Tutorials"] = "Exibir tutoriais",
    ["Reset Tutorials"] = "Resetar tutoriais",
    ["Credits"] = "Créditos",
    ["This is a long message which contains both emoticons and urls 8). WIM's home is www.WIMAddon.com."] = "Esta é uma mensagem longa que contém emoticons e URLs 8). A página do WIM é www.WIMAddon.com.",
    ["Message Formatting"] = "Formatação",
    ["Manipulate how WIM displays messages."] = "Manipule como WIM exibi mensagens.",
    ["Preview"] = "Previsualização",
    ["Display Time Stamps"] = "Exibir carimbos de tempo",
    ["Display Emoticons"] = "Exibir emoticons",
    ["Display URLs as Links"] = "Exibir URLs como links",
    ["Indent long messages."] = "Encomendar mensagens longas",
	["Bracket names."] = "Nomes de colchetes",
    ["Window Behavior"] = "Comportamento",
    ["You can control how windows behave while you are in different situations."] = "Você pode controlar como as jenelas se comportam enquanto você está em diferentes situações.",
    ["Intercept Slash Commands"] = "Interceptar comandos de barra",
    ["Include sent messages in /REPLY."] = "Incluir mensagens enviadas em /r",
	["Obey autofocus rules when opening frames via the menu. (autofocus if unchecked)"] = "Obedecer as regras de foco automático ao abrir janelas",
    ["Use the same rules for all states."] = "Usar as mesmas regras para todos os estados",
    ["Behaviors for state:"] = "Comportamentos de estado:",
    ["Pop-Up window when message is sent."] = "Brotar janela quando a mensagem é enviada",
    ["Pop-Up window when message is received."] = "Brotar janela quando a mensagem é recebida",
    ["Auto focus a window when it is shown."] = "Focar na janela automaticamente quando ela aparecer",
    ["Keep focus on window after sending a message."] = "Manter o foco na janela depis de enviar mensagem",
    ["Suppress messages from the default chat frame."] = "Suprimir mensagens da janela de bate-papo padrão",
    ["Window Settings"] = "Definições da janela",
    ["Some settings may be limited by certain skins."] = "Algumas configurações podem ser limitadas por certos temas.",
    ["Default Width"] = "Largura padrão",
    ["Default Height"] = "Altura padrão",
    ["Window Scale"] = "Escala da janela",
    ["Window Alpha"] = "Alfa da janela",
    ["Set Window Spawn Location"] = "Definir o local do surgimento da janela",
    ["Up"] = "Cima",
    ["Down"] = "Baixo",
    ["Left"] = "Esquerda",
    ["Right"] = "Direita",
    ["Cascade overlapping windows."] = "Janelas em cascata sobrepostas",
    ["Ignore arrow keys in message box."] = "Ignorar teclas de seta na caixa de mensagem",
    ["Allow <ESC> to hide windows."] = "Permitir que <ESC> oculte as janelas",
    ["Display Settings"] = "Visualização",
    ["Configure general window display settings."] = "Configure a exibição geral da janela.",
    ["Window Skin:"] = "Tema da janela:",
    ["Version"] = "Versão",
    ["Color: System Messages"] = "Cor: mensagens do sistema",
    ["Color: Error Messages"] = "Cor: mensagens de erro",
    ["Color: URL - Web Addresses"] = "Cor: URL - endereços de sites",
    ["Color: History Messages Sent"] = "Cor: mensagens do histórico enviadas",
    ["Color: History Messages Received"] = "Cor: mensagens do histórico recebidas",
    ["Use colors suggested by skin."] = "Usar cores sugerido pelo tema",
    ["Enable window fading effects."] = "Ativar efeitos de desbotamento na janela",
    ["Enable window animation effects."] = "Ativar efeitos de animação na janela",
    ["Display item links when hovering over them."] = "Exibir links de item quando pairar o ponteiro sobre",
    ["Fonts"] = "Fontes",
    ["Configure the fonts used in WIM's message windows."] = "Configure a fonte usada na janela de mensagens do WIM.",
    ["Font Outline"] = "Contorno da fonte",
    ["Thin"] = "Fino",
    ["Thick"] = "Grosso",
    ["Use font suggested by skin."] = "Usar fonte sugerido pelo tema",
    ["Chat Font Size"] = "Tamanho da fonte do bate-papo",
    ["Configure general display settings when dealing with whispers."] = "Configure as exibições gerais quando se lida com sussurros.",
    ["Color: Messages Sent"] = "Cor: mensagens enviadas",
    ["Color: Messages Received"] = "Cor: mensagens recebidas",
	["Color: BNet Messages Sent"] = "Color: mensagens de BNet enviadas",
    ["Color: BNet Messages Received"] = "Color: mensagens de BNet recibidas",
    ["Display user class icons and details."] = "Exibir ícones e detalhes sobre a classe do usuário",
    ["Requires who lookups."] = "Exige quem procura.",
    ["Display Shortcut Bar"] = "Exibir barra de atalhos",
    ["Allow"] = "Permitir",
    ["Ignore"] = "Ignorar",
    ["Block"] = "Bloqueio",
    ["Filtering"] = "Filtragem",
    ["Filtering allows you to control which messages are handled as well as how they are handled by WIM."] = "Filtragem permite que você controle quais mensagens são tratadas também como elas são manipuladas pelo WIM.",
    ["Enable Filtering"] = "Ativar filtragem",
    ["Protected"] = "Protegido",
    ["Action:"] = "Ação:",
    ["Occurrences:"] = "Ocorrências:",
    ["Delete Filter"] = "Deletar filtro",
    ["History"] = "Histórico",
    ["WIM can store conversations to be viewed at a later time."] = "WIM pode armanezar conversações para ser visto mais tarde.",
    ["Enable History"] = "Ativar histórico",
    ["Messages"] = "Mensagens",
    ["Preview history inside message windows."] = "Previsualizar histórico dentro das janelas de mensagem",
    ["Record Friends"] = "Gravar amigos",
    ["Record Guild"] = "Gravar guilda",
    ["Record Everyone"] = "Gravar todos",
    ["Record Chat"] = "Gravar bate-papo",
    ["Maintenance"] = "Manutenção",
    ["Allowing your history logs to grow too large will affect the game's performance, therefore it is reccomended that you use the following options."] = "Permita que o registro da histórico ao crescer e fiquei muito grande afetará o desempenho do jogo, portanto o recomendável que você use as seguintes opções.",
    ["Save a maximum number of messages per person."] = "Salvar o máximo de números de mensagens por pessoa",
    ["%d |4Week:Weeks;"] = "%d |4Semana:Semanas;",
    ["Automatically delete old messages."] = "Deletar automaticamente mensagens antigas",
    ["WIM-2-WIM is a feature which allows users with WIM to interact in ways that normal whispering can not."] = "WIM-2-WIM é um recurso que permite que o usuário com WIM possa interagir de forma que o modo padrão de sussuro não consegue.",
    ["Enable WIM-2-WIM"] = "Ativar WIM-2-WIM",
    ["Privacy"] = "Privacidade",
    ["Restrict the data that is shared."] = "Restringir os dados que são compartilhados.",
    ["Allow others to see me typing."] = "Permitir que outros me vejam digitando.",
    ["Allow others to see my location."] = "Permitir que outros vejam minha localização.",
    ["Main"] = "Principal",
    ["General"] = "Geral",
    ["User Level"] = "Nível do usuário",
    ["Windows will also be hidden when frames such as the world map are shown."] = "Janelas também serão ocultadas quando os quadros, como o mapa-múndi são exibidos.",
    ["Sounds"] = "Sons",
    ["Configure various sound events and how they are triggered."] = "Configure eventos sonoros diversos, e como eles são acionados.",
    ["Play sound when a whisper is received."] = "Reproduzir som quando um sussurro é recebido",
    ["Play special sound for friends."] = "Reproduzir som especial para amigos",
	["Play special sound for battle.net friends."] = "Reproduzir som especial para amigos de battle.net",
    ["Play special sound for guild members."] = "Reproduzir som especial para membros da guilda",
    ["Play sound when a whisper is sent."] = "Reproduzir som quando um sussurro é enviado",
    ["Allow others to see my talent spec."] = "Permitir que outros vejam o meu talento especifico",
    ["Window Strata:"] = "Strata da janela:",
	["Background"] = BACKGROUND,
	["Low"] = LOW,
	["Medium"] = "Médio",
	["High"] = "Alto",
	["Dialog"] = ENABLE_DIALOG,
	["Tooltip"] = "Dica",
    ["Unlock from Minimap"] = "Desbloquear do minimapa",
    ["Press <Tab> to advance to next tell target."] = "Pressionar <Tab> para avançar para o próximo alvo",
	["Force sounds when game sound is disabled."] = "Forçar sons quando o som do jogo estiver desativado",
    ["Colorize names."] = "Colorir nomes",
    ["Clamp window to screen."] = "Fixar a janela na tela",
    ["Group with whisper windows."] = "Agrupar com janelas sussurradas",

    -- TabManagement.lua --
    ["Tab Management"] = "Gerenciador de guia",
    ["Automatically manage your open windows and place them into appropriate tab groups."] = "Gerencie automaticamente suas janelas abertas e coloque-as em grupos de abas apropriados.",
    ["Automatically group whispers."] = "Formar automaticamente um grupo de sussurros",
	["Automatically group chat windows."] = "Formar automaticamente um grupo de janelas de bate-papo",
    ["Place friends in their own group."] = "Colocar amigos no seu próprio grupo",
    ["Place guild members in their own group."] = "Colocar membros da guilda no seu próprio grupo",
    ["Does not apply to windows already opened."] = "Isso não se aplica à janelas já abertas.",

    -- Talent Specs --
    ["Hybrid"] = "Híbrido",

    -- Filters.lua --
    ["Show Alert"] = "Exibir alerta",
    ["WIM has blocked a message from %s."] = "O WIM bloqueou uma mensagem de %s.",
    ["View Blocked Message"] = "Ver mensagem bloqueada",
    ["Blocked Message"] = "Mensagem bloqueada",

    -- MinimapIcon.lua
    ["Show Unread Messages"] = "Exibir mensagens não lidas",
    ["Show All Windows"] = "Exibir todas as janelas",
    ["Hide All Windows"] = "Ocultar todas as janelas",

    --Emoticons.lua
    ["Also"] = "Além disso",
    ["More"] = "Mais",
    ["Emoticons"] = "Emoticons",

    --Expose.lua
    ["Your conversations have been hidden in order to clear your screen while in combat. To disable this feature type"] = "Suas conversas foram ocultas para limpar sua tela durante o combate. Para desativar esse recurso, digite",
    ["Expose"] = "Expose",
    ["Expose is a Mac OS X inspired feature which enables you to quickly clear your screen of windows and then restore them back to their original position."] = "Expose é um recurso inspirado no Mac OS X que permite limpar rapidamente a tela da janelas e depois restaurá-la à sua posição original.",
    ["Auto hide/restore windows during combat."] = "Ocultar/restaurar automaticamente janelas durante o combate",
	["Delay if I am typing a message."] = "Atraso se estou escrevendo uma mensagem",
    ["Border Size"] = "Tamanho da borda",
    ["Only while in an instance."] = "Somente enquanto estiver em uma instância",
    ["Show Border"] = "Exibir borda",
    ["Animation Direction:"] = "Direção da animação:",

    --ChatEngine.lua
    ["WIM will manage this chat type within its own message windows."] = "O WIM gerenciará esse tipo de bate-papo dentro de suas próprias janelas de mensagens.",
    ["Show Minimap Alerts"] = "Exibir alertas do minimapa",
    ["Never pop-up on my screen."] = "Nunca aparecer na minha tela",
    ["Never suppress messages."] = "Nunca suprimir mensagens",
	["Include emotes."] = "Incluir expressões",
    ["Have WIM monitor this channel."] = "Faça com que o WIM monitore este canal.",
    ["Never Pop"] = "Nunca aparecer",
    ["Never have this window pop-up on my screen."] = "Nunca essa janela apareceu na minha tela.",
    ["Never Suppress"] = "Nunca suprimir",
    ["Never suppress messages from the default chat frame."] = "Nunca suprima mensagens do quadro de bate-papo padrão.",
    ["Show unread message alert on minimap."] = "Exibir alerta de mensagem não lida no minimapa.",
    ["No History"] = "Sem histórico",
    ["Do not record history for this channel."] = "Não grave histórico para este canal.",
    ["World Chat"] = "Bate-papo mundial",
    ["Custom Chat"] = "Bate-papo personalizado",
    ["Community Chat"] = "Bate-papo da comunidade",
    ["Community Chats"] = "Bate-papos da comunidade",
    ["Chat"] = "Bate-papo",
    ["Play special sound for %s."] = "Reproduzir som especial para %s",
    ["Play sound when a message is received."] = "Reproduzir som quando uma mensagem é recebida.",
    ["Play sound when a message is sent."] = "Reproduzir som quando uma mensagem é enviada.",
    ["Do not play sounds for this channel."] = "Não reproduz sons para este canal.",
    ["No Sound"] = "Sem som",
    ["Sensitivity"] = "Sensibilidade",
    ["Enable WorldFrame Click Detection."] = "Ativar detecção de clique no WorldFrame",

    --OffScreenTracker.lua
    ["WIM Window Off Screen"] = "Janela WIM fora da tela",
    ["Click to reposition."] = "Clique para reposicionar.",

	-- Whisper Mode Warnings
    ["Whisper Mode: In-line"] = "Modo de susurro: em linha",
	["Set whispers to In-line"] = "Definir sussurros como Em linha",
	["Message suppression requires whispers to be set to 'In-line'."] = "A supressão de mensagens requer que os sussurros estejam configurados como 'Em linha'.",
	["It is recommended for whispers to be set to in-line in order to handle their behavior properly."] = "Recomenda-se configurar os sussurros como Em linha para lidar corretamente com seu comportamento.",

	-- Skins --
	["Blue"] = "Azul",
	["Green"] = "Verde",
	["Red"] = "Vermelho",
	["Yellow"] = "Amarelo",

	-- Battle.net friend consolidation (History Viewer)
	["Battle.net Friends"] = "Amigos da Battle.net",
	["Are you sure you want to delete ALL history saved with %s, across every realm and every character on this account?"] = "Você tem certeza que você quer deletar TODO o histórico salvo com %s, em todos os reinos e todos os personagens desta conta?",

	-- Per-date deletion from the History Viewer filter list
	["Are you sure you want to delete the %s history with %s across every realm and character on this account?"] = "Você tem certeza que você quer deletar o histórico de %s com %s em todos os reinos e personagens desta conta?",
	["Are you sure you want to delete the %s history for %s across every character on %s?"] = "Você tem certeza que você quer deletar o histórico de %s de %s em todos os personagens de %s?",
	["Are you sure you want to delete the %s history for %s on %s?"] = "Você tem certeza que você quer deletar o histórico de %s de %s em %s?",


	-- Modern options panel --
	["Use modern options UI"] = "Usar a interface de opções moderna",
	["Classic Options"] = "Opções clássicas",
	["Open"] = "Abrir",
	["Open the classic WIM options window."] = "Abre a janela de opções clássicas do WIM.",
	["Choose the options style: /wim style [classic|modern]."] = "Escolha o estilo das opções: /wim style [classic|modern].",
	["When enabled, WIM's Options entry points (minimap menu, key binding, /wim) open this panel instead of the classic WIM options window."] = "Quando ativada, os pontos de acesso às opções do WIM (menu do minimapa, atalho de teclado, /wim) abrem este painel em vez da janela de opções clássicas do WIM.",
	["While a modern-only skin (such as WIM Modern) is selected, this option is enforced: those skins are configured through this panel only."] = "Com um skin exclusivamente moderno selecionado (como o WIM Modern), esta opção é imposta: esses skins são configurados apenas por este painel.",

	-- Modern skin styling --
	["Modern Skin"] = "Skin moderno",
	["These settings style WIM's modern-only skins (such as WIM Modern), which are built from the game's own interface art. They shape the History Viewer and the chat windows, and are available only while a modern-only skin is selected under General > Display Settings; with a classic skin active they are greyed out."] = "Essas configurações definem o estilo dos skins exclusivamente modernos do WIM (como o WIM Modern), construídos com a arte de interface do próprio jogo. Elas moldam o visualizador de histórico e as janelas de bate-papo, e estão disponíveis apenas enquanto um skin exclusivamente moderno estiver selecionado em Geral > Configurações de exibição; com um skin clássico ativo, ficam esmaecidas.",
	["Disabled while a modern-only skin (such as WIM Modern) is selected: those skins carry settings the classic window has no controls for."] = "Desativado enquanto um skin exclusivamente moderno (como o WIM Modern) estiver selecionado: esses skins trazem configurações para as quais a janela clássica não tem controles.",
	["Frame background"] = "Fundo da moldura",
	["Message area background"] = "Fundo da área de mensagens",
	["Chat history background"] = "Fundo do histórico de bate-papo",
	["Selection panels background"] = "Fundo dos painéis de seleção",
	["Window frame background"] = "Fundo da moldura da janela",
	["None (game default)"] = "Nenhum (padrão do jogo)",
	["Panels see through to the game world"] = "Os painéis deixam ver o mundo do jogo",
	["Window sees through to the game world"] = "A janela deixa ver o mundo do jogo",
	["Draws the frame background only around the panels, so a clear panel background (None or Transparent) shows the game world behind the viewer instead of the frame fill."] = "Desenha o fundo da moldura apenas ao redor dos painéis, de modo que um fundo de painel limpo (Nenhum ou Transparente) mostra o mundo do jogo atrás do visualizador em vez do preenchimento da moldura.",
	["Draws the window frame background only around the message area, so a clear message area background (None or Transparent) shows the game world behind the window."] = "Desenha o fundo da moldura da janela apenas ao redor da área de mensagens, de modo que um fundo de área de mensagens limpo (Nenhum ou Transparente) mostra o mundo do jogo atrás da janela.",

	-- Roleplay profiles (Total RP 3 / Mary Sue Protocol) --
	["Roleplay Profiles"] = "Perfis de roleplay",
	["Enable roleplay profile integration"] = "Ativar a integração de perfis de roleplay",
	["Whisper windows show roleplay profile fields from Total RP 3 or any Mary Sue Protocol addon, and gain an Open RP Profile button on their shortcut bar that opens the partner's profile in the installed viewer."] = "As janelas de sussurro mostram os campos de perfil de roleplay do Total RP 3 ou de qualquer addon Mary Sue Protocol, e ganham um botão 'Abrir perfil de roleplay' na sua barra de atalhos que abre o perfil do outro jogador no visualizador instalado.",
	["Open RP Profile"] = "Abrir perfil de roleplay",
	["Displayed profile fields"] = "Campos de perfil exibidos",
	["Whisper windows show the selected fields from the partner's Total RP 3 or Mary Sue Protocol profile. Fields left unselected -- or without profile data -- keep the standard display."] = "As janelas de sussurro mostram os campos selecionados do perfil de Total RP 3 ou Mary Sue Protocol do outro jogador. Os campos não selecionados -- ou sem dados de perfil -- mantêm a exibição padrão.",
	["First Name"] = "Nome",
	["Last Name"] = "Sobrenome",
	["Title"] = "Título",
	["Full Title"] = "Título completo",
	["Race"] = "Raça",
	["Class"] = "Classe",
	["Portrait"] = "Retrato",
	["Name & Class Color"] = "Cor do nome e da classe",
	["The profile's first name, shown as the window's name text."] = "O nome do perfil, exibido como texto do nome da janela.",
	["The profile's last name, shown as the window's name text."] = "O sobrenome do perfil, exibido como texto do nome da janela.",
	["The short title, shown on the window's details line."] = "O título curto, exibido na linha de detalhes da janela.",
	["The long title, shown on the window's details line and portrait tooltip."] = "O título longo, exibido na linha de detalhes da janela e na dica do retrato.",
	["The custom race, replacing the character's race on the details line."] = "A raça personalizada, substituindo a raça do personagem na linha de detalhes.",
	["The custom class, replacing the character's class on the details line."] = "A classe personalizada, substituindo a classe do personagem na linha de detalhes.",
	["The profile's icon, replacing the class icon."] = "O ícone do perfil, substituindo o ícone de classe.",
	["The profile's custom color, applied to the window's name text and to the class on the details line."] = "A cor personalizada do perfil, aplicada ao texto do nome da janela e à classe na linha de detalhes.",
	["Apply filter to character menus"] = "Aplicar filtro aos menus de personagem",

	-- History Viewer filters --
	["No Filter"] = "Sem filtro",
	["Relative Dates"] = "Datas relativas",
	["%d or more"] = "%d ou mais",
	["Fewer than %d"] = "Menos de %d",
	["Results Filtered"] = "Resultados filtrados",
	["-- Results Filtered --"] = "-- Resultados filtrados --",
	["Results are hidden by the active filter. Click to open the Filters menu."] = "Os resultados estão ocultos pelo filtro ativo. Clique para abrir o menu de filtros.",
	["Click to change how history is filtered."] = "Clique para alterar como o histórico é filtrado.",
	["Click to open the Filters menu."] = "Clique para abrir o menu de filtros.",
	["Clicking the %s button on the message window will show that user's history in WIM's History Viewer."] = "Clicar no botão %s da janela de mensagens mostrará o histórico desse usuário no Visualizador de histórico do WIM.",

	-- Message input & formatting --
	["Wrap the message being typed"] = "Quebrar a mensagem sendo digitada",
	["Limit wrapped lines"] = "Limitar as linhas quebradas",
	["Visible input lines"] = "Linhas de entrada visíveis",
	["Caps how far the input field grows; past the limit the message scrolls inside it."] = "Limita até onde o campo de entrada cresce; além do limite, a mensagem rola dentro dele.",
	["The most lines the input field grows to before the message scrolls inside it."] = "O número máximo de linhas que o campo de entrada cresce antes de a mensagem rolar dentro dele.",
	["The input field wraps long messages onto multiple lines, growing downward with the message instead of scrolling it on one line."] = "O campo de entrada quebra mensagens longas em várias linhas, crescendo para baixo com a mensagem em vez de rolá-la em uma única linha.",
	["Timestamp Format"] = "Formato de carimbo de tempo",
	["Bracket Style"] = "Estilo de colchetes",
	["Colors"] = "Cores",
	["Sound"] = "Som",

	-- Chat type options --
	["Chat Windows"] = "Janelas de bate-papo",
	["Monitor"] = "Monitorar",
	["Record"] = "Gravar",
	["Minimap Alerts"] = "Alertas do minimapa",

	-- Help, bug reports & links --
	["Found a bug?"] = "Encontrou um erro?",
	["Report a Bug"] = "Relatar um erro",
	["Reports are welcome! Click below and follow the instructions in the bug report template."] = "Relatórios são bem-vindos! Clique abaixo e siga as instruções do modelo de relatório de erros.",
	["Visit us on GitHub"] = "Visite-nos no GitHub",
	["Click to copy the link."] = "Clique para copiar o link.",
	["Press Ctrl+C to copy the link, then open it in your browser."] = "Pressione Ctrl+C para copiar o link e abra-o no seu navegador.",

	-- Debugging & development slash commands --
	["Clear the captured debug log."] = "Limpa o log de depuração capturado.",
	["Set debugging level: /wim debug [0|1|2]. 2 adds verbose chat event tracing."] = "Define o nível de depuração: /wim debug [0|1|2]. 2 adiciona rastreamento detalhado de eventos de bate-papo.",
	["Snapshot the next modern context menu while it is open."] = "Captura uma instantâneo do próximo menu de contexto moderno enquanto estiver aberto.",
	["Snapshot UI widget state for skin development: /wim snap all | <Frame.Dot.Path> (bare /wim snap lists the arguments)."] = "Captura o estado dos widgets da interface para desenvolvimento de skins: /wim snap all | <Frame.Dot.Path> (/wim snap sem argumentos lista as opções).",

	-- Tutorials & notices --
	["WIM is currently running. To access WIM's wide array of options type:"] = "O WIM está em execução. Para acessar a ampla gama de opções do WIM, digite:",
	["WIM's message window has been hidden to WIM's Minimap Icon. If you want to end a conversation, you may do so by <Shift-Clicking> the close button."] = "A janela de mensagens foi ocultada no ícone do minimapa do WIM. Se quiser encerrar uma conversa, você pode fazê-lo <Shift-Clicando> no botão de fechar.",
	["If you want all windows to be this size, you can set the default window size within WIM's options."] = "Se quiser que todas as janelas tenham esse tamanho, você pode definir o tamanho padrão das janelas nas opções do WIM.",
	["You can <Shift-Click> a tab and drag it out into it's own window."] = "Você pode <Shift-clicar> em uma aba e arrastá-la para fora para torná-la uma janela própria.",
	["You received a whisper which was hidden due to your current activity. You can change how whispers behave in WIM's options by typing"] = "Você recebeu um sussurro que foi ocultado devido à sua atividade atual. Você pode alterar como os sussurros se comportam nas opções do WIM digitando",
	["Sets the game's Social > Whisper Mode setting to In-line. Without it, suppressed whispers would vanish into a popout chat tab."] = "Define a configuração 'Social > Modo de sussurro' do jogo como 'Em linha'. Sem ela, os sussurros suprimidos desapareceriam em uma aba popout do chat.",

	-- Community channel maintenance --
	["Toggle the experimental community channel re-add repair (mutates chat window channels)."] = "Ativa o reparo experimental de readição de canais de comunidade (altera os canais das janelas de bate-papo).",
	["Toggle whether WIM focuses community streams at login."] = "Define se o WIM foca os fluxos de comunidade ao fazer login.",

	-- Misc --
	["Age"] = "Idade",
	["Users in %s"] = "Usuários em %s",

	-- History Viewer filter modes --
	["Sent by Me"] = "Enviado por mim",
	["Sent by Them"] = "Enviados por eles",
	["Active Days"] = "Dias ativos",
	["Last 1 Day"] = "Último dia",
	["Last 7 Days"] = "Últimos 7 dias",
	["Last 30 Days"] = "Últimos 30 dias",
	["Last 90 Days"] = "Últimos 90 dias",


	-- Chrome background names --
	["None (fully clear)"] = "Nenhum (totalmente transparente)",
	["Transparent"] = "Transparente",
	["Rock"] = "Rocha",
	["Marble"] = "Mármore",
	["Dark Marble"] = "Mármore escuro",
	["Bank"] = "Banco",
	["Guild Vault"] = "Cofre da guilda",
	["Dark Sandstone"] = "Arenito escuro",
	["Parchment (Tileable)"] = "Pergaminho (repetível)",
	["Quest Parchment"] = "Pergaminho de missão",
	["Raid Frame"] = "Moldura de raide",
	["Destiny"] = "Destino",
	["Stationery (Auction)"] = "Papelaria (leilão)",
	["Stationery (Illustrated)"] = "Papelaria (ilustrada)",
	["Stationery (Orgrimmar)"] = "Papelaria (Orgrimmar)",
	["Stationery (Thunder Bluff)"] = "Papelaria (Penhasco do Trovão)",
	["Stationery (Undercity)"] = "Papelaria (Cidade Subterrânea)",
	["Stationery (Plain)"] = "Papelaria (simples)",
	["World Map 1"] = "Mapa-múndi 1",
	["World Map 2"] = "Mapa-múndi 2",
	["Achievement Stats"] = "Estatísticas de conquistas",
	["Adventure Map Parchment"] = "Pergaminho do mapa de aventuras",
	["Collections"] = "Coleções",
	["Frame: Alliance"] = "Moldura: Aliança",
	["Frame: Horde"] = "Moldura: Horda",
	["Frame: Neutral"] = "Moldura: Neutro",
	["Frame: Marine"] = "Moldura: Marinha",
	["Frame: Mechagon"] = "Moldura: Mechagon",
	["Frame: Kyrian"] = "Moldura: kyrianos",
	["Frame: Necrolord"] = "Moldura: necrossenhores",
	["Frame: Night Fae"] = "Moldura: fadas noturnas",
	["Frame: Venthyr"] = "Moldura: venthyr",
	["Frame: Oribos"] = "Moldura: Oribos",
	["Frame: Dragonflight"] = "Moldura: Dragonflight",
	["Frame: The War Within"] = "Moldura: The War Within",
	["Class Hall"] = "Salão de classe",
	["Class Hall (Internal)"] = "Salão de classe (interno)",
	["Garrison Landing Page"] = "Página de desembarque da guarnição",
	["Garrison Mission"] = "Missão de guarnição",
	["Ship Mission Parchment"] = "Pergaminho de missão naval",
	["Garrison UI"] = "Interface da guarnição",
	["Garrison UI 2"] = "Interface da guarnição 2",
	["Credits: Classic"] = "Créditos: Clássico",
	["Credits: Burning Crusade"] = "Créditos: Burning Crusade",
	["Credits: Wrath"] = "Créditos: Wrath",
	["Credits: Cataclysm"] = "Créditos: Cataclysm",
	["Credits: Mists of Pandaria"] = "Créditos: Mists of Pandaria",
	["Credits: Warlords"] = "Créditos: Warlords",
	["Credits: Legion"] = "Créditos: Legion",
	["Credits: Battle for Azeroth"] = "Créditos: Battle for Azeroth",


	-- Skin & options style notices --
	["WIM: the selected skin (%s) is configured through the modern options UI; the classic window is unavailable while it is active."] = "WIM: a skin selecionada (%s) é configurada pela interface de opções moderna; a janela clássica não está disponível enquanto ela estiver ativa.",
	["WIM: the selected skin (%s) requires the modern options UI; switch to another skin first."] = "WIM: a skin selecionada (%s) requer a interface de opções moderna; mude primeiro para outra skin.",
	["WIM options style: Modern (native Options > AddOns)."] = "Estilo de opções do WIM: moderno (nativo, em Opções > AddOns).",
	["WIM options style: Classic (WIM window)."] = "Estilo de opções do WIM: clássico (janela do WIM).",

});
