--[[
    Language Localization: ruRU
    Translated by: StingerSoft <stingersoft@iti.lt>
]]

WIM.AddLocale("ruRU", {
	["WIM (WoW Instant Messenger)"] = "WIM (WoW Instant Messenger)",
	["_Description"] = "WIM - модификация, которая принесет Вам знакомое чувство удобства при общении в Мире Warcraft. На данном экране Вы сможете настроить WIM по своему вкусу. Если у Вас есть какие-нибудь вопросы, комментарии или предложения, пожалуйста обратитесь на сайт разработчка http://www. WIMAddon.com (английский).",

	["_DemoText"] = "Это демонстрационное окно! Разместите данное окно на Вашем экране там, где Вы хотели бы, чтобы появлялось окно WIM по умолчанию. После того, как Вы разместите данное окно в нужное место, закройте его и настройки будут сохранены автоматически.",

	["_DateFormat"] = "%d.%m.%Y",

	["Yes"] = "Да",
	["No"] = "Нет",
	["None"] = "Нету",
	["Cancel"] = "Отмена",
	["Unknown"] = "Неизвестно",
	["Click to update..."] = "Кликните для обновления...",
	["Usage"] = "Используется",

	["state_resting"] = "Отдыхает",
	["state_combat"] = "В бою",
	["state_pvp"] = "ПВП",
	["state_arena"] = "На арене",
	["state_party"] = "В групповом инстансе",
	["state_raid"] = "В рейдовом инстансе",
	["state_other"] = "Обычный (Другое)",

	["Options"] = "Настройки",

	["Up"] = "Вверх",
	["Down"] = "Вниз",
	["Left"] = "Влево",
	["Right"] = "Вправо",
	["Ignore"] = "Игнорировать",
	["Block"] = "Блокировать",
	["Enable WIM"] = "Включить WIM",

	["Enable"] = "Включить",
	["Disable"] = "Выключить",
	["Enable window fading effects."] = "Включить затухание.",

	["General"] = "Основное",
	["History"] = "История",
	["Filters"] = "Фильтры",

	["Include sent messages in /REPLY."] = "Включать отправленные сообщения в /REPLY.",
	["Display URLs as Links"] = "Отображать URL-адрес как ссылку.",

	["Sort tabs by:"] = "Сортировка закладок:",
	["Window Created"] = "По созданию окна",
	["Last Activity"] = "По последней активности",
	["Alphabetical"] = "По алфавиту",

    -- Class Names --
	["Druid"] = "Друид",
	["Hunter"] = "Охотник",
	["Mage"] = "Маг",
	["Paladin"] = "Паладин",
	["Priest"] = "Жрец",
	["Rogue"] = "Разбойник",
	["Shaman"] = "Шаман",
	["Warlock"] = "Чернокнижник",
	["Warrior"] = "Воин",
	["Death Knight"] = "Рыцарь cмерти",
	["Monk"] = "Монах",
	["Demon Hunter"] = "Охотник на демонов",
	["Evoker"] = "Пробудитель",

    -- Female Class Names --
	["DruidF"] = "Друид",
	["HunterF"] = "Охотница",
	["MageF"] = "Маг",
	["PaladinF"] = "Паладин",
	["PriestF"] = "Жрица",
	["RogueF"] = "Разбойница",
	["ShamanF"] = "Шаманка",
	["WarlockF"] = "Чернокнижница",
	["WarriorF"] = "Воин",
	["Death KnightF"] = "Рыцарь cмерти",
	["MonkF"] = "Монахиня",
	["Demon HunterF"] = "Охотница на демонов",
	["EvokerF"] = "Пробудительница",

	["Game Master"] = "ГМ",

	-- WIM.lua --
	["Toggle WIM 'On' and 'Off'."] = "Вкл/Выкл WIM",
	["Toggle Debugging Mode 'On' and 'Off'."] = "Вкл/Выкл режим отладки",

    -- Filters.lua --
	["Whispers Sent by Addons"] = "Шопот высылаемый аддонами",
	["WhisperSelect Part 1"] = "WhisperSelect Part 1",
	["Example Spam Blocker"] = "Example Spam Blocker",
	["WhisperSelect Part 2"] = "WhisperSelect Part 2",
	["Filter Name"] = "Название",
	["Filter By"] = "Фильтровать по",
	["Pattern"] = "Пример",
	["User Type"] = "Тип игрока",
	["Level"] = "Уровень",
	["Friends"] = "Друзья",
	["Guild Members"] = "Участники гильдии",
	["Party Members"] = "Участники группы",
	["Raid Members"] = "Участники рейда",
	["Cross-Realm"] = "Cross-Realm",
	["Everyone"] = "Все",
	["User must be at least level:"] = "",
	["Apply to messages sent."] = "К исходящим сообщениям",
	["Apply to messages received."] = "К входящим сообщениям",
	["Apply to:"] = "Применить к:",
	["All Classes"] = "Все классы",
	["Action to Perform:"] = "Выполняемое действие:",
	["Allow"] = "Разрешить",
	["Ignore"] = "Игнорировать",
	["Blocked"] = "Блокировать",
	["Save"] = "Сохранить",
	["Cancel"] = "Отмена",
	["Edit Filter"] = "Править фильтр",
	["Add Filter"] = "Добавить фильтр",

    -- History.lua --
	["WIM History Button"] = "Кнопка истории",
	["Click to view message history."] = "Нажмите для просмотра истории.",
	["WIM pruned %d |4message:messages; from your history."] = "WIM удалил %d |4сообщение:сообщения:сообщений; из вашей истории.",
	["History Viewer"] = "Просмотр истории",
	["Filters"] = "Фильтры",
	["Are you sure you want to delete all history saved for %s on %s?"] = "Вы действительно хотите удалить всю сохранённую историю %s на %s?",
	["Search resulted in %d |4message:messages;."] = "Результат поиска %d |4сообщение:сообщения:сообщений;.",
	["No results found!"] = "Ничего не найдено!",
	["Search"] = "Поиск",
	["Show All"] = "Показать всё",
	["Loading History"] = "Загрузка истории",
	["Chat View"] = "Вид чата",
	["Text View"] = "Вид текста",
	["BBCode"] = "BBCode",
	["WIM History Viewer can be accessed any time by typing:"] = "Доступ к просмотру истории можете получить введя команду:",
	["WIM History Viewer"] = "WIM просмотр истории",
	["Display history viewer."] = "Показывать просмотр истории",

    -- ldb.lua --
	["No New Messages"] = "Пусто",

    -- Menu.lua --
	["Whispers"] = "Сообщения",
	["Chat"] = "Чат",

    -- Negotiate.lua --
	["WIM Update Available!"] = "Доступно обновление WIMа!",

    -- ShortcutBar.lua --
	["Player Location"] = "Местонахождение персонажа",
	["Unknown"] = "Неизвестно",
	["Click to update..."] = "Кликните для обновления...",
	["Invite to Party"] = "Пригласить в группу",
	["Invite to Guild"] = "Пригласить в гильдию",
	["Add Friend"] = "Добавить",
	["Ignore Player"] = "Игнорировать персонажа",
	["Are you sure you want to\nignore %s?"] = "Вы уверены что вы хотите добавить\nперсонажа %s в черный список?",
    ["Right-Click for profile links..."] = "[Правый-Клик] - ссылка на профиль...",
    ["Profile Links"] = "Ссылка на профиль",
	["Character"] = "Персонаж",
	["Game"] = "Игра",
	["Realm"] = "Игровой мир",
	["Location"] = "Зона",
	["Copy Name"] = "Копировать имя",

    -- Tutorials.lua --
	["View Updates"] = "Просмотреть обновления",

    -- WhisperEngine.lua --
	["Whisper Received!"] = "Входящее сообщение!",
	["Recently Sent Messages"] = "Недавно отосланные сообщения",
	["Users in %s"] = "Пользователи в %s",

    -- Clear.lua --
	["You are about to clear all of WIM's history!"] = "Вы собираетесь удалить всю историю WIMа!",
	["This action will reload your user interface."] = "Данное действие перезагрузит ваш интерфейс.",
	["Do you want to continue?"] = "Вы хотите продолжить?",
	["You are about to restore WIM's filters to it's default settings!"] = "Вы собираетесь восстановить настройки фильтров WIMа на настройки по умолчанию!",
	["Usage"] = "Использование",
	["Clear various WIM data."] = "Очистка различных данных WIMа.",

    -- SlashHandler.lua --
	["WIM Slash Commands"] = "WIM слеш команды",
	["Hide or show {all, whisper, chat} windows."] = "Показать/скрыть окна {все, шёпота, чата}.",
	["To see a list of available WIM slash commands type:"] = "Для просмотра списка доступных команд введите:",
	["Display available slash commands."] = "Отображать доступные слеш команды",
	["Reload User Interface."] = "Перезагрузить интерфейс",

    -- TabHandler.lua --
	["Manipulating Tabs"] = "Управление закладками",

    -- WindowHandler.lua --
	["Window Resized!"] = "Изменён размер окна!",
	["Creating Tab Groups"] = "Создание групп закладок",
	["You can group two or many windows together by <Shift-Clicking> a window and dragging it on top of another."] = "Вы можете группировать окна воедино нажав <Shift-Клик> по окну и натаскивая его один на другого.",
	["Resizing Windows"] = "Изменение размера",
	["You can resize a window by holding <Shift> and dragging the bottom right corner of the window."] = "Вы можете изменять размер окна удерживая <Shift> перемещать нижний правый угол окна.",
	["Demo Window"] = "Демо окно",
	["<Shift-Click> to close window."] = "<Shift-Клик> для закрытия окна.",
	["Message Window Hidden"] = "Окно сообщений - скрыто",
	["Default"] = "По умолчанию",
	["%s is Away From Keyboard: %s"] = "%s отсутствует: %s",
	["%s does not wish to be disturbed: %s"] = "%s в режиме \"не беспокоить\": %s",
	["Right-Mouse Click!"] = "Кликните правой кнопкой мыши!",
	["There might be useful tools hidden under the message box. Right-Click to see them!"] = "Полезные инструменты могут быть скрыты под окном. Кликните правой кнопкой мыши чтобы увидеть их!",

    -- Options.lua --
	["Display WIM's options."] = "Отображает настройки WIMа",
	["Resetting WIM will clear all of your settings!"] = "Сброс WIMа обнулит все ваши настройки!",
	["A reset will reload your user interface."] = "Сброс приведёт к перезагрузке интерфейса.",
	["Reset all options to default."] = "Сброс всех настроек на стандартные значения.",

    -- CoreOptions --
	["Bracket names."] = "Заключать имена в скобки.",
	["Created By:"] = "Создатель:",
	["Special Thanks:"] = "Отдельно спасибо:",
	["Welcome!"] = "Добро пожаловать!",
	["Enable WIM"] = "Включить WIM",
	["Display Minimap Icon"] = "Отображать иконку у мини-карты",
	["<Right-Click> to show unread messages."] = "<Правый-Клик> открывает непрочитанные сообщения.",
	["Display Addon Compartment Icon"] = "Показывать значок панели аддонов",
	["Display Tutorials"] = "Показывать руководство",
	["Reset Tutorials"] = "Сброс руководства",
	["Credits"] = "Титры",
	["This is a long message which contains both emoticons and urls 8). WIM's home is www.WIMAddon.com."] = "Это длинное сообщение, которое содержит и смайлики и адреса/ссылки 8). Домашняя страничка WIM'а: www.WIMAddon.com.",
	["Message Formatting"] = "формат сообщения",
	["Manipulate how WIM displays messages."] = "Управление отображением сообщений WIMом",
	["Preview"] = "Пред просмотр",
	["Display Time Stamps"] = "Отображать время",
	["Display Emoticons"] = "Отображать эмоции",
	["Display URLs as Links"] = "Отображать URL-адрес как ссылку",
	["Indent long messages."] = "Делать отступ в длинных сообщениях",
	["Window Behavior"] = "Поведение окна",
	["You can control how windows behave while you are in different situations."] = "Вы можете настроить поведения окна в различных ситуациях.",
	["Intercept Slash Commands"] = "Перехватывать слеш команды",
	["Obey autofocus rules when opening frames via the menu. (autofocus if unchecked)"] = "Соблюдать правила автофокуса при открытии окон через меню. (автофокус, если не отмечено)",
	["Use the same rules for all states."] = "Использовать одинаковые правила для всех состояний",
	["Behaviors for state:"] = "Поведение для:",
	["Pop-Up window when message is sent."] = "Всплывание окна при отсылке сообщения.",
	["Pop-Up window when message is received."] = "Всплывание окна при получении сообщения.",
	["Auto focus a window when it is shown."] = "Авто-фокус окна при его появлении.",
	["Keep focus on window after sending a message."] = "Сохранить фокус на окне после отправки сообщения.",
	["Suppress messages from the default chat frame."] = "Подавлять сообщения в стандартном окне чата.",
	["Window Settings"] = "Настройки окна",
	["Some settings may be limited by certain skins."] = "Некоторые настройку будут ограничены в определённых шкурках.",
	["Default Width"] = "Стандартная ширина",
	["Default Height"] = "Стандартная высота",
	["Window Scale"] = "Масштаб окна",
	["Window Alpha"] = "Прозрачность окна",
	["Set Window Spawn Location"] = "Установка места появления окна",
	["Up"] = "Вверх",
	["Down"] = "Вниз",
	["Left"] = "Влево",
	["Right"] = "Вправо",
	["Cascade overlapping windows."] = "Каскад окон с наложением.",
	["Ignore arrow keys in message box."] = "Игнорировать кнопки передвижения в строке ввода.",
	["Allow <ESC> to hide windows."] = "Позволить скрывать окно клавишей <ESC>.",
	["Display Settings"] = "Настройки отображения",
	["Configure general window display settings."] = "Настройки отображения основного окна.",
	["Window Skin:"] = "Шкурка окна:",
	["Version"] = "Версия",
	["Color: System Messages"] = "Цвет: системных сообщений",
	["Color: Error Messages"] = "Цвет: ошибок",
	["Color: URL - Web Addresses"] = "Цвет: URL - интернет адресов",
	["Color: History Messages Sent"] = "Цвет: высылаемых сообщений в истории",
	["Color: History Messages Received"] = "Цвет: получаемых сообщений в истории",
	["Use colors suggested by skin."] = "Использовать цвета входящие в шкурку.",
	["Enable window fading effects."] = "Включить эффекты затухания окна",
	["Enable window animation effects."] = "Включить эффекты анимации окна",
	["Display item links when hovering over them."] = "Отображать ссылки предметов при зависании мышью над ними.",
	["Fonts"] = "Шрифты",
	["Configure the fonts used in WIM's message windows."] = "Настройка используемых шрифтов в окне сообщений WIMа.",
	["Font Outline"] = "Контур шрифта",
	["Thin"] = "Тонкий",
	["Thick"] = "Толстый",
	["Use font suggested by skin."] = "Использовать шрифт входящий в шкурку.",
	["Chat Font Size"] = "Размер шрифта чата",
	["Configure general display settings when dealing with whispers."] = "Настройка основного отображения когда происходит общение шепотом.",
	["Color: Messages Sent"] = "Цвет: высылаемых сообщений",
	["Color: Messages Received"] = "Цвет: получаемых сообщений",
	["Color: BNet Messages Sent"] = "Цвет: высылаемых BNet сообщений",
	["Color: BNet Messages Received"] = "Цвет: получаемых BNet сообщений",
	["Use colors suggested by skin."] = "Исп. встроенные цвета шкурки.",
	["Display user class icons and details."] = "Отображать иконку класса пользователя и другие детали.",
	["Requires who lookups."] = "Требует поиск через команду /who",
	["Display Shortcut Bar"] = "Отображать панель ярлыков",
	["Allow"] = "Разрешить",
	["Ignore"] = "Игнорировать",
	["Block"] = "Блокировать",
	["Filtering"] = "Фильтрация",
	["Filtering allows you to control which messages are handled as well as how they are handled by WIM."] = "Фильтрация позволяет вам контролировать, какие сообщения обрабатывать, а также каким образом они будут обрабатываться WIMом.",
	["Enable Filtering"] = "Включить фильтрацию",
	["Protected"] = "Под защитой",
	["Action:"] = "Действие",
	["Occurrences:"] = "Появление",
	["Delete Filter"] = "Удалить фильтр",
	["History"] = "История",
	["WIM can store conversations to be viewed at a later time."] = "WIM может хранить беседы, которые можно проссматривать в любое время.",
	["Enable History"] = "Включить историю",
	["Messages"] = "Сообщений",
	["Preview history inside message windows."] = "Пред просмотр истории в окне сообщения.",
	["Record Friends"] = "Записывать друзей",
	["Record Guild"] = "Записывать гильдию",
	["Record Everyone"] = "Записывать всех",
	["Record Chat"] = "Записывать чат",
	["Maintenance"] = "Поддержка",
	["Allowing your history logs to grow too large will affect the game's performance, therefore it is reccomended that you use the following options."] = "Позволяя вести журнал вашей истории, что может сильно повлиять на производительность вашей игры, поэтому рекомендуется использовать следующие настройки.",
	["Save a maximum number of messages per person."] = "Макс. количество сохраняемых сообщений на человека.",
	["%d |4Week:Weeks;"] = "%d |4ниделя: нидели:нидель;",
	["Automatically delete old messages."] = "Автоматически удалять старые сообщения.",
	["WIM-2-WIM is a feature which allows users with WIM to interact in ways that normal whispering can not."] = "WIM-2-WIM даёт возможность пользователям с WIM взаимодействовать таким образом, что нормальное перешептывание не может.",
	["Enable WIM-2-WIM"] = "Включить WIM-2-WIM",
	["Privacy"] = "Личное дело",
	["Restrict the data that is shared."] = "Ограничить разделение/вывод данных.",
	["Allow others to see me typing."] = "Позволить другим видеть когда вы печатаете.",
	["Allow others to see my location."] = "Позволить другим видеть ваше местоположение.",
	["Main"] = "Главное",
	["General"] = "Основное",
	["User Level"] = "Уровень игрока",
	["Windows will also be hidden when frames such as the world map are shown."] = "Окно будет также закрыто при открытии карты.",
	["Sounds"] = "Звуки",
	["Configure various sound events and how they are triggered."] = "Настройка звуковых оповещений и когда они будут проигрываться.",
	["Play sound when a whisper is received."] = "Проиграть звук при получении сообщения.",
	["Play special sound for battle.net friends."] = "Специальный звук для Battle.Net друзей.",
	["Play special sound for friends."] = "Специальный звук для друзей.",
	["Play special sound for guild members."] = "Специальный звук для членов гильдии.",
	["Play sound when a whisper is sent."] = "Проиграть звук при отправке сообщения.",
	["Allow others to see my talent spec."] = "Позволить другим видеть мои таланты.",
	["Window Strata:"] = "Слой окна",
	["Background"] = BACKGROUND,
	["Low"] = LOW,
	["Medium"] = "Средняя",
	["High"] = "Высокая",
	["Dialog"] = ENABLE_DIALOG,
	["Tooltip"] = "Подсказка",
	["Unlock from Minimap"] = "Открепить от мини-карты",
    ["Press <Tab> to advance to next tell target."] = "Нажмите <Tab> чтобы перейти к следующему собеседнику.",
    ["Force sounds when game sound is disabled."] = "Принудительно воспроизводить звук, когда игровой звук отключён.",
    ["Colorize names."] = "Окраска имён.",
    ["Clamp window to screen."] = "Фиксировать окно на экране.",
	["Group with whisper windows."] = "Групировать с окном шопота.", --??

    -- TabManagement.lua --
	["Tab Management"] = "Управление закладками",
	["Automatically manage your open windows and place them into appropriate tab groups."] = "Автоматическое управление открытыми окнами и помещение их в соответствующие вкладки групп.",
	["Automatically group whispers."] = "Автоматически группировать",
	["Place friends in their own group."] = "Помещать друзей в отдельную группу.",
	["Place guild members in their own group."] = "Помещать членов гильдии в отдельную группу.",
	["Does not apply to windows already opened."] = "Не применять если окно уже открыто.",
	["Automatically group chat windows."] = "Автоматически группировать окна чата.",

    -- Talent Specs --
	["Hybrid"] = "Гибрид",

    -- Filters.lua --
    ["Show Alert"] = "Показ уведомления",
    ["WIM has blocked a message from %s."] = "WIM заблокировал сообщение от персонажа: %s.",
    ["View Blocked Message"] = "Просмотр заблокированного сообщения",
    ["Blocked Message"] = "Заблокированное сообщение",

    -- MinimapIcon.lua
    ["Show Unread Messages"] = "Показать непрочитанные сообщения",
    ["Show All Windows"] = "Показать все окна",
    ["Hide All Windows"] = "Скрыть все окна",

    --Emoticons.lua
    ["Also"] = "Также",
    ["More"] = "Еще",
    ["Emoticons"] = "Смайлики",

	--Expose.lua
    ["Your conversations have been hidden in order to clear your screen while in combat. To disable this feature type"] = "Ваши диалоги были скрыты, чтобы очистить экран в то время как в находитесь в бою. Чтобы отключить эту функцию введите",
    ["Expose"] = "Экспонировка",
    ["Expose is a Mac OS X inspired feature which enables you to quickly clear your screen of windows and then restore them back to their original position."] = "Экспонировка является инспирической особенностью Mac OS X, которая позволяет быстро очистить экран от окон, а затем восстановить их обратно в их первоначальное положение.",
    ["Auto hide/restore windows during combat."] = "Авто скрывать/открывать окона во время боя.",
    ["Border Size"] = "Размер рамки",
    ["Only while in an instance."] = "Только в подземельях.",
    ["Show Border"] = "Показать рамку",
    ["Animation Direction:"] = "Направления анимации:",
    ["Delay if I am typing a message."] = "Откладывать, если я печатаю сообщение.",

    --ChatEngine.lua
    ["WIM will manage this chat type within its own message windows."] = "WIM будет управлять данным типом чата в рамках своего окна сообщений.",
    ["Include emotes."] = "Включать эмоции.",
    ["Show Minimap Alerts"] = "Оповещения у мини-карты",
    ["Never pop-up on my screen."] = "Никогда не всплывать на маём экране.",
    ["Never suppress messages."] = "Никогда не подавлять сообщения.",
    ["Have WIM monitor this channel."] = "Позволить WIMу следить за данным каналом.",
    ["Never Pop"] = "Не всплывать",
    ["Never have this window pop-up on my screen."] = "Никогда не позволять всплывать данному окну на моём экране.",
    ["Never Suppress"] = "Не подавлять",
    ["Never suppress messages from the default chat frame."] = "Никогда не подавлять сообщения с стандартного окна чата.",
    ["Show unread message alert on minimap."] = "Показывать у мини-карты оповещение об непрочитанных сообщениях.",
    ["No History"] = "Без истории",
    ["Do not record history for this channel."] = "Не записывать историю для данного канала.",
    ["World Chat"] = "Мировой чат",
    ["Custom Chat"] = "Свой чат",
    ["Community Chat"] = "Чат сообщества",
    ["Community Chats"] = "Чаты сообщества",
    ["Chat"] = "Чат",
    ["Play special sound for %s."] = "Проиграть особый звук для %s.",
    ["Play sound when a message is received."] = "Проиграть звук при получении сообщения.",
    ["Play sound when a message is sent."] = "Проиграть звук при отправке сообщения.",
    ["Do not play sounds for this channel."] = "Не проигрывать звук для данного канала.",
    ["No Sound"] = "Без звука",
	["Sensitivity"] = "Чувствительность",
    ["Enable WorldFrame Click Detection."] = "Включить обнаружение клика на мировом фрейме.",

    --OffScreenTracker.lua
    ["WIM Window Off Screen"] = "Окно WIM за экраном",
    ["Click to reposition."] = "Кликните для смены расположения.",

	-- Whisper Mode Warnings
	["Whisper Mode: In-line"] = "Режим шёпота: встроенный",
	["Set whispers to In-line"] = "Установить шёпот во встроенный режим",
	["Message suppression requires whispers to be set to 'In-line'."] = "Для подавления сообщений шёпот должен быть установлен в режим «встроенный».",
	["It is recommended for whispers to be set to in-line in order to handle their behavior properly."] = "Рекомендуется установить шёпот во встроенный режим для корректной обработки.",

	-- Skins --
	["Blue"] = "Синий",
	["Green"] = "Зелёный",
	["Red"] = "Красный",
	["Yellow"] = "Жёлтый",

	-- Battle.net friend consolidation (History Viewer)
	["Battle.net Friends"] = "Друзья Battle.net",
	["Are you sure you want to delete ALL history saved with %s, across every realm and every character on this account?"] = "Вы действительно хотите удалить ВСЮ историю, сохранённую с %s, на всех реалмах и у всех персонажей этой учётной записи?",

	-- Per-date deletion from the History Viewer filter list
	["Are you sure you want to delete the %s history with %s across every realm and character on this account?"] = "Вы действительно хотите удалить историю за %s с %s на всех реалмах и у всех персонажей этой учётной записи?",
	["Are you sure you want to delete the %s history for %s across every character on %s?"] = "Вы действительно хотите удалить историю за %s для %s у всех персонажей на %s?",
	["Are you sure you want to delete the %s history for %s on %s?"] = "Вы действительно хотите удалить историю за %s для %s на %s?",


	-- Modern options panel --
	["Use modern options UI"] = "Использовать современный интерфейс настроек",
	["Classic Options"] = "Классические настройки",
	["Open"] = "Открыть",
	["Open the classic WIM options window."] = "Открывает классическое окно настроек WIM.",
	["Choose the options style: /wim style [classic|modern]."] = "Выберите стиль настроек: /wim style [classic|modern].",
	["When enabled, WIM's Options entry points (minimap menu, key binding, /wim) open this panel instead of the classic WIM options window."] = "Если включено, точки входа в настройки WIM (меню миникарты, привязка клавиши, /wim) открывают эту панель вместо классического окна настроек WIM.",
	["While a modern-only skin (such as WIM Modern) is selected, this option is enforced: those skins are configured through this panel only."] = "Пока выбран исключительно современный облик (например, WIM Modern), этот параметр принудительно включён: такие облики настраиваются только через эту панель.",

	-- Modern skin styling --
	["Modern Skin"] = "Современный облик",
	["These settings style WIM's modern-only skins (such as WIM Modern), which are built from the game's own interface art. They shape the History Viewer and the chat windows, and are available only while a modern-only skin is selected under General > Display Settings; with a classic skin active they are greyed out."] = "Эти параметры задают оформление исключительно современных обликов WIM (например, WIM Modern), построенных на элементах интерфейса самой игры. Они определяют вид окна просмотра истории и окон чата и доступны только пока выбран исключительно современный облик в разделе «Общие > Настройки отображения»; при активном классическом облике они неактивны.",
	["Disabled while a modern-only skin (such as WIM Modern) is selected: those skins carry settings the classic window has no controls for."] = "Недоступно, пока выбран исключительно современный облик (например, WIM Modern): такие облики содержат параметры, для которых у классического окна нет элементов управления.",
	["Frame background"] = "Фон рамки",
	["Message area background"] = "Фон области сообщений",
	["Chat history background"] = "Фон истории чата",
	["Selection panels background"] = "Фон панелей выбора",
	["Window frame background"] = "Фон рамки окна",
	["None (game default)"] = "Нет (как в игре)",
	["Panels see through to the game world"] = "Панели прозрачны для игрового мира",
	["Window sees through to the game world"] = "Окно прозрачно для игрового мира",
	["Draws the frame background only around the panels, so a clear panel background (None or Transparent) shows the game world behind the viewer instead of the frame fill."] = "Рисует фон рамки только вокруг панелей, поэтому при прозрачном фоне панелей («Нет» или «Прозрачный») за окном просмотра виден игровой мир вместо заливки рамки.",
	["Draws the window frame background only around the message area, so a clear message area background (None or Transparent) shows the game world behind the window."] = "Рисует фон рамки окна только вокруг области сообщений, поэтому при прозрачном фоне области сообщений («Нет» или «Прозрачный») за окном виден игровой мир.",

	-- Roleplay profiles (Total RP 3 / Mary Sue Protocol) --
	["Roleplay Profiles"] = "Ролевые профили",
	["Enable roleplay profile integration"] = "Включить интеграцию ролевых профилей",
	["Whisper windows show roleplay profile fields from Total RP 3 or any Mary Sue Protocol addon, and gain an Open RP Profile button on their shortcut bar that opens the partner's profile in the installed viewer."] = "Окна шёпота показывают поля ролевого профиля из Total RP 3 или любого аддона с протоколом Mary Sue, а также получают кнопку «Открыть RP-профиль» на панели ярлыков, которая открывает профиль собеседника в установленном просмотрщике.",
	["Open RP Profile"] = "Открыть RP-профиль",
	["Displayed profile fields"] = "Отображаемые поля профиля",
	["Whisper windows show the selected fields from the partner's Total RP 3 or Mary Sue Protocol profile. Fields left unselected -- or without profile data -- keep the standard display."] = "Окна шёпота показывают выбранные поля из профиля Total RP 3 или Mary Sue собеседника. Невыбранные поля — или поля без данных профиля — сохраняют обычный вид.",
	["First Name"] = "Имя",
	["Last Name"] = "Фамилия",
	["Title"] = "Титул",
	["Full Title"] = "Полный титул",
	["Race"] = "Раса",
	["Class"] = "Класс",
	["Portrait"] = "Портрет",
	["Name & Class Color"] = "Цвет имени и класса",
	["The profile's first name, shown as the window's name text."] = "Имя из профиля, отображаемое как имя окна.",
	["The profile's last name, shown as the window's name text."] = "Фамилия из профиля, отображаемая как имя окна.",
	["The short title, shown on the window's details line."] = "Короткий титул, отображаемый в строке деталей окна.",
	["The long title, shown on the window's details line and portrait tooltip."] = "Полный титул, отображаемый в строке деталей окна и во всплывающей подсказке портрета.",
	["The custom race, replacing the character's race on the details line."] = "Особая раса, заменяющая расу персонажа в строке деталей.",
	["The custom class, replacing the character's class on the details line."] = "Особый класс, заменяющий класс персонажа в строке деталей.",
	["The profile's icon, replacing the class icon."] = "Значок профиля, заменяющий значок класса.",
	["The profile's custom color, applied to the window's name text and to the class on the details line."] = "Особый цвет профиля, применяемый к имени окна и к классу в строке деталей.",
	["Apply filter to character menus"] = "Применять фильтр к меню персонажей",

	-- History Viewer filters --
	["No Filter"] = "Без фильтра",
	["Relative Dates"] = "Относительные даты",
	["%d or more"] = "%d и более",
	["Fewer than %d"] = "Меньше %d",
	["Results Filtered"] = "Результаты отфильтрованы",
	["-- Results Filtered --"] = "-- Результаты отфильтрованы --",
	["Results are hidden by the active filter. Click to open the Filters menu."] = "Результаты скрыты активным фильтром. Нажмите, чтобы открыть меню фильтров.",
	["Click to change how history is filtered."] = "Нажмите, чтобы изменить фильтрацию истории.",
	["Click to open the Filters menu."] = "Нажмите, чтобы открыть меню фильтров.",
	["Clicking the %s button on the message window will show that user's history in WIM's History Viewer."] = "Нажатие кнопки %s в окне сообщения покажет историю этого игрока в окне просмотра истории WIM.",

	-- Message input & formatting --
	["Wrap the message being typed"] = "Переносить набираемое сообщение",
	["Limit wrapped lines"] = "Ограничить число строк переноса",
	["Visible input lines"] = "Видимые строки ввода",
	["Caps how far the input field grows; past the limit the message scrolls inside it."] = "Ограничивает рост поля ввода; сверх лимита сообщение прокручивается внутри него.",
	["The most lines the input field grows to before the message scrolls inside it."] = "Максимальное число строк, до которых растёт поле ввода, прежде чем сообщение начнёт прокручиваться внутри.",
	["The input field wraps long messages onto multiple lines, growing downward with the message instead of scrolling it on one line."] = "Поле ввода переносит длинные сообщения на несколько строк, увеличиваясь вниз вместе с сообщением, вместо прокрутки в одной строке.",
	["Timestamp Format"] = "Формат времени",
	["Bracket Style"] = "Стиль скобок",
	["Colors"] = "Цвета",
	["Sound"] = "Звук",

	-- Chat type options --
	["Chat Windows"] = "Окна чата",
	["Monitor"] = "Отслеживать",
	["Record"] = "Записывать",
	["Minimap Alerts"] = "Оповещения на миникарте",

	-- Help, bug reports & links --
	["Found a bug?"] = "Нашли ошибку?",
	["Report a Bug"] = "Сообщить об ошибке",
	["Reports are welcome! Click below and follow the instructions in the bug report template."] = "Сообщения об ошибках приветствуются! Нажмите ниже и следуйте инструкциям в шаблоне отчёта.",
	["Visit us on GitHub"] = "Заходите к нам на GitHub",
	["Click to copy the link."] = "Нажмите, чтобы скопировать ссылку.",
	["Press Ctrl+C to copy the link, then open it in your browser."] = "Нажмите Ctrl+C, чтобы скопировать ссылку, и откройте её в браузере.",

	-- Debugging & development slash commands --
	["Clear the captured debug log."] = "Очистить захваченный журнал отладки.",
	["Set debugging level: /wim debug [0|1|2]. 2 adds verbose chat event tracing."] = "Задаёт уровень отладки: /wim debug [0|1|2]. 2 включает подробную трассировку событий чата.",
	["Snapshot the next modern context menu while it is open."] = "Делает снимок следующего современного контекстного меню, пока оно открыто.",
	["Snapshot UI widget state for skin development: /wim snap all | <Frame.Dot.Path> (bare /wim snap lists the arguments)."] = "Сохраняет состояние UI-виджетов для разработки обликов: /wim snap all | <Frame.Dot.Path> (без аргументов /wim snap выводит список вариантов).",

	-- Tutorials & notices --
	["WIM is currently running. To access WIM's wide array of options type:"] = "WIM сейчас запущен. Чтобы получить доступ ко всем настройкам WIM, введите:",
	["WIM's message window has been hidden to WIM's Minimap Icon. If you want to end a conversation, you may do so by <Shift-Clicking> the close button."] = "Окно сообщения скрыто в значок на миникарте WIM. Чтобы завершить беседу, <Shift-щёлкните> кнопку закрытия.",
	["If you want all windows to be this size, you can set the default window size within WIM's options."] = "Если хотите, чтобы все окна были такого размера, задайте размер окна по умолчанию в настройках WIM.",
	["You can <Shift-Click> a tab and drag it out into it's own window."] = "<Shift-щелчок> по вкладке позволяет перетащить её в отдельное окно.",
	["You received a whisper which was hidden due to your current activity. You can change how whispers behave in WIM's options by typing"] = "Вы получили шёпот, скрытый из-за вашей текущей активности. Изменить поведение шёпота можно в настройках WIM, введя",
	["Sets the game's Social > Whisper Mode setting to In-line. Without it, suppressed whispers would vanish into a popout chat tab."] = "Устанавливает игровой параметр «Социальное > Режим шёпота» в значение «Встроенный». Иначе подавленные шёпоты исчезнут в отдельной вкладке чата.",

	-- Community channel maintenance --
	["Toggle the experimental community channel re-add repair (mutates chat window channels)."] = "Включает экспериментальное исправление повторного присоединения каналов сообщества (изменяет каналы окон чата).",
	["Toggle whether WIM focuses community streams at login."] = "Определяет, фокусирует ли WIM потоки сообщества при входе.",

	-- Misc --
	["Age"] = "Возраст",
	["Users in %s"] = "Игроки в %s",

	-- History Viewer filter modes --
	["Sent by Me"] = "Отправлено мной",
	["Sent by Them"] = "Отправлено ими",
	["Active Days"] = "Активные дни",
	["Last 1 Day"] = "Последний день",
	["Last 7 Days"] = "Последние 7 дней",
	["Last 30 Days"] = "Последние 30 дней",
	["Last 90 Days"] = "Последние 90 дней",


	-- Chrome background names --
	["None (fully clear)"] = "Нет (полностью прозрачный)",
	["Transparent"] = "Прозрачный",
	["Rock"] = "Скала",
	["Marble"] = "Мрамор",
	["Dark Marble"] = "Тёмный мрамор",
	["Bank"] = "Банк",
	["Guild Vault"] = "Банк гильдии",
	["Dark Sandstone"] = "Тёмный песчаник",
	["Parchment (Tileable)"] = "Пергамент (плитка)",
	["Quest Parchment"] = "Пергамент задания",
	["Raid Frame"] = "Рамка рейда",
	["Destiny"] = "Судьба",
	["Stationery (Auction)"] = "Почтовая бумага (аукцион)",
	["Stationery (Illustrated)"] = "Почтовая бумага (с рисунком)",
	["Stationery (Orgrimmar)"] = "Почтовая бумага (Оргриммар)",
	["Stationery (Thunder Bluff)"] = "Почтовая бумага (Громовой утёс)",
	["Stationery (Undercity)"] = "Почтовая бумага (Подгород)",
	["Stationery (Plain)"] = "Почтовая бумага (простая)",
	["World Map 1"] = "Карта мира 1",
	["World Map 2"] = "Карта мира 2",
	["Achievement Stats"] = "Статистика достижений",
	["Adventure Map Parchment"] = "Пергамент карты приключений",
	["Collections"] = "Коллекции",
	["Frame: Alliance"] = "Рамка: Альянс",
	["Frame: Horde"] = "Рамка: Орда",
	["Frame: Neutral"] = "Рамка: Нейтральный",
	["Frame: Marine"] = "Рамка: Морская",
	["Frame: Mechagon"] = "Рамка: Мехагон",
	["Frame: Kyrian"] = "Рамка: Кирии",
	["Frame: Necrolord"] = "Рамка: Некролорды",
	["Frame: Night Fae"] = "Рамка: Ночная Фея",
	["Frame: Venthyr"] = "Рамка: Вентир",
	["Frame: Oribos"] = "Рамка: Орибос",
	["Frame: Dragonflight"] = "Рамка: Dragonflight",
	["Frame: The War Within"] = "Рамка: The War Within",
	["Class Hall"] = "Оплот класса",
	["Class Hall (Internal)"] = "Оплот класса (внутренний)",
	["Garrison Landing Page"] = "Страница высадки гарнизона",
	["Garrison Mission"] = "Задание гарнизона",
	["Ship Mission Parchment"] = "Пергамент морских заданий",
	["Garrison UI"] = "Интерфейс гарнизона",
	["Garrison UI 2"] = "Интерфейс гарнизона 2",
	["Credits: Classic"] = "Титры: Classic",
	["Credits: Burning Crusade"] = "Титры: Burning Crusade",
	["Credits: Wrath"] = "Титры: Wrath",
	["Credits: Cataclysm"] = "Титры: Cataclysm",
	["Credits: Mists of Pandaria"] = "Титры: Mists of Pandaria",
	["Credits: Warlords"] = "Титры: Warlords",
	["Credits: Legion"] = "Титры: Legion",
	["Credits: Battle for Azeroth"] = "Титры: Battle for Azeroth",


	-- Skin & options style notices --
	["WIM: the selected skin (%s) is configured through the modern options UI; the classic window is unavailable while it is active."] = "WIM: выбранный облик (%s) настраивается через современный интерфейс настроек; классическое окно недоступно, пока он активен.",
	["WIM: the selected skin (%s) requires the modern options UI; switch to another skin first."] = "WIM: выбранный облик (%s) требует современный интерфейс настроек; сначала переключитесь на другой облик.",
	["WIM options style: Modern (native Options > AddOns)."] = "Стиль настроек WIM: современный (в настройках игры, раздел «Аддоны»).",
	["WIM options style: Classic (WIM window)."] = "Стиль настроек WIM: классический (окно WIM).",

});
