--[[
    Update:2010/07/04
    Language Localization: zhTW
    Translated by: Junxian <junxian1121@hotmail.com>
]]

WIM.AddLocale("zhTW", {
    ["WIM (WoW Instant Messenger)"] = "WIM （魔獸世界即時通）",
    ["_Description"] = "WIM 的設計是為了讓你在魔獸世界中與人交談時有更親切的介面，在這個視窗中您可以自訂所有的設定。若您有任何的問題，歡迎各位到官方網頁提供意見。\n網址：http://www.WIMAddon.com",

    ["_DemoText"] = "這個視窗可以設定對話視窗出現的預設位置。您可以將這個視窗拖曳到您想要的位置，當您關閉這個視窗的時候，所有的設定將被自動記錄下來。",

    ["_DateFormat"] = "%Y/%m/%d",

    ["Yes"] = "是",
    ["No"] = "否",
    ["None"] = "無",
    ["Cancel"] = "取消",
    ["Unknown"] = "未知",
    ["Click to update..."] = "點擊更新……",
    ["Usage"] = "使用",

    ["state_resting"] = "休息",
    ["state_combat"] = "戰鬥",
    ["state_pvp"] = "PVP",
    ["state_arena"] = "競技場",
    ["state_party"] = "組隊",
    ["state_raid"] = "團隊",
    ["state_other"] = "一般（其他）",

    ["Options"] = "選項",

    ["Up"] = "上",
    ["Down"] = "下",
    ["Left"] = "左",
    ["Right"] = "右",
    ["Ignore"] = "忽略",
    ["Block"] = "封鎖",
    ["Enable WIM"] = "開啟 WIM",

    ["Enable"] = "開啟",
    ["Disable"] = "關閉",
    ["Enable window fading effects."] = "開啟視窗淡化效果",

    ["General"] = "一般",
    ["History"] = "聊天記錄",
    ["Filters"] = "過濾條件",

    ["Sort tabs by:"] = "依照下列規則切換標籤",
    ["Window Created"] = "最先密你的",
    ["Last Activity"] = "最後密你的",
    ["Alphabetical"] = "字母順序",

    -- Class Names --
    ["Druid"] = "德魯伊",
    ["Hunter"] = "獵人",
    ["Mage"] = "法師",
    ["Paladin"] = "聖騎士",
    ["Priest"] = "牧師",
    ["Rogue"] = "盜賊",
    ["Shaman"] = "薩滿",
    ["Warlock"] = "術士",
    ["Warrior"] = "戰士",
    ["Death Knight"] = "死亡騎士",
    ["Monk"] = "武僧",
    ["Demon Hunter"] = "惡魔獵人",
    ["Evoker"] = "喚魔師",

    -- Female Class Names --
    ["DruidF"] = "德魯伊",
    ["HunterF"] = "獵人",
    ["MageF"] = "法師",
    ["PaladinF"] = "聖騎士",
    ["PriestF"] = "牧師",
    ["RogueF"] = "盜賊",
    ["ShamanF"] = "薩滿",
    ["WarlockF"] = "術士",
    ["WarriorF"] = "戰士",
    ["Death KnightF"] = "死亡騎士",
    ["MonkF"] = "武僧",
    ["Demon HunterF"] = "惡魔獵人",
    ["EvokerF"] = "喚魔師",

    ["Game Master"] = "遊戲管理者",

    -- WIM.lua --
    ["Toggle WIM 'On' and 'Off'."] = "開啟/關閉 WIM",
    ["Toggle Debugging Mode 'On' and 'Off'."] = "開啟/關閉 Debugging 模式",

    -- Filters.lua --
    ["Whispers Sent by Addons"] = "由插件所發出的密語",
    ["WhisperSelect Part 1"] = "密語選擇 1",
    ["Example Spam Blocker"] = "阻擋的訊息範例",
    ["WhisperSelect Part 2"] = "密語選擇 2",
    ["Filter Name"] = "過濾名字",
    ["Filter By"] = "過濾條件",
    ["Pattern"] = "模式",
    ["User Type"] = "玩家狀況",
    ["Level"] = "等級",
    ["Friends"] = "好友",
    ["Guild Members"] = "公會成員",
    ["Party Members"] = "隊伍成員",
    ["Raid Members"] = "團隊成員",
    ["Cross-Realm"] = "敵對陣營",
    ["Everyone"] = "所有人",
    ["User must be at least level:"] = "使用者最低等級:",
    ["Apply to messages received."] = "套用到接收訊息規則",
    ["Apply to messages sent."] = "套用到傳送訊息規則",
    ["Apply to:"] = "套用至：",
    ["All Classes"] = "所有職業",
    ["Action to Perform:"] = "執行動作:",
    ["Allow"] = "允許",
    ["Ignore"] = "忽略",
    ["Blocked"] = "封鎖",
    ["Save"] = "儲存",
    ["Cancel"] = "取消",
    ["Edit Filter"] = "編輯過濾條件",
    ["Add Filter"] = "增加過濾條件",

    -- History.lua --
    ["WIM History Button"] = "WIM 對話記錄按鈕",
    ["Click to view message history."] = "檢視歷史記錄",
    ["WIM pruned %d |4message:messages; from your history."] = "WIM 刪除 %d 消息從你的歷史記錄",
    ["History Viewer"] = "對話記錄檢視",
    ["Filters"] = "過濾器",
    ["Are you sure you want to delete all history saved for %s on %s?"] = "您確定要刪除所有 %s 在 %s 儲存的記錄？",
    ["Search resulted in %d |4message:messages;."] = "搜尋結果於 %d 消息",
    ["No results found!"] = "沒有發現符合的條件！",
    ["Search"] = "搜尋",
    ["Show All"] = "顯示全部",
    ["Loading History"] = "載入對話記錄",
    ["Chat View"] = "檢視對話",
    ["Text View"] = "檢視文字",
    ["BBCode"] = "BBCode",
    ["WIM History Viewer can be accessed any time by typing:"] = "WIM 對話記錄檢視可以隨時透過下列指令開啟:",
    ["WIM History Viewer"] = "檢視 WIM 對話記錄",
    ["Display history viewer."] = "顯示對話記錄",

    -- ldb.lua --
    ["No New Messages"] = "沒有新的訊息",

    -- Menu.lua --
    ["Whispers"] = "密語",
    ["Chat"] = "聊天訊息",

    -- Negotiate.lua --
    ["WIM Update Available!"] = "WIM 已有新的更新！",

    -- ShortcutBar.lua --
    ["Location"] = "玩家位置",
    ["Character"] = "角色",
    ["Game"] = "遊戲",
    ["Realm"] = "伺服器",
    ["Player Location"] = "玩家位置",
    ["Unknown"] = "未知",
    ["Click to update..."] = "點擊更新資訊……",
    ["Invite to Party"] = "組隊邀請",
    ["Invite to Guild"] = "公會邀請",
    ["Add Friend"] = "添加好友",
    ["Ignore Player"] = "忽略玩家",
    ["Are you sure you want to\nignore %s?"] = "您確定您要忽略 %s",
    ["Right-Click for profile links..."] ="右鍵點擊 查看英雄榜",
    ["Profile Links"] = "查看英雄榜",
	["Copy Name"] = "複製名稱",

    -- Tutorials.lua --
    ["View Updates"] = "檢視更新",

    -- WhisperEngine.lua --
    ["Whisper Received!"] = "收到密語！",
    ["Include sent messages in /REPLY."] = "在/REPLY中包含已發送的訊息。",
    ["Recently Sent Messages"] = "最近傳送的訊息",
    ["Users in %s"] = "%s中的用戶",

    -- Clear.lua --
    ["You are about to clear all of WIM's history!"] = "你即將刪除所有的 WIM 對話記錄",
    ["This action will reload your user interface."] = "這個動作將重新載入你的使用者介面",
    ["Do you want to continue?"] = "你確定要繼續嗎?",
    ["You are about to restore WIM's filters to it's default settings!"] = "你即將把 WIM 的過濾選項恢復成預設值！",
    ["Usage"] = "使用",
    ["Clear various WIM data."] = "清除所有 WIM 資料",

    -- SlashHandler.lua --
    ["WIM Slash Commands"] = "WIM 指令",
    ["Hide or show {all, whisper, chat} windows."] = "隱藏或顯示{所有、密語、聊天}視窗。",
    ["To see a list of available WIM slash commands type:"] = "顯示可用的 WIM 指令：",
    ["Display available slash commands."] = "顯示可用的 WIM 指令",
    ["Reload User Interface."] = "重新載入使用者介面",

    -- TabHandler.lua --
    ["Manipulating Tabs"] = "操作群組標籤",

    -- WindowHandler.lua --
    ["Window Resized!"] = "視窗尺寸已改變",
    ["Creating Tab Groups"] = "建立群組標籤",
    ["You can group two or many windows together by <Shift-Clicking> a window and dragging it on top of another."] = "您可以透過 <Shift-左鍵> 點擊一個視窗後，跟其他視窗拖曳在一起，將多個視窗合併成一個",
    ["Resizing Windows"] = "變更視窗尺寸",
    ["You can resize a window by holding <Shift> and dragging the bottom right corner of the window."] = "您可以透過按著 <Shift> 鍵並拖曳視窗右下角來變更視窗大小",
    ["Demo Window"] = "視窗範例",
    ["<Shift-Click> to close window."] = "<Shift-左鍵> 關閉視窗",
    ["Message Window Hidden"] = "隱藏訊息視窗",
    ["Default"] = "預設",
    ["%s is Away From Keyboard: %s"] = "%s 目前暫離：%s",
    ["%s does not wish to be disturbed: %s"] = "%s 目前不願被打擾：%s",
    ["Right-Mouse Click!"] = "滑鼠 右鍵點擊！",
    ["There might be useful tools hidden under the message box. Right-Click to see them!"] = "有可用的工具被隱藏在訊息欄下方，請按滑鼠右鍵開啟",

    -- Options.lua --
    ["Display WIM's options."] = "顯示 WIM 設定選單",
    ["Resetting WIM will clear all of your settings!"] = "重設 WIM 將會清除您所有的設定！",
    ["A reset will reload your user interface."] = "重設後將重新載入您的使用者介面。",
    ["Reset all options to default."] = "將所有設定恢復為預設值",

    -- CoreOptions --
    ["Created By:"] = "作者：",
    ["Special Thanks:"] = "特別感謝：",
    ["Welcome!"] = "歡迎！",
    ["Enable WIM"] = "啟用 WIM",
    ["Display Minimap Icon"] = "顯示小地圖按鈕",
    ["<Right-Click> to show unread messages."] = "<右鍵> 顯示未讀密語",
	["Display Addon Compartment Icon"] = "顯示插件隔間圖示",
    ["Display Tutorials"] = "顯示教學",
    ["Reset Tutorials"] = "重設教學",
    ["Credits"] = "榮譽",
    ["This is a long message which contains both emoticons and urls 8). WIM's home is www.WIMAddon.com."] = "這一段很長的訊息是給你觀看設定後的顯示效果用的。 其中包含網址連接與心情符號 8)。 我們的網址是 www.WIMAddon.com",
    ["Message Formatting"] = "訊息格式",
    ["Manipulate how WIM displays messages."] = "設定 WIM 如何顯示訊息格式",
    ["Preview"] = "預覽",
    ["Display Time Stamps"] = "顯示時間戳",
    ["Display Emoticons"] = "顯示心情圖示",
    ["Display URLs as Links"] = "顯示網址連結",
    ["Indent long messages."] = "縮排長訊息",
    ["Window Behavior"] = "視窗的動作",
    ["You can control how windows behave while you are in different situations."] = "您可以設定訊息視窗在您不同的狀態下的動作。",
    ["Intercept Slash Commands"] = "攔截斜線指令",
    ["Use the same rules for all states."] = "所有的狀態下都採用相同規則",
    ["Behaviors for state:"] = "此行為套用到下列狀態：",
    ["Pop-Up window when message is sent."] = "當送出密語時彈出對話視窗",
    ["Pop-Up window when message is received."] = "當收到密語時彈出對話視窗",
    ["Auto focus a window when it is shown."] = "當視窗彈出時自動獲得焦點",
    ["Keep focus on window after sending a message."] = "發送訊息後視窗保持獲得焦點狀態",
    ["Obey autofocus rules when opening frames via the menu. (autofocus if unchecked)"] = "從選單開啟視窗時遵守自動對焦規則。（取消選取將自動對焦。）",
    ["Suppress messages from the default chat frame."] = "過濾系統內建對話框中的密語訊息",
    ["Window Settings"] = "視窗設定",
    ["Some settings may be limited by certain skins."] = "部份設定將會因為套用的佈景受到限制",
    ["Default Width"] = "預設寬度",
    ["Default Height"] = "預設高度",
    ["Window Scale"] = "視窗縮放",
    ["Window Alpha"] = "視窗透明度",
    ["Set Window Spawn Location"] = "設定視窗出現位置",
    ["Up"] = "上",
    ["Down"] = "下",
    ["Left"] = "左",
    ["Right"] = "右",
    ["Cascade overlapping windows."] = "視窗重疊",
    ["Ignore arrow keys in message box."] = "在對話視窗中不使用方向鍵",
    ["Allow <ESC> to hide windows."] = "按下 <Esc> 隱藏所有對話視窗",
    ["Display Settings"] = "顯示設定",
    ["Configure general window display settings."] = "設定對話視窗顯示細節",
    ["Window Skin:"] = "視窗面版",
    ["Version"] = "版本",
    ["Color: System Messages"] = "顏色：系統訊息",
    ["Color: Error Messages"] = "顏色：錯誤訊息",
    ["Color: URL - Web Addresses"] = "顏色：網址連結",
    ["Color: History Messages Sent"] = "顏色：對話記錄-送出",
    ["Color: History Messages Received"] = "顏色：對話記錄-收到",
    ["Use colors suggested by skin."] = "使用面版建議色彩",
    ["Enable window fading effects."] = "開啟視窗淡化效果",
    ["Enable window animation effects."] = "開啟視窗動態效果",
    ["Display item links when hovering over them."] = "當滑鼠移至物品連結上時，直接顯示物品說明",
    ["Fonts"] = "字型",
    ["Configure the fonts used in WIM's message windows."] = "設定 WIM 訊息視窗中的字型",
    ["Font Outline"] = "文字描邊",
    ["Thin"] = "細",
    ["Thick"] = "粗",
    ["Use font suggested by skin."] = "面版建議使用的字型",
    ["Chat Font Size"] = "對話文字大小",
    ["Configure general display settings when dealing with whispers."] = "設定當密語出現時的顯示設定",
    ["Color: Messages Sent"] = "顏色：已傳送密語",
    ["Color: Messages Received"] = "顏色：已接收密語",
    ["Color: BNet Messages Sent"] = "顏色：已傳送 BNet 密語",
    ["Color: BNet Messages Received"] ="顏色：已接收 BNet 密語",

    ["Use colors suggested by skin."] = "使用佈景主題建議",
    ["Display user class icons and details."] = "顯示對方職業圖示與資訊",
    ["Requires who lookups."] = "需要用到查詢功能",
    ["Display Shortcut Bar"] = "顯示功能選單",
    ["Allow"] = "允許",
    ["Ignore"] = "忽略",
    ["Block"] = "封鎖",
    ["Filtering"] = "過濾",
    ["Filtering allows you to control which messages are handled as well as how they are handled by WIM."] = "在此您可以設定 WIM 的過濾機制",
    ["Enable Filtering"] = "開啟過濾功能",
    ["Protected"] = "已保護",
    ["Action:"] = "動作：",
    ["Occurrences:"] = "發生次數：",
    ["Delete Filter"] = "刪除過濾",
    ["History"] = "訊息記錄",
    ["WIM can store conversations to be viewed at a later time."] = "WIM 可以儲存對話記錄",
    ["Enable History"] = "開啟訊息記錄",
    ["Messages"] = " 則訊息",
    ["Preview history inside message windows."] = "在對話視窗中顯示的訊息數量",
    ["Record Friends"] = "記錄好友",
    ["Record Guild"] = "記錄公會",
    ["Record Everyone"] = "記錄所有人",
    ["Record Chat"] = "記錄對話",
    ["Maintenance"] = "維護",
    ["Allowing your history logs to grow too large will affect the game's performance, therefore it is reccomended that you use the following options."] = "當訊息記錄檔太大時，會影響到遊戲的效能。因此我們建議您採用下列的步驟。",
    ["Save a maximum number of messages per person."] = "每個對象的最大密語儲存數",
    ["%d |4Week:Weeks;"] = "%d 週",
    ["Automatically delete old messages."] = "自動清除舊訊息",
    ["WIM-2-WIM is a feature which allows users with WIM to interact in ways that normal whispering can not."] = "WIM-2-WIM 是一個允許不同使用者的WIM彼此通訊的功能。它可以辦到密語系統無法辦到的事情。",
    ["Enable WIM-2-WIM"] = "開啟 WIM-2-WIM",
    ["Privacy"] = "隱私設定",
    ["Restrict the data that is shared."] = "限制分享的資訊",
    ["Allow others to see me typing."] = "讓其他人知道我正在輸入密語",
    ["Allow others to see my location."] = "讓其他人知道我的位置",
    ["Main"] = "主選單",
    ["General"] = "一般功能",
    ["User Level"] = "玩家等級",
    ["Windows will also be hidden when frames such as the world map are shown."] = "當開啟世界地圖時，對話視窗隱藏",
    ["Sounds"] = "音效",
    ["Configure various sound events and how they are triggered."] = "設定此插件的音效功能",
    ["Play sound when a whisper is received."] = "當收到密語時撥放音效",
    ["Play special sound for friends."] = "設定好友音效",
    ["Play special sound for guild members."] = "設定公會成員音效",
    ["Play sound when a whisper is sent."] = "當送出密語時撥放音效",
    ["Force sounds when game sound is disabled."] = "遊戲音效關閉時仍強制播放音效。",
    ["Allow others to see my talent spec."] = "讓其他人看見我的天賦資訊",
    ["Play special sound for battle.net friends."] = "設定 battle.net 好友音效",
    ["Window Strata:"] = "視窗層級：",
	["Background"] = BACKGROUND,
	["Low"] = LOW,
	["Medium"] = "中",
	["High"] = "高",
	["Dialog"] = ENABLE_DIALOG,
	["Tooltip"] = "提示",
    ["Unlock from Minimap"] = "解鎖小地圖按鈕",
    ["Press <Tab> to advance to next tell target."] = "按下 <Tab> 切換到下一個對話欄",
    ["Colorize names."] = "名字上色",
    ["Bracket names."] = "名字加上括號",
    ["Clamp window to screen."] = "限制視窗不超出畫面",
    ["Group with whisper windows."] = "群組包含密語視窗",

    -- TabManagement.lua --
    ["Tab Management"] = "標籤管理",
    ["Automatically manage your open windows and place them into appropriate tab groups."] = "WIM 會將您的密語對話視窗自動放到適合的群組",
    ["Automatically group whispers."] = "自動群組密語對話視窗",
    ["Place friends in their own group."] = "將好友放在同一個群組",
    ["Place guild members in their own group."] = "將公會成員放在同一個群組",
    ["Automatically group chat windows."] = "自動群組聊天對話視窗",
    ["Does not apply to windows already opened."] = "不要套用到已經開啟的對話視窗",

    -- Talent Specs --
	["Hybrid"] = "混合",

    -- Filters.lua --
    ["Show Alert"] = "顯示警告",
    ["WIM has blocked a message from %s."] = "WIM 發現阻檔訊息來自 %s",
    ["View Blocked Message"] = "檢視阻檔訊息",
    ["Blocked Message"] = "阻檔訊息",

    -- MinimapIcon.lua
    ["Show Unread Messages"] = "顯示未閱讀訊息",
    ["Show All Windows"] = "顯示所有視窗",
    ["Hide All Windows"] = "隱藏所有視窗",

    --Emoticons.lua
    ["Also"] = "並且",
    ["More"] = "更多",
    ["Emoticons"] = "心情符號",

    --Expose.lua
    ["Your conversations have been hidden in order to clear your screen while in combat. To disable this feature type"] = "你的對話視窗將在進入戰鬥狀態時被隱藏。要停用這個功能請輸入：",
    ["Expose"] = "Expose",
    ["Expose is a Mac OS X inspired feature which enables you to quickly clear your screen of windows and then restore them back to their original position."] = "Expose 是 Mac OS X 的一個增強功能，當你處於戰鬥時可快速清除畫面上的對話視窗，在戰鬥結束後再恢復顯示對話視窗",
    ["Auto hide/restore windows during combat."] = "戰鬥時自動 隱藏/恢復 對話視窗",
    ["Delay if I am typing a message."] = "如果我正在輸入訊息則延遲關閉",
    ["Border Size"] = "邊框大小",
    ["Only while in an instance."] = "只在副本中",
    ["Show Border"] = "顯示邊框",
    ["Animation Direction:"] = "動畫方向：",

    --ChatEngine.lua
    ["WIM will manage this chat type within its own message windows."] = "WIM 可收集不同頻道的對話並在各自獨立的視窗中呈現",
    ["Show Minimap Alerts"] = "顯示小地圖警示",
    ["Never pop-up on my screen."] = "絕不在我的螢幕上突然彈出",
    ["Never suppress messages."] = "絕不抑制訊息",
    ["Have WIM monitor this channel."] = "WIM 已監視這個頻道",
    ["Never Pop"] = "絕不彈出",
    ["Never have this window pop-up on my screen."] = "這個視窗絕不在我的螢幕上突然彈出",
    ["Never Suppress"] = "絕不抑制",
    ["Never suppress messages from the default chat frame."] = "預設的聊天框中絕不抑制訊息",
    ["Show unread message alert on minimap."] = "在小地圖上提示有未閱讀的訊息",
    ["No History"] = "無對話記錄",
    ["Do not record history for this channel."] = "這個頻道不記錄對話內容",
    ["World Chat"] = "一般頻道",
    ["Custom Chat"] = "自定頻道",
    ["Community Chat"] = "社群聊天",
    ["Community Chats"] = "社群聊天",
    ["Chat"] = "聊天",
    ["Play special sound for %s."] = "對 %s 撥放特別的音效",
    ["Include emotes."] = "包含表情。",
    ["Play sound when a message is received."] = "當收到訊息時撥放音效",
    ["Play sound when a message is sent."] = "當發送訊息時撥放音效",
    ["Do not play sounds for this channel."] = "這個頻道不要播放音效",
    ["No Sound"] = "無聲",
    ["Sensitivity"] = "靈敏度",
    ["Enable WorldFrame Click Detection."] = "啟用「世界框架」點擊檢測",

    --OffScreenTracker.lua
    ["WIM Window Off Screen"] = "關閉 WIM 視窗追蹤",
    ["Click to reposition."] = "點擊 重新定位",

    -- Whisper Mode Warnings
    ["Whisper Mode: In-line"] = "密語模式：內聯",
    ["Set whispers to In-line"] = "將密語設定為內聯",
    ["Message suppression requires whispers to be set to 'In-line'."] = "訊息抑制需要將密語設定為「內聯」。",
    ["It is recommended for whispers to be set to in-line in order to handle their behavior properly."] = "建議將密語設定為內聯，以便正確處理其行為。",

    -- Skins --
    ["Blue"] = "藍色",
    ["Green"] = "綠色",
    ["Red"] = "紅色",
    ["Yellow"] = "黃色",

    -- Battle.net friend consolidation (History Viewer)
    ["Battle.net Friends"] = "戰網好友",
    ["Are you sure you want to delete ALL history saved with %s, across every realm and every character on this account?"] = "您確定要刪除與 %s 在此帳號所有伺服器與所有角色儲存的所有記錄嗎？",

    -- Per-date deletion from the History Viewer filter list
    ["Are you sure you want to delete the %s history with %s across every realm and character on this account?"] = "您確定要刪除 %s 當天與 %s 在此帳號所有伺服器與角色儲存的記錄嗎？",
    ["Are you sure you want to delete the %s history for %s across every character on %s?"] = "您確定要刪除 %s 當天 %s 在 %s 所有角色儲存的記錄嗎？",
    ["Are you sure you want to delete the %s history for %s on %s?"] = "您確定要刪除 %s 當天 %s 在 %s 儲存的記錄嗎？",


    -- Modern options panel --
    ["Use modern options UI"] = "使用現代選項介面",
    ["Classic Options"] = "經典選項",
    ["Open"] = "開啟",
    ["Open the classic WIM options window."] = "開啟經典 WIM 選項視窗。",
    ["Choose the options style: /wim style [classic|modern]."] = "選擇選項樣式：/wim style [classic|modern]。",
    ["When enabled, WIM's Options entry points (minimap menu, key binding, /wim) open this panel instead of the classic WIM options window."] = "啟用後，WIM 選項的入口（小地圖選單、按鍵綁定、/wim）將開啟此面板，而非經典 WIM 選項視窗。",
    ["While a modern-only skin (such as WIM Modern) is selected, this option is enforced: those skins are configured through this panel only."] = "選擇僅現代外觀（如 WIM Modern）時，此選項會被強制開啟：這類外觀只能透過此面板設定。",

    -- Modern skin styling --
    ["Modern Skin"] = "現代外觀",
    ["These settings style WIM's modern-only skins (such as WIM Modern), which are built from the game's own interface art. They shape the History Viewer and the chat windows, and are available only while a modern-only skin is selected under General > Display Settings; with a classic skin active they are greyed out."] = "這些設定用於美化 WIM 的僅現代外觀（如 WIM Modern），它們以遊戲自帶的介面美術建構，決定記錄檢視器與聊天視窗的樣式。只有在「一般 > 顯示設定」下選擇了僅現代外觀時才可用；使用經典外觀時為灰色停用。",
    ["Disabled while a modern-only skin (such as WIM Modern) is selected: those skins carry settings the classic window has no controls for."] = "選擇僅現代外觀（如 WIM Modern）時停用：這類外觀包含經典視窗沒有對應控制項的設定。",
    ["Frame background"] = "邊框背景",
    ["Message area background"] = "訊息區域背景",
    ["Chat history background"] = "聊天記錄背景",
    ["Selection panels background"] = "選擇面板背景",
    ["Window frame background"] = "視窗邊框背景",
    ["None (game default)"] = "無（遊戲預設）",
    ["Panels see through to the game world"] = "面板透出遊戲世界",
    ["Window sees through to the game world"] = "視窗透出遊戲世界",
    ["Draws the frame background only around the panels, so a clear panel background (None or Transparent) shows the game world behind the viewer instead of the frame fill."] = "僅在面板周圍繪製邊框背景，如此當面板背景為空（無或透明）時，檢視器背後顯示的是遊戲世界而非邊框填色。",
    ["Draws the window frame background only around the message area, so a clear message area background (None or Transparent) shows the game world behind the window."] = "僅在訊息區域周圍繪製視窗邊框背景，如此當訊息區域背景為空（無或透明）時，視窗背後顯示的是遊戲世界。",

    -- Roleplay profiles (Total RP 3 / Mary Sue Protocol) --
    ["Roleplay Profiles"] = "角色扮演檔案",
    ["Enable roleplay profile integration"] = "啟用角色扮演檔案整合",
    ["Whisper windows show roleplay profile fields from Total RP 3 or any Mary Sue Protocol addon, and gain an Open RP Profile button on their shortcut bar that opens the partner's profile in the installed viewer."] = "密語視窗顯示來自 Total RP 3 或任何 Mary Sue Protocol 插件的角色扮演檔案欄位，並在捷徑列上新增「開啟 RP 檔案」按鈕，以已安裝的檢視器開啟對方的檔案。",
    ["Open RP Profile"] = "開啟 RP 檔案",
    ["Displayed profile fields"] = "顯示的檔案欄位",
    ["Whisper windows show the selected fields from the partner's Total RP 3 or Mary Sue Protocol profile. Fields left unselected -- or without profile data -- keep the standard display."] = "密語視窗顯示對方 Total RP 3 或 Mary Sue Protocol 檔案中勾選的欄位。未勾選的欄位——或沒有檔案資料的欄位——維持標準顯示。",
    ["First Name"] = "名字",
    ["Last Name"] = "姓氏",
    ["Title"] = "頭銜",
    ["Full Title"] = "完整頭銜",
    ["Race"] = "種族",
    ["Class"] = "職業",
    ["Portrait"] = "肖像",
    ["Name & Class Color"] = "名稱與職業顏色",
    ["The profile's first name, shown as the window's name text."] = "檔案中的名字，顯示為視窗的名稱文字。",
    ["The profile's last name, shown as the window's name text."] = "檔案中的姓氏，顯示為視窗的名稱文字。",
    ["The short title, shown on the window's details line."] = "短頭銜，顯示在視窗的詳細資訊列。",
    ["The long title, shown on the window's details line and portrait tooltip."] = "長頭銜，顯示在視窗的詳細資訊列與肖像提示中。",
    ["The custom race, replacing the character's race on the details line."] = "自訂種族，取代詳細資訊列中角色的種族。",
    ["The custom class, replacing the character's class on the details line."] = "自訂職業，取代詳細資訊列中角色的職業。",
    ["The profile's icon, replacing the class icon."] = "檔案圖示，取代職業圖示。",
    ["The profile's custom color, applied to the window's name text and to the class on the details line."] = "檔案的自訂顏色，套用於視窗的名稱文字與詳細資訊列中的職業。",
    ["Apply filter to character menus"] = "將過濾器套用到角色選單",

    -- History Viewer filters --
    ["No Filter"] = "無過濾器",
    ["Relative Dates"] = "相對日期",
    ["%d or more"] = "%d 則以上",
    ["Fewer than %d"] = "少於 %d 則",
    ["Results Filtered"] = "結果已過濾",
    ["-- Results Filtered --"] = "-- 結果已過濾 --",
    ["Results are hidden by the active filter. Click to open the Filters menu."] = "結果已被目前的過濾器隱藏。點擊以開啟過濾器選單。",
    ["Click to change how history is filtered."] = "點擊變更記錄的過濾方式。",
    ["Click to open the Filters menu."] = "點擊開啟過濾器選單。",
    ["Clicking the %s button on the message window will show that user's history in WIM's History Viewer."] = "點擊訊息視窗上的 %s 按鈕，將在 WIM 的記錄檢視器中顯示該玩家的記錄。",

    -- Message input & formatting --
    ["Wrap the message being typed"] = "輸入中的訊息自動換行",
    ["Limit wrapped lines"] = "限制換行行數",
    ["Visible input lines"] = "可見輸入行數",
    ["Caps how far the input field grows; past the limit the message scrolls inside it."] = "限制輸入框可成長的高度；超過上限後，訊息會在框內捲動。",
    ["The most lines the input field grows to before the message scrolls inside it."] = "輸入框在訊息開始捲動前最多可成長到的行數。",
    ["The input field wraps long messages onto multiple lines, growing downward with the message instead of scrolling it on one line."] = "輸入框會將長訊息折行為多行，隨訊息向下增長，而不是讓訊息在單行內捲動。",
    ["Timestamp Format"] = "時間戳格式",
    ["Bracket Style"] = "括號樣式",
    ["Colors"] = "顏色",
    ["Sound"] = "音效",

    -- Chat type options --
    ["Chat Windows"] = "聊天視窗",
    ["Monitor"] = "監視",
    ["Record"] = "記錄",
    ["Minimap Alerts"] = "小地圖警示",

    -- Help, bug reports & links --
    ["Found a bug?"] = "發現錯誤？",
    ["Report a Bug"] = "回報錯誤",
    ["Reports are welcome! Click below and follow the instructions in the bug report template."] = "歡迎回報！點擊下方並依照錯誤回報範本中的說明操作。",
    ["Visit us on GitHub"] = "造訪我們的 GitHub",
    ["Click to copy the link."] = "點擊複製連結。",
    ["Press Ctrl+C to copy the link, then open it in your browser."] = "按 Ctrl+C 複製連結，然後在瀏覽器中開啟。",

    -- Debugging & development slash commands --
    ["Clear the captured debug log."] = "清除已擷取的除錯日誌。",
    ["Set debugging level: /wim debug [0|1|2]. 2 adds verbose chat event tracing."] = "設定除錯等級：/wim debug [0|1|2]。2 會加入詳細的聊天事件追蹤。",
    ["Snapshot the next modern context menu while it is open."] = "在下一個現代右鍵選單開啟時為其擷取快照。",
    ["Snapshot UI widget state for skin development: /wim snap all | <Frame.Dot.Path> (bare /wim snap lists the arguments)."] = "擷取介面元件狀態供外觀開發使用：/wim snap all | <Frame.Dot.Path>（直接輸入 /wim snap 會列出參數）。",

    -- Tutorials & notices --
    ["WIM is currently running. To access WIM's wide array of options type:"] = "WIM 正在執行中。若要存取 WIM 的完整選項，請輸入：",
    ["WIM's message window has been hidden to WIM's Minimap Icon. If you want to end a conversation, you may do so by <Shift-Clicking> the close button."] = "訊息視窗已隱藏至 WIM 的小地圖圖示。若要結束對話，可以<Shift+點擊>關閉按鈕。",
    ["If you want all windows to be this size, you can set the default window size within WIM's options."] = "若希望所有視窗都採用此尺寸，可以在 WIM 選項中設定預設視窗尺寸。",
    ["You can <Shift-Click> a tab and drag it out into it's own window."] = "您可以<Shift+點擊>一個分頁並將其拖出，使其成為獨立視窗。",
    ["You received a whisper which was hidden due to your current activity. You can change how whispers behave in WIM's options by typing"] = "您收到一則因目前活動而被隱藏的密語。要變更密語的行為方式，請在 WIM 選項中設定，或輸入",
    ["Sets the game's Social > Whisper Mode setting to In-line. Without it, suppressed whispers would vanish into a popout chat tab."] = "將遊戲的「社交 > 密語模式」設定為「內聯」。否則，被抑制的密語會消失在彈出的聊天分頁中。",

    -- Community channel maintenance --
    ["Toggle the experimental community channel re-add repair (mutates chat window channels)."] = "開啟實驗性的社群頻道重新加入修復（會更動聊天視窗的頻道）。",
    ["Toggle whether WIM focuses community streams at login."] = "控制 WIM 登入時是否聚焦社群串流。",

    -- Misc --
    ["Age"] = "年齡",
    ["Users in %s"] = "%s 的玩家",

    -- History Viewer filter modes --
    ["Sent by Me"] = "由我傳送",
    ["Sent by Them"] = "由對方傳送",
    ["Active Days"] = "活躍天數",
    ["Last 1 Day"] = "最近 1 天",
    ["Last 7 Days"] = "最近 7 天",
    ["Last 30 Days"] = "最近 30 天",
    ["Last 90 Days"] = "最近 90 天",


    -- Chrome background names --
    ["None (fully clear)"] = "無（完全透明）",
    ["Transparent"] = "透明",
    ["Rock"] = "岩石",
    ["Marble"] = "大理石",
    ["Dark Marble"] = "暗色大理石",
    ["Bank"] = "銀行",
    ["Guild Vault"] = "公會銀行",
    ["Dark Sandstone"] = "暗色砂岩",
    ["Parchment (Tileable)"] = "羊皮紙（可平鋪）",
    ["Quest Parchment"] = "任務羊皮紙",
    ["Raid Frame"] = "團隊框架",
    ["Destiny"] = "命運",
    ["Stationery (Auction)"] = "信紙（拍賣場）",
    ["Stationery (Illustrated)"] = "信紙（插圖）",
    ["Stationery (Orgrimmar)"] = "信紙（奧格瑪）",
    ["Stationery (Thunder Bluff)"] = "信紙（雷霆崖）",
    ["Stationery (Undercity)"] = "信紙（幽暗城）",
    ["Stationery (Plain)"] = "信紙（素色）",
    ["World Map 1"] = "世界地圖 1",
    ["World Map 2"] = "世界地圖 2",
    ["Achievement Stats"] = "成就統計",
    ["Adventure Map Parchment"] = "冒險地圖羊皮紙",
    ["Collections"] = "收藏品",
    ["Frame: Alliance"] = "邊框：聯盟",
    ["Frame: Horde"] = "邊框：部落",
    ["Frame: Neutral"] = "邊框：中立",
    ["Frame: Marine"] = "邊框：海軍",
    ["Frame: Mechagon"] = "邊框：麥卡貢",
    ["Frame: Kyrian"] = "邊框：琪瑞安",
    ["Frame: Necrolord"] = "邊框：死靈領主",
    ["Frame: Night Fae"] = "邊框：夜妖精",
    ["Frame: Venthyr"] = "邊框：Venthyr",
    ["Frame: Oribos"] = "邊框：奧利波斯",
    ["Frame: Dragonflight"] = "邊框：巨龍崛起",
    ["Frame: The War Within"] = "邊框：地心之戰",
    ["Class Hall"] = "職業大廳",
    ["Class Hall (Internal)"] = "職業大廳（內部）",
    ["Garrison Landing Page"] = "要塞登陸頁",
    ["Garrison Mission"] = "要塞任務",
    ["Ship Mission Parchment"] = "艦船任務羊皮紙",
    ["Garrison UI"] = "要塞介面",
    ["Garrison UI 2"] = "要塞介面 2",
    ["Credits: Classic"] = "製作人員：經典版",
    ["Credits: Burning Crusade"] = "製作人員：燃燒的遠征",
    ["Credits: Wrath"] = "製作人員：巫妖王之怒",
    ["Credits: Cataclysm"] = "製作人員：浩劫與重生",
    ["Credits: Mists of Pandaria"] = "製作人員：潘達利亞的迷霧",
    ["Credits: Warlords"] = "製作人員：德拉諾之霸",
    ["Credits: Legion"] = "製作人員：軍臨天下",
    ["Credits: Battle for Azeroth"] = "製作人員：決戰艾澤拉斯",


    -- Skin & options style notices --
    ["WIM: the selected skin (%s) is configured through the modern options UI; the classic window is unavailable while it is active."] = "WIM：所選外觀（%s）透過現代選項介面設定；啟用期間，經典視窗無法使用。",
    ["WIM: the selected skin (%s) requires the modern options UI; switch to another skin first."] = "WIM：所選外觀（%s）需要現代選項介面；請先切換到其他外觀。",
    ["WIM options style: Modern (native Options > AddOns)."] = "WIM 選項樣式：現代（遊戲內「選項 > 插件」）。",
    ["WIM options style: Classic (WIM window)."] = "WIM 選項樣式：經典（WIM 視窗）。",

});
